### ISSUE TITLE
Log page can consume all available memory

### ISSUE THREAD

**Issue by jon5353** [MultiMC/MultiMC5#1008]
Hi guys. Recently updated to the new MultiMC update and now I get crashes on my single player world. I've noticed that it usually tends to happen when I press J to open journeymap (not 100% positive though) The error is weird. I'll get a mass amount of C++ Runtime Library dialogues, telling me the program requested to stop working. I'll hit OK on one, then the windows dialog will come up telling me that MultiMC has stopped responding and I just close it. My minecraft instance works fine though. I'm not sure if there are any logs or anything that I can post. The logs in the root folder don't seem to be telling me anything. I'll post them if someone wants me to. Any ideas? Should I just downgrade?

**Comment by peterix** [comment]
Right. No amount of pressing 'j' does that for me... Would have been an easy thing to test :P

If you look at the console window, do you see a LOT of scrolling text after the game fully loads? Do you see lots of scrolling text with journeymap open?

**Comment by jon5353** [comment]
I have noticed Compact Machines has been throwing a lot of errors towards some null fluid (even though there are none)
I'm gonna disable it for now and run around. I'll get back to you on it.

**Comment by peterix** [comment]
Yeah, if that happens, it can just use up all the available memory for the log in the console window (and in case of MultiMC on Windows, that's about 2GB, because it's a 32bit application).

For now, you can get around it without disabling any mods by turning off logging - there's a checkbox on the console window for that.

Anyway, the same mod is probably also spamming your harddrive. Some mods love their multi-GB log files ~_~

**Comment by peterix** [comment]
As for null fluid: you may want to experiment with Forge versions. The fluids got changed in some of the more recent versions.

**Comment by peterix** [comment]
Fixed in develop
