### ISSUE TITLE
Minecraft jar is not created in offline mode

### ISSUE THREAD

**Issue by MagicCraftMaster** [MultiMC/MultiMC5#1034]
before multimc 0.4.7 (0.4.6 and earlier) optifine could be added as the only jar mod and now it wont work with the same file and i need 1.8.4 and my PC is to weak for no optifine. the game crashes when i launch it

**Comment by peterix** [comment]
Works here, no issues, on multiple machines and operating systems.

I would suggest using the Upload button on the console/log window.

**Comment by MagicCraftMaster** [comment]
this happened

Log:
http://paste.ee/p/0lT1W

**Comment by peterix** [comment]
Alright. The jar isn't there, even though it should. That's quite strange, because it should be created on instance start.

Can you also post the MultiMC log file? The current one is MultiMC-0.log in the MultiMC folder, with the numbers going up the older the file is.

Run this instance, post the file. It should show what's happening.

**Comment by MagicCraftMaster** [comment]
this time it ran but the only difference was it wasnt in offline mode aka no connection with internet on

**Comment by peterix** [comment]
Right. offline mode. That's something I didn't think about.

Interesting.

I should be able to fix this quickly :)

**Comment by peterix** [comment]
Fixed in latest develop.
