### ISSUE TITLE
FTB Instance Whitelist

### ISSUE THREAD

**Issue by brandon3055** [MultiMC/MultiMC5#1061]
I only ever use 3 of the FTB packs and the other 23 are just unwanted clutter. It would be nice if i could white list the 3 packs i use so they are the only ones that show up in the FTB group.

**Comment by 02JanDal** [comment]
FTB is moving towards being import-only, which would mean only instances you have explicitly imported will show up.

A possible solution that also applies to all types of instances is something similar to what [the IRC client quassel does](http://bugs.quassel-irc.org/projects/1/wiki/Buffer_Views#ShowHide-Chats): From the start all instances are visible, but you can right-click them to hide them. Through a global switch you can make all instances (including hidden) visible with checkboxes to select if they will be visible by default.

Since this means storing state from the view see also #851.

**Comment by peterix** [comment]
If you do not use them... why not delete them?

**Comment by peterix** [comment]
Anyway, FTB will become import only at some point. Probably when they fully transition to the curse client.

**Comment by peterix** [comment]
Hell, it might become 'gone'.

**Comment by peterix** [comment]
Closing, won't implement this.
