### ISSUE TITLE
MultiAuth: Change the accounts drop down menu

### ISSUE THREAD

**Issue by calloatti** [MultiMC/MultiMC5#1063]
In the accounts dropdown menu, instead of displaying the account email and account name in two lines, with the account email disabled, display it in one line like this:

account-name (account email)

**Comment by peterix** [comment]
1. it would be better if the e-mail wasn't there. e-mail is possibly private information you don't want to show -> that means just a list of profiles.
2. if there is no skin, show at least a placeholder skin (steve for minecraft?)
3. if there is a profile selected, show its name instead of 'Accounts'

**Comment by peterix** [comment]
I believe this has been addressed in the multiauth rebase branch. If not, it will be.
