### ISSUE TITLE
Profiles with no skin set don't get their default Alex or Steve skin

### ISSUE THREAD

**Issue by calloatti** [MultiMC/MultiMC5#1072]
In Windows 7, using MultiMC 0.4.8-dev 593
I do not have a skin in my user, and checking MultiMC-1.log I can these lines repeated four times:

Downloading  "http://skins.minecraft.net/MinecraftSkins/myusername.png"
Failed  "http://skins.minecraft.net/MinecraftSkins/myusername.png"  with reason  203

The request is getting a 404 not found, since there is no skin for my user.

I am shure this was never encountered since everyone involved has a skin, so the change sugested is to stop trying to download a user skin after one try if you get a 404, no need to try 3 more times.

Maybe just download default skin from http://assets.mojang.com/steve.png when getting a 404

**Comment by 02JanDal** [comment]
The changes in #1007 use crafatar instead for skins, which returns a steve or alex (depending on the UUID) skin if there is no skin for the user available, so this will likely be fixed by that.

**Comment by peterix** [comment]
This isn't at all related to skins.

**Comment by peterix** [comment]
This will use the above mentioned resource system, minus crafatar because it doesn't work anyway,

**Comment by jomo** [comment]
> minus crafatar because it doesn't work anyway

Crafatar co-author here. What are the issues you're having?

**Comment by peterix** [comment]
It was mostly with profiles that do not have a set skin/skin type yet.

This one has the problem: `_Peterix_`

I'll re-test all of it, but what I've seen before is differences between using a browser, using curl and using wget... Some of it worked, some of it didn't.

**Comment by peterix** [comment]
This account is supposed to have the alex model/skin, but nothing is set (yet).

**Comment by peterix** [comment]
https://sessionserver.mojang.com/session/minecraft/profile/4363286331474710a1c360f43fbf380a

```
{"id":"4363286331474710a1c360f43fbf380a","name":"_Peterix_","properties":[{"name":"textures","value":"eyJ0aW1lc3RhbXAiOjE0NDA0MzA1NzMzOTAsInByb2ZpbGVJZCI6IjQzNjMyODYzMzE0NzQ3MTBhMWMzNjBmNDNmYmYzODBhIiwicHJvZmlsZU5hbWUiOiJfUGV0ZXJpeF8iLCJ0ZXh0dXJlcyI6e319"}]}
```

->

```
{"timestamp":1440430573390,"profileId":"4363286331474710a1c360f43fbf380a","profileName":"_Peterix_","textures":{}}
```

So only profile ID is used to determine skin info.

**Comment by jomo** [comment]
As you can see, that account has no skin (`"textures":{}`). Other than that, you should send requests for UUIDs because there is no (reliable) way for us to find out if a username supposed to be alex.

See:
https://crafatar.com/avatars/4363286331474710a1c360f43fbf380a
![uuid image](https://crafatar.com/avatars/4363286331474710a1c360f43fbf380a)
vs
https://crafatar.com/avatars/_Peterix_
![name image](https://crafatar.com/avatars/_Peterix_)

**Comment by peterix** [comment]
```
[mrazekp@infernal test]$ wget https://crafatar.com/avatars/4363286331474710a1c360f43fbf380a
--2015-08-24 17:43:56--  https://crafatar.com/avatars/4363286331474710a1c360f43fbf380a
Resolving crafatar.com (crafatar.com)... 104.28.9.115, 104.28.8.115, 2400:cb00:2048:1::681c:873, ...
Connecting to crafatar.com (crafatar.com)|104.28.9.115|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-08-24 17:43:57 ERROR 404: Not Found.
```

**Comment by peterix** [comment]
There actually is a very reliable way to do this, but the code is nasty bit shifting mess copied out of a java class...

**Comment by peterix** [comment]
```
curl https://crafatar.com/avatars/4363286331474710a1c360f43fbf380a
�PNG

... binary mess continues
```

So wget doesn't work while curl does.

**Comment by jomo** [comment]
It sends a 404 because the user has no skin. It still sends the image in the body, though.
This [has been changed](https://github.com/crafatar/crafatar/issues/111) in the latest version (which soon to be deployed)

in your case, wget cancels the download on 404. Check the man page to see how to change that.

Differences between browser and CLI can also occur when your browser has a cached version of some image, while curl/wget don't have a cache.

> There actually is a very reliable way to do this

Yes, using the hash of the UUID, which we do. You can't do that on usernames.

**Comment by peterix** [comment]
That's all kinds of wrong.

**Comment by jomo** [comment]
What is wrong, exactly?

**Comment by peterix** [comment]
Returning a 404... I would expect a redirect, or a 203

**Comment by jomo** [comment]
Yes the 404 was wrong. That's why we fixed it and will soon roll it out :smiley:

**Comment by peterix** [comment]
Alright :smile:

**Comment by jomo** [comment]
Just FYI:
```shell
wget --content-on-error "https://crafatar.com/avatars/4363286331474710a1c360f43fbf380a"
```
should get you the same result using wget :)

**Comment by peterix** [comment]
It does. I'll just assume this will get fixed in time for 0.4.8 though.

This issue is actually a bug in MultiMC anyway, because we use the uuid blindly. It was all independently reverse-engineered and I skipped a bunch of the API querying steps.

So if I can use crafatar this way without having an extra hacky '--content-on-error'-like option, I certainly will. Less code on my side :)

**Comment by peterix** [comment]
I assume you are fine with the launcher using the service this way?

**Comment by jomo** [comment]
Yeah, we will roll out soon (which comes along a bunch of other improvements too). Given that there are more than 20 open issues for 0.4.8, I'm sure it will be fixed in time!

> I assume you are fine with the launcher using the service this way?

Yes, we would love to see MultiMC using Crafatar  :heart_eyes:

**Comment by jomo** [comment]
Just letting you know: We've rolled out the update and default skins are now served with a 200 status code.

**Comment by peterix** [comment]
fixed in develop. multiauth branch will have to wait.
