### ISSUE TITLE
Environment variables aren't kept across updates

### ISSUE THREAD

**Issue by SoniEx2** [MultiMC/MultiMC5#1100]
If MultiMC updates and restarts, environment variables (mainly LD_PRELOAD) get lost so you can't use Steam overlay.

**Comment by 02JanDal** [comment]
Are you modifying the launcher script (`MultiMC`)? Or how are the variables set?

**Comment by SoniEx2** [comment]
Steam sets them. I only replace the PulseAudio sink (I should actually check if it kept that variable...)

**Comment by 02JanDal** [comment]
Alright, so this is what's happening:

[MultiMC#21-24](https://github.com/MultiMC/MultiMC5/blob/develop/application/package/linux/MultiMC#L21-L24): When MultiMC is started it puts the value of LD_PRELOAD (as set by Steam in this case) to GAME_PRELOAD, and then sets LD_PRELOAD to be empty.

When launching the game GAME_PRELOAD is set back to LD_PRELOAD so that the game sees it's original value, as set by Steam.

When updating though, the script is run again. LD_PRELOAD is empty from the first run of the script (the value is in GAME_PRELOAD). The same lines as above now set GAME_PRELOAD to be empty.

What now? I'd argue that it's simple enough to just restart MultiMC manually, though that can be annoying. The fix would be to check if GAME_PRELOAD is already set, and if it is not change it (`export GAME_PRELOAD=${GAME_PRELOAD:=LD_PRELOAD}`). @peterix sound good?

**Comment by peterix** [comment]
sounds about right.

**Comment by peterix** [comment]
This should now be fixed in develop. Reopen if it isn't.
