### ISSUE TITLE
No sensible error message when the per-instance java setting are wrong on launch

### ISSUE THREAD

**Issue by youraveragedoge** [MultiMC/MultiMC5#1124]
I was recently trying to run a friend's modpack on my Mac using MultiMC and the instance file was export correctly but when I try to run the instance I get a loading bar that opens in a new window that says "Stuck on Updating assets index..." I wait for the bar to load but it is stuck at 100%. If you would like some sort of log, please instruct me how to give one as I don't know how to. Thank you in advance!

**Comment by peterix** [comment]
The log should be inside the .app - look for MultiMC-#.log, where # is 0-5. 0 is the latest one.

**Comment by youraveragedoge** [comment]
Here is the pastebin link for the "MultiMC-0.log" file: http://pastebin.com/0nsyQYC3

**Comment by peterix** [comment]
Nothing concolusive in that log...

The current develop build uses a significantly different launch process... maybe it would fix it?

**Comment by peterix** [comment]
Actually likely related to this:
#1133

Try to re-detect java. I'm going to close this, assuming it's the same issue.

**Comment by jilleJr** [comment]
When I got this error I was too playing around with exporting modpacks. And since it saves the java path in the config it transfers the java path to the other computer that you install the modpack on.

Idk if you (@peterix) wants to do something about this, maybe have it ignore the java path when importing a pack?
