### ISSUE TITLE
MultiMC vanished from my Computer files!

### ISSUE THREAD

**Issue by EthanCoy** [MultiMC/MultiMC5#1161]
I run a YouTube channel and have several different series of Minecraft that run through MultiMC. I was currently away for about a week and when I came home, MultiMC and all the contents have been removed. I am very disappointed after i redownloaded the application, logged into my account, and all my worlds have been removed. This is a disaster! All the hard work that I have put into things have been removed! 

Please tell me there is a way for me to get everything back!

**Comment by peterix** [comment]
That is indeed a disaster. Do you have backups?

**Comment by peterix** [comment]
If the folder is gone - the whole thing is pretty much gone.
Maybe just search for the files on your system?

Did anyone mess with your computer while you were away?

**Comment by EthanCoy** [comment]
I didn't think I would need backups outside of this program, I should have made one though.

I've also done a lot of searches through my computer, and there are no traces of my worlds.

**Comment by peterix** [comment]
Right. you might be able to recover some of it with some undelete program... depends on how much was written to the drive since though. If that's something you want to try:
the key is to run the OS from a second drive not attach/mount the original drive to prevent things from destroying the original data.

It could live in a temp folder, which got cleaned. This can happen and did happen to people who used winrar and just ran the exe from that on Windows. It extracted everything into temp, MultiMC ran fine, and then the stuff just disappeared. Current MultiMC versions check if they are running from temp and warn you.

Plain old bug? But there's really nothing in MultiMC that would allow it to delete itself entirely... AFAIK
An update can get broken, but the update system touches only the application files, not data...

I wonder what actually happened...

**Comment by spannerman79** [comment]
@EthanCoy what OS are you on?

Personally I think someone else had access to your system and removed MultiMC not knowing what it was.

**Comment by EthanCoy** [comment]
I'm on Mac OS X. 
And no one was on this computer. My mom was watching my house while I was away and she wouldn't even know how to turn it on.

I am ok with starting a new world, but how do I save backups if this happens again?

**Comment by peterix** [comment]
Everything is in the .app - unlike many other applications, MultiMC keeps everything in one place.

Maybe that's the issue? If you replace the .app, everything is gone.

**Comment by peterix** [comment]
Don't know what happened here really. Make sure to keep a backup of the app itself - it contains all the data.
