### ISSUE TITLE
Game exited with exitcode -1.

### ISSUE THREAD

**Issue by legoman9570** [MultiMC/MultiMC5#1270]
Here is the crash report http://paste.ee/p/mfv1B#

Along with this my textures are completely screwed up, everything is either green or white and my items are white squares.

**Comment by peterix** [comment]
Well, it ran out of memory. Give it more than the default 512MB - 1GB :)

**Comment by legoman9570** [comment]
Ok so I changed the minimum memory allocation from 512MB to 1024MB and nothing changed.

**Comment by peterix** [comment]
you need to change the maximum.

**Comment by legoman9570** [comment]
I tried that it only goes up to 1152MB and still nothing changes

**Comment by peterix** [comment]
`Operating System: Windows 10 (x86) version 10.0`

Looking at that graphics card (I have the same, it's decent), I can tell the system isn't **that** old. Why the 32bit OS?

You are limited to about 1500MB because of that. You'll either have to use a 64bit OS and have more RAM, or remove some mods/textures/whatever to be able to play.

**Comment by legoman9570** [comment]
Where does it say I have a 32bit operating system?

**Comment by peterix** [comment]
In the log, reported by Minecraft:
```
-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 461222224 bytes (439 MB) / 519110656 bytes (495 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 355.82' Renderer: 'GeForce GTX 750/PCIe/SSE2'
```

**Comment by legoman9570** [comment]
On my screen it has Windows 10 (x86) I don't see any x32

**Comment by peterix** [comment]
x86 means 32bit. otherwise it would be x86_64, amd64, x64, or something along those lines.

http://www.tenforums.com/tutorials/4399-system-type-32-bit-x86-64-bit-x64-windows-10-a.html

**Comment by legoman9570** [comment]
Oh I see, so what can I do to fix it?

**Comment by peterix** [comment]
Really, I don't know what you can do. If you have a 64bit CPU, you absolutely should run a 64bit OS. To do otherwise is basically throwing away the system resources.

Check the CPU, just to be sure. If it's 64bit -- and it should be -- you should install 64bit Windows.

I think the license should be usable for both 32bit and 64bit, so even if you don't have the installation media, you should be able to download the right version.

**Comment by legoman9570** [comment]
Ok Thanks!!

**Comment by peterix** [comment]
How much memory does the system have?

**Comment by legoman9570** [comment]
I'm using 260GB and I have 670GB+ left over

**Comment by peterix** [comment]
http://www.tenforums.com/tutorials/4399-system-type-32-bit-x86-64-bit-x64-windows-10-a.html

What is the number next to Installed RAM on your system?

**Comment by legoman9570** [comment]
Oh derp, 8GB

**Comment by peterix** [comment]
Right. If the CPU is a 64bit one, definitely get a 64bit OS and java.

**Comment by legoman9570** [comment]
Ok thanks for the help!!
