### ISSUE TITLE
I always fail to compile

### ISSUE THREAD

**Issue by mainwindow** [MultiMC/MultiMC5#1344]
There are too many problems to compile the source.
1. Step too cumbersome, I configured one hour.
2. Once configured, Quazip source code download failed, I manually re-download extract.
3. Help documentation does not mention zlib installation, I had to be added manually.
4. Everything is ready, the compilation process popping error: Can not find parameters "-Werror=return-type"
5. I manually remove all -Werror = return-type, continue to compile, perhaps a success? But after a few minutes again encountered more problems, Grammatical errors.
I use Visual Studio 2010 with SP1, Qt 5.5.1, and cmake 3.4.0.

So, how can I really do?
I think the configuration steps to compile before it is too cumbersome, and since each person's system environment, there may be a lot of unforeseen problems.

**Comment by 02JanDal** [comment]
1. Compiling manually is not recommended unless you have experience with software development.
2. This might be interesting, did you get any errors?
3. [It does](https://github.com/MultiMC/MultiMC5/blob/develop/BUILD.md#dependencies)
4. & 5. Did you read the documentation? "The project will simply not compile using Microsoft build tools, because that's not something we do." MSVC (the compiler used by Visual Studio) is not supported, use MinGW instead. Apart from that VS2010 is really old, we use a lot of modern C++ features that are most likely not supported yet in that compiler.

Unless you have a really, really good reason you should use the prebuilt packages from [multimc.org](https://multimc.org/), otherwise make sure you're really following [the instructions](https://github.com/MultiMC/MultiMC5/blob/develop/BUILD.md#windows).

If there is anything still unclear don't hesitate to comment, it's after all not impossible that you've run into a bug with QuaZip, or that the build documentation is outdated.

**Comment by peterix** [comment]
Pretty much, that.

MSVC 2010 is obsolete. You might have a better chance with 2015, if you really must use that... but you don't, and all Windows version of the GNU toolchain > 4.9 should be fine. Free downloads, usually no extra bloat :)

**Comment by mainwindow** [comment]
@peterix After a long attempt, I using MinGW 4.9 to compile the code, and it works. So you are right, MSVC 2010 is obsolete( But 2015 is also failed ;) ).
Thank you very much!

**Comment by mainwindow** [comment]
Oh, sorry, I did not see so soon to update (a few minutes ago), Thank you!
