### ISSUE TITLE
Memory allocation error

### ISSUE THREAD

**Issue by daburger17** [MultiMC/MultiMC5#1395]
When I load minecraft it says "minecraft has run out of memory", when i try to allocate more memory it gives this error.
http://paste.ee/p/tfQcz

**Comment by 1726379897** [comment]
Get the 64 Bit edition of MMC.
64 Bit java as well
This assuming your using a 64-bit CPU. Otherwise java can only use 1GB.

**Comment by daburger17** [comment]
i don't have MMC 64 bit, but when I download windows 32/64 bit MMC it only downloads 32 bit. Where can I get the 64 bit version?

**Comment by 1726379897** [comment]
Can you identify to me what cpu you have?

**Comment by peterix** [comment]
There is no 64bit version of MultiMC on Windows, because it is not needed.

Open up the MultiMC settings (icon with computer screen and screwdriver on the top toolbar, unless you changed the icon theme), then the Java page and click Auto-Detect.

Select a 64bit version of java. If there isn't one, install it. You can get all of the current downloads here:
http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

**Comment by peterix** [comment]
And yes, to use more than 1500MB of memory in java, on Windows, the CPU, the OS and Java have to all be 64bit.

Also note that you do need to have the actual free physical memory. You are trying to use ~3.7GB of it. It might simply not be available. If, for example, your system has 4GB of RAM, you'll never have enough free to use 3.7GB for Minecraft.

**Comment by peterix** [comment]
See:
https://github.com/MultiMC/MultiMC5/wiki/Java-settings
https://github.com/MultiMC/MultiMC5/wiki/Increasing-Java%27s-memory-allocation

**Comment by daburger17** [comment]
My computer is 16 GB of RAM so I think it's a problem with Java.

**Comment by daburger17** [comment]
Thank You everyone that helped! It worked!!

**Comment by peterix** [comment]
Alright, good to hear that :)
