### ISSUE TITLE
MultiMC crashes on launch (OS X 10.7.5)

### ISSUE THREAD

**Issue by fireredlily** [MultiMC/MultiMC5#1410]
```
OS: Mac OS X 10.7.5
MultiMC version: 0.4.8.684

After updating my MultiMC to the latest version, I now cannot load MultiMC at all. I get the following in the system console log:

Process:         launchd [7437]
Path:            /Applications/MultiMC.app/Contents/MacOS/MultiMC
Identifier:      org.multimc.MultiMC5
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [125]

Date/Time:       2016-01-17 18:28:01.967 -0600
OS Version:      Mac OS X 10.7.5 (11G63)
Report Version:  9

Interval Since Last Report:          300036 sec
Crashes Since Last Report:           17
Per-App Crashes Since Last Report:   16
Anonymous UUID:                      32677E4F-79F4-4F44-AE71-5A78572B8BC0

Crashed Thread:  Unknown

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x00007fff5fc01028

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000055  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x0000000000000000
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff5fc01028  rfl: 0x0000000000010203  cr2: 0x00007fff5fc01028
Logical CPU: 0

Binary images description not available


External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 1
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 5640
    thread_create: 1
    thread_set_state: 0

Model: iMac12,1, BootROM IM121.0047.B1F, 4 processors, Intel Core i5, 2.5 GHz, 8 GB, SMC 1.71f22
Graphics: AMD Radeon HD 6750M, AMD Radeon HD 6750M, PCIe, 512 MB
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1333 MHz, 0x80AD, 0x484D54333531533642465238432D48392020
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1333 MHz, 0x80AD, 0x484D54333531533642465238432D48392020
AirPort: spairport_wireless_card_type_airport_extreme (0x168C, 0x9A), Atheros 9380: 4.0.67.5-P2P
Bluetooth: Version 4.0.8f17, 2 service, 18 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: WDC WD5000AAKS-402AA0, 500.11 GB
Serial ATA Device: OPTIARC DVD RW AD-5690H
USB Device: FaceTime HD Camera (Built-in), apple_vendor_id, 0x850b, 0xfa200000 / 3
USB Device: hub_device, 0x0424  (SMSC), 0x2514, 0xfa100000 / 2
USB Device: GameCapture HD, 0x0fd9, 0x0051, 0xfa120000 / 6
USB Device: Yeti Stereo Microphone, 0xb58e, 0x9e84, 0xfa130000 / 5
USB Device: BRCM2046 Hub, 0x0a5c  (Broadcom Corp.), 0x4500, 0xfa110000 / 4
USB Device: Bluetooth USB Host Controller, apple_vendor_id, 0x8215, 0xfa111000 / 7
USB Device: hub_device, 0x0424  (SMSC), 0x2514, 0xfd100000 / 2
USB Device: IR Receiver, apple_vendor_id, 0x8242, 0xfd120000 / 4
USB Device: Internal Memory Card Reader, apple_vendor_id, 0x8403, 0xfd110000 / 3
```

No MultiMC log is generated, and I've tried removing the app entirely and doing a fresh install of MultiMC from the website, but I still get a crash immediately on trying to open it.

**Comment by glynndaddy** [comment]
Experiencing same issue.  Here is the report.

Process:         launchd [836]
Path:            /Users/USER/Desktop/MultiMC.app/Contents/MacOS/MultiMC
Identifier:      org.multimc.MultiMC5
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [136]

Date/Time:       2016-01-17 21:14:44.303 -0600
OS Version:      Mac OS X 10.7.3 (11D50b)
Report Version:  9

Interval Since Last Report:          10011380 sec
Crashes Since Last Report:           75
Per-App Crashes Since Last Report:   17
Anonymous UUID:                      5747FE52-BDE6-4503-A056-568E468E50E1

Crashed Thread:  Unknown

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x00007fff5fc01028

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000055  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x0000000000000000
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff5fc01028  rfl: 0x0000000000010203  cr2: 0x00007fff5fc01028
Logical CPU: 0

Binary images description not available


External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 2
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 1048
    thread_create: 2
    thread_set_state: 0

Model: MacBookPro5,5, BootROM MBP55.00AC.B03, 2 processors, Intel Core 2 Duo, 2.26 GHz, 8 GB, SMC 1.47f2
Graphics: NVIDIA GeForce 9400M, NVIDIA GeForce 9400M, PCI, 256 MB
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1067 MHz, 0x0198, 0x393930353432382D3032302E4130304C4620
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1067 MHz, 0x0198, 0x393930353432382D3032302E4130304C4620
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x8D), Broadcom BCM43xx 1.0 (5.100.98.75.19)
Bluetooth: Version 4.0.3f12, 2 service, 18 devices, 1 incoming serial ports
Network Service: AirPort, AirPort, en1
Network Service: Ethernet Adaptor (en2), Ethernet, en2
Serial ATA Device: Hitachi HTS545016B9SA02, 160.04 GB
Serial ATA Device: HL-DT-ST DVDRW  GS23N
USB Device: Internal Memory Card Reader, apple_vendor_id, 0x8403, 0x26500000 / 2
USB Device: Built-in iSight, apple_vendor_id, 0x8507, 0x24400000 / 2
USB Device: Apple Internal Keyboard / Trackpad, apple_vendor_id, 0x0236, 0x04600000 / 4
USB Device: IR Receiver, apple_vendor_id, 0x8242, 0x04500000 / 3
USB Device: Logitech USB Optical Mouse, 0x046d  (Logitech Inc.), 0xc018, 0x04100000 / 2
USB Device: BRCM2046 Hub, 0x0a5c  (Broadcom Corp.), 0x4500, 0x06100000 / 2
USB Device: Bluetooth USB Host Controller, apple_vendor_id, 0x8213, 0x06110000 / 3

**Comment by peterix** [comment]
I can't see anything useful in these crash reports. Only that it crashed. Normally, the backtrace part would have some useful information.

As for the question from IRC: Everything is inside the .app. Configs, instances, everything.

**Comment by peterix** [comment]
https://en.wikipedia.org/wiki/Mac_OS_X_Lion

... 10.7 is two years out of support and 10.7.3 is not even the latest version of 10.7. Just what is going on here?

**Comment by glynndaddy** [comment]
> peterix.  I know nearly nothing about Mac.  This is an older MacBookPro and I am not certain why or how the OS is not updated to the latest.

Thanks for answering my question from IRC.
All I know what that 0.4.7 was working great, had ~15 instances configured, and accepted the upgrade to 0.4.8 when it was presented tonight.  When I go to run, get the popup that MutliMC quit unexpectedly.  I've rebooed the Mac and still the same.  I'm on the latest JAVA version if that means anything.

I guess the upgraded created a new folder in my DOWNLOADS folder called 'MultiMC 2.  The original 'MULTIMC' folder is still in my DOWNLOADS folder, and I can run it, it runs 0.4.7 successfully.  Strangely though, all my instances are gone (except for one very old one).

Sorry I can't provide more / better details.

**Comment by peterix** [comment]
I'm assuming you made a copy of the app at some point, and the old copy works, while the new one doesn't.

Open up the .app folders. There should be an 'instances' folder inside. Copy it over to the old copy of MultiMC that works for you.

**Comment by Builderb0y** [comment]
Getting the same error, also on 10.7.5. It even crashes before the "are you sure you want to open this program" dialog comes up. Also interesting is that it's the same memory address each time (0x00007fff5fc01028). No backtrace for me either.

**Comment by Builderb0y** [comment]
> Because of the reverted Qt version, OSX 10.7 might work again. If it does, please do tell, it would help with figuring out what went wrong there :)

It doesn't. 0.4.10.693 has the exact same error.

**Comment by peterix** [comment]
Well, now we know it's not Qt.

**Comment by Builderb0y** [comment]
"otool" isn't recognized in the terminal. Either I'm in the wrong directory, it's something I have to download, or it simply doesn't exist in lion (that site does say it's for leopard). Also tried "ldd" and it also was not recognized.

**Comment by peterix** [comment]
Alright. I am buying a copy of 10.7 from Apple and will set it up on my mac mini... as long as it doesn't protest against running :)

**Comment by peterix** [comment]
Here are all the previous versions I could piece together:

https://files.multimc.org/downloads/mmc-stable-osx64-0.4.5-33.zip
https://files.multimc.org/downloads/mmc-stable-osx64-0.4.6-521.zip
https://files.multimc.org/downloads/mmc-stable-osx64-0.4.7-553.zip
https://files.multimc.org/downloads/mmc-stable-osx64-0.4.8-684.zip
https://files.multimc.org/downloads/mmc-stable-osx64-0.4.9-688.zip
https://files.multimc.org/downloads/mmc-stable-osx64-0.4.10-693.zip

You will just have to move over the data from inside the .app.

Files:
* multimc.cfg
* metacache
* accounts.json

Folders:
* accounts
* assets
* cache
* icons
* libraries
* lwjgl
* mods
* versions

Copy/Move them to the same relative path in the new .app

**Comment by peterix** [comment]
I realized that I am stupid and completely forgot that 10.7 build stopped working when we moved to the current build infrastructure. I should have documented this. Instead, the builds now target 10.9.

Look and see for yourself:
http://ci.multimc.org/builders/osx64/builds/694/steps/configure/logs/stdio

`
-DCMAKE_OSX_DEPLOYMENT_TARGET=10.9
`

I'll have to set up a new builder with 10.7 SDK and the 10.7 SDK. I do have the license and hardware for it now, all it will take is installation.

**Comment by alyandon** [comment]
Thanks for taking the time to fix this.  My son is on an older education model iMac that can't be upgraded past 10.7 (no support for 64-bit efi) and I have all his Minecraft instances set up through MultiMC.

**Comment by peterix** [comment]
So, you need the previous versions for now. Do not update!

You can navigate into the .app with cmd-click or right click and selecting the appropriate option if you already did.

**Comment by alyandon** [comment]
Unfortunately, none of those older versions appear to work.  I download and extract the MultiMC application and to run it causes the icon to show up on the dock and bounce for a while until it stops.  Clicking on the icon in the dock causes it to immediate go away.  No crash dialog or anything.

**Comment by peterix** [comment]
Right. Why didn't anyone find this earlier? Why didn't I?

:-/

The binary files inside are not marked as executable. That's the issue. You can easily fix that on your end from a terminal:
```
chmod +x MultiMC.app/Contents/MacOS/updater
chmod +x MultiMC.app/Contents/MacOS/MultiMC
```
Assuming you are in the folder with the application.

I'll repackage those versions again.

**Comment by peterix** [comment]
Alright. Hopefully this will work better :)[mmc-stable-osx64-0.4.7-553.tar.gz](https://files.zenhub.io/56c1248ef7471cd9688f42dd)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by alyandon** [comment]
Alright, downloaded and extracts MultiMC.  Ran it once to let it initialize itself and then copied over the instances resource from the non-functional install that was upgraded.  However, although the instances show up and they appear to have all the correct data - I'm confronted with a "Too Soon!  Let the LWJGL list load :)" error when I try to start them.

So - yay progress?

**Comment by alyandon** [comment]
Copying the lwjgl library folder from the broken MultiMC appears to have fixed the problem.  Is that a resource that is supposed to get downloaded automatically or is the fact the folder is missing a problem?

**Comment by peterix** [comment]
@alyandon I assume it was broken because sourceforge was down? I should really get rid of that dependency.

**Comment by peterix** [comment]
The latest develop build should be fine again!

Please grab it here and test it separately from your real install. If that goes well, this could be definitively fixed this weekend.

**Comment by peterix** [comment]
http://files.multimc.org/downloads/mmc-develop-osx64.tar.gz

**Comment by Builderb0y** [comment]
It works! :D

**Comment by alyandon** [comment]
@peterix well either get rid of the lwjgl dependency or have a less vague error message when it can't be fetched  :-D

**Comment by TomeWyrm** [comment]
Um... I'm getting the "Instance update failed because: Too soon! Let the LWJGL list load :)." message as well.

I tried to import the FTB Retro pack into MultiMC via the FTB Launcher integration. It detects fine, but when I launch, I get this error... do I need a specific lwjgl for this 1.2.5 pack?

**Comment by TomeWyrm** [comment]
This is on Windows 7 with Java 1.8.0.101-b13 (64 bit server)

**Comment by peterix** [comment]
@TomeWyrm that has nothing to do with OSX 10.7, please open a separate issue.

**Comment by peterix** [comment]
Assuming this is no longer relevant.
