### ISSUE TITLE
MultiMc Error code 1

### ISSUE THREAD

**Issue by Nameless121** [MultiMC/MultiMC5#1496]
I have pasted the log here.
https://paste.ee/p/TcgZM

**Comment by whitephoenix0** [comment]
This is not a MultiMc issue. Please don't ask questions here about your modpack. Anyways, the issue appears to be caused by magical crops.

Try redownloading magical crops and make sure you're using the right version. My main concern is that the name of the magical crops jar file should be "magicalcrops-4.0.0_PUBLIC_BETA_3.jar" or similar, which leads me to believe you've tried to download the mod from one of those scummy mod-stealing websites like 9minecraft. Try this one for 1.7.10: http://mods.curse.com/mc-mods/minecraft/228834-magical-crops/2236937

**Comment by Mpsmall** [comment]
Hello, I switched from Windows 7 64-bit to Windows 10 64-bit and I am receiving a "Error code 1". I apologize if it's due to a mod or something third-party but nothing was changed from the previous computer and I just need a point in the right direction if possible, thank you!

I have pasted the log here:
https://paste.ee/p/CsYMv#

**Comment by peterix** [comment]
@Mpsmall check out https://github.com/LWJGL/lwjgl/issues/119 and https://github.com/MultiMC/MultiMC5/issues/1276

**Comment by Mpsmall** [comment]
Thanks!! it ended up being my up to date Java, I had to downgrade to Java SE Runtime Environment 7u79 

Got download from here:
http://www.oracle.com/technetwork/java/javase/downloads/jre7-downloads-1880261.html
