### ISSUE TITLE
Infinity doesnt launch

### ISSUE THREAD

**Issue by mhmd04** [MultiMC/MultiMC5#1497]
So 
System Information
i7 8GB ram
MultiMC version:
0.4.10-733
Operating System:
Windows 10
Summary of the issue or suggestion:
someone gave me their FTB infinty folder and when i launched it it doesnt open

What should happen:
It shouldve opened :/

Steps to reproduce the issue (Add more if needed):

Suspected cause:
---
I have no clue
Logs/Screenshots:
---
http://paste.ee/p/P5dln
Additional Info:

My internet sucks so i got someones Infinity folder and it didnt work in FTB launcher so i tried This and this is what happened

**Comment by JamesTheCoder** [comment]
By the look of things - it seems that the Scala libraries did not download - probably because you did not install the modpack conventionally. I may be entirely wrong, but just to check, do you have a folder called 'scala-lang' in '/path/to/MultiMC/libraries/org'? In terms of fixing this, your best bet is to install the modpack normally overnight or something. Bear in mind you should probably take what I'm saying with a pinch of salt, as I'm new at MultiMC development.

**Comment by jikuja** [comment]
Discussed and fixed in irc. Should be closed.
