### ISSUE TITLE
Is there some reason to avoid LWJGL 2.9.3?

### ISSUE THREAD

**Issue by Vekseid** [MultiMC/MultiMC5#1507]
Having to manually update is a bit mildly annoying.

**Comment by peterix** [comment]
Mostly Mojang being terribly inconsistent about LWJGL.

They have some custom builds up, none of which are actually available on all operating systems.

So I just decided to use a consistent version everywhere.

Is there a reason for updating it?

**Comment by peterix** [comment]
Without repackaging and rehosting LWJGL, I can get the versions from Mojang. It will need some extra work and hosting the separated version files though.

These are provided by Mojang:

* 2.9.0
* 2.9.1
* 2.9.1-nightly-20130708-debug3
* 2.9.1-nightly-20131017
* 2.9.1-nightly-20131120"
* 2.9.2-nightly-20140822
* 2.9.4-nightly-20150209

Some of them only on OSX, some of them only on Windows and Linux. 2.9.1 is everywhere.

**Comment by peterix** [comment]
Or I could make my own build of LWJGL. Or repackage the builds from sourceforge.

**Comment by Vekseid** [comment]
I just grabbed the 2.9.3 from sourceforge.

I wasn't aware that Mojang was doing its own thing with it, though. I thought the official launcher only used 2.9.3 on Windows. At least it was for awhile.

I'm not sure if there's any particular reason to upgrade, except for some odd bugs. I was trying to figure out a crash and updated manually. It didn't fix the problem, so I opted not to report anything until 1.9 here.

**Comment by peterix** [comment]
Well. I'm refactoring code related to version files and will then continue with replacing the existing version files and their lists with a unified format.

I'm not going to mess with the existing solution in any significant way, because it will be replaced entirely.

1. Repackaging upstream builds would make sense - repackaging because they don't exactly fit into how the mojang version files work.

2. Making a custom build would work too. I forked LWJGL at some point and added some minor AMD switchable graphics improvement - https://github.com/MultiMC/lwjgl
Realistically, it should just be merged to upstream though...

3. The easiest would be to expose all the Mojang versions. I should be able to do that with just version files and adding the ability to filter versions by rules.

I'll probably start with **3.** and decide what to do after that later.

**Comment by peterix** [comment]
Alright. Idea added to workflowy: https://workflowy.com/s/2EyDMcp7CU

Ideas -> Version lists -> LWJGL

**Comment by peterix** [comment]
Works in develop now.
