### ISSUE TITLE
feature request: offline / no account / personal server mode

### ISSUE THREAD

**Issue by meoso** [MultiMC/MultiMC5#1512]
offline / no account / personal server mode

requesting a way to bypass real accounts to be able to play personal servers.

**Comment by QuImUfu** [comment]
Do you want to play illegally without an account or do you want to play offline/with different name (having a valid account)?

If you just want to play offline/with different name just click on play offline on the right side after you have selected your instance. (MultiMC will ask you to choose a offline name)
You need one valid account logged in once to be able to do so.

If you want to play without account, you could try to find a way to circumvent this, but i think MultiMC will never include such an "feature".

**Comment by TheDoctorsLife** [comment]
MultiMC

**Comment by peterix** [comment]
I honestly don't know.

We are getting these requests all the time.

Problem is, you can't separate running without an account for legitimate reasons from running without an account because of piracy.

So, unless Mojang changes the things they allow, I'm not not willing to change anything about this.

You can run 'personal' servers while using a Mojang accoutn just fine.

**Comment by happysmash27** [comment]
You could just fork it or add a patch, seeing as this is under LGPL. Mojang can restrict downloads of the jar, but I'm pretty sure they can't restrict a launcher, since it is in no way their intellectual property. Please note that I am not encouraging piracy. It is quite harmful if someone who would buy something otherwise pirates it, even though Minecraft is now owned by Microsoft, a company which has too much money anyway /:

**Comment by cgarz** [comment]
This is one such example https://github.com/Ponywka/MultiMC5-with-offline

**Comment by Zetabite** [comment]
MultiMC already has an offline mode, if you have an account enabled in it and have downloaded the needed files. MultiMC wont support using minecraft without any minecraft account.

**Comment by Zetabite** [comment]
btw, thank you for reporting that repo, it will be taken down soon

**Comment by cgarz** [comment]
All bark, no bite 😛. Thankfully the issue continues to be resolved with a fork.

**Comment by peterix** [comment]
Yeah, whataver. It's not going to be supported here and anyone wanting this can go to hell.
