### ISSUE TITLE
adapt and include apparmor profiles

### ISSUE THREAD

**Issue by chadmiller** [MultiMC/MultiMC5#1519]
A project at
https://github.com/chadmiller/minecraft-linux-support
aims to add Apparmor profiles for Linux users. If the server or client is malicious or somehow compromised, apparmor will limit the systems that can be affected. Your launcher can be the new entry point for those profiles, and the server and client will only be able to read, write, execute, and transmit only as the profiles allow.

I'm the author of that project. I hereby assign copyright, or place in whatever intellectual-property domain you require, to include the apparmor files at https://github.com/chadmiller/minecraft-linux-support .

**Comment by peterix** [comment]
Interesting... However, how should this work? Some interesting and unusual challenges are involved.

MultiMC is not really tied to a fixed location - it is a portable application - and generally isn't even installed. There is no way for it to put apparmor profiles on the system.

The java version is left to the user and can be anywhere - it's not fixed like those profiles assume. You can download java from Oracle directly and use that. You can include java with it on an external drive. The thing can run from a network share - and some people actually do this.

As for Minecraft itself - the profiles seem fine for vanilla Minecraft. The problem is, modded minecraft is wild and chaotic in comparison. It's almost impossible to capture a minimal set of privileges it needs, because there's always something that would break. Modded minecraft generally means random code downloads more random code. It's extremely messy. And if you break it with security rules, it's broken and doesn't work.

Is there some way to start a process with a generated profile? If not, this would likely be limited only to the debian/ubuntu package - it's just a downloader that grabs the actual application - and is there because Unity is unable to deal with applications that do not have `.desktop` files.

**Comment by peterix** [comment]
I am not going to do this.
