### ISSUE TITLE
Error -1

### ISSUE THREAD

**Issue by luniayt** [MultiMC/MultiMC5#1615]
## System Information

MultiMC version: 0.4.11-751 on win32

Operating System: Windows 10

**Comment by QuImUfu** [comment]
And another likely "win 10 + Intel driver + java version>8u59" problem.
A Workaround is changing any of the things:
 - ***Downgrade java to 8u59***
 - Change OS to e.g. Linux
 - Buy a graphic card

this issue is explained in greater detail in #1606. 
If you are not using a Intel GPU it is very likely some sort of driver problem.
