### ISSUE TITLE
Thermal Expansion conflict

### ISSUE THREAD

**Issue by REUSSofficial** [MultiMC/MultiMC5#1623]
Hello github~
I decided to add the thermal expansion(dynamics & foundation too) mod in my MultiMC instance. And my minecraft started to crash every startup. I think it's a cross-mod conflict or version conflict. Do u know wat is this?
Lоg: http://paste.ee/p/rH5Wd

**Comment by QuImUfu** [comment]
1. Update MultiMC, your version is **very** outdated
2. Update your Mods. Some of them are outdated, too.

**Comment by REUSSofficial** [comment]
Soooo, will that rly help me?

**Comment by 02JanDal** [comment]
Since stuff changed; please post a new log.

**Comment by REUSSofficial** [comment]
New log: http://paste.ee/p/EurDo

**Comment by peterix** [comment]
I'm not aware of any version named '5 0.17'... so that's strange.

Please also post the following log file:
C:\Users\MrEU\Desktop\MultiMC\MultiMC\instances\THa & RPG\minecraft\hs_err_pid6344.log

**Comment by REUSSofficial** [comment]
log: http://paste.ee/p/jA3j2

**Comment by QuImUfu** [comment]
Does minecraft without mods work?
You could try to (re)install [OpenAL](https://www.openal.org/downloads/oalinst.zip), i do not know if this will work, but i have no idea what else you could do. :)
If this does not work you could sent me you instance for more testing.

**Comment by QuImUfu** [comment]
if you use some cracked MMC Version, i want to inform you that this is illegal:
1. because it is a cracked launcher
2. becouse it is a modified version of MultiMC without making clear that it is NOT MultiMC himself

if you really want to play the game without paying for it, you should (IMHO) just use the official MMC version and let it use some fake (non existant) proxy to stop MMC from testing you account and create a fake accounts.json e.g.:
```json
{
    "accounts": [
        {
            "accessToken": "00deadbeef00deadbeef00deadbeef00",
            "activeProfile": "00deadbeef00deadbeef00deadbeef00",
            "clientToken": "00deadbeef00deadbeef00deadbeef00",
            "profiles": [
                {
                    "id": "00deadbeef00deadbeef00deadbeef00",
                    "legacy": false,
                    "name": "whatever-nick-you-want"
                }
            ],
            "user": {
                "id": "00deadbeef00deadbeef00deadbeef00"
            },
            "username": "whoever@wherever.net"
        }
    ],
    "activeAccount": "whoever@wherever.net",
    "formatVersion": 2
}
```
After that you should be able to to chose you username everytime you start the game. This is still illegal but at least you will not have to use some outdated and maybe even dangerous version.
