### ISSUE TITLE
cant add account i get the Authentication operation failed due to a network error: Unable to init SSL Context: (99) error

### ISSUE THREAD

**Issue by itehmichael** [MultiMC/MultiMC5#1625]
## System Information

MultiMC version: 0.4.11-751

Operating System: Windows 10
## What should happen:

i log in in all places
## Steps to reproduce the issue (Add more if needed):
1. try to log into multi mc after logging off server with custom pack
2. cant so i deleted the instance and the account of MultiMC and couldnt re add

3.
## Suspected cause:

account compromise? i really have no idea
## Logs/Screenshots:

https://gyazo.com/ec473802df361dad691a5a188dd45109

no log

**Comment by KingDGrizzle** [comment]
In worst case, your firewall might be blocking you..

And why haven't you migrated yet? Having the old style accounts makes your account easier to crack, and use.

Recommended things to do: Migrate your account, and try letting multimc through your firewall.. Ask me if you need steps to let MultiMC through

**Comment by shelbykauth** [comment]
Hi, I need the steps to let MultiMC through!  I can't find instructions anywhere, and I can't find Minecraft in the list of programs on McAfee (in part because I can see like three at a time and they're not sorted in any obvious manner).  I have McAfee LiveSafe and Windows Defender Firewalls.  When I disable McAfee Firewall completely, my friend can connect to my LAN enabled game with Hamachi.  I presume she can also connect through the MineThrough mod if I disable the firewall, because we got the exact same error, but did not think to disable the firewall until after we were using Hamachi.  I think it's McAfee and not Windows that's blocking it.
If I can't get this working, I think I'll just disable McAfee altogether and rely on Windows Defender.  I'm not sure if that's the best solution or not, though.  So steps to letting just MultiMC through would be great.

**Comment by Loetkolben** [comment]
@shelbykauth 
Do you actually get the same error message? Or do you just want support for adding a firewall exception? In the second case, try googling `mcafee firewall whitelist application` and try to find something that works. Be aware that you will have to whitelist the MultiMC application / binary itself (on Windows its `MultiMC.exe`) for the MultiMC launcher (if you actually get the same error message and it can be fixed by adding a firewall exception - I'm not sure that is the case) and Java for Minecraft, I cant provice any additional help with that since I dont use McAfee.

**Comment by shelbykauth** [comment]
It was a different error.  Problems with other computers connecting to my
server (client/server combined).  Googling with similar search terms is how
I got to this issue thread.  Others were with old versions of mcafee
apparently.  The previous poster offered help with that, though I suppose
it is a bit of a dead thread.  It's okay.  I ended up having to switch
computers anyways due to other problems.  I apologize for dirtying this
thread.

**Comment by Loetkolben** [comment]
Oh, I see. Glad you solved it.
/close for real now ;)

**Comment by sircorneilous** [comment]
@vladfrangu  actually I've recently migrated my Mojang account to my Microsoft account and it had the same error be for i migrated my account there were no issues when I signed in

**Comment by sircorneilous** [comment]
@vladfrangu actually I've recently have migrated my account and i have the same error message and it did not have any problems before i migrated

**Comment by sircorneilous** [comment]
also if this issue accured  right after you migrated than this is the solution for you if not then im sorry your on your own

**Comment by r58Playz** [comment]
> I know a solution remove the MULTIMC folder and replace it with the developer edition of multimc and extract the file where MULTIMC was located. and if you have any instances that you don't want deleted I recommend copying and pasting every instance you want saved in any folder you want to put it in

Or you can just update to the developer version:
![image](https://user-images.githubusercontent.com/45221816/131922030-130d4749-3a05-4f62-a009-dea8f068838e.png)
