### ISSUE TITLE
A problem happened when I used  CMAKE

### ISSUE THREAD

**Issue by hxp1999** [MultiMC/MultiMC5#1626]
I'm sorry.My English is poor. 
There is the warning.

F:\Development\Launcher\MultiMC5-develop\MultiMC5-develop\CMakeLists.txt:92: error: The source directory F:/Development/Launcher/MultiMC5-develop/MultiMC5-develop/libraries/libnbtplusplus does not contain a CMakeLists.txt file.

And I want to know how to install zlib ..........orz

**Comment by peterix** [comment]
You don't have the complete source code. So:
```
git submodule init
git submodule update
```

**Comment by hxp1999** [comment]
Thanks, I'll try it.
But can you tell me hao tu install  ZLIB

**Comment by hxp1999** [comment]
It's done.Thanks a lot.
But I still don't know hao to install zlib ..........................orz

**Comment by jikuja** [comment]
https://github.com/MultiMC/MultiMC5/blob/develop/BUILD.md ?

**Comment by hxp1999** [comment]
I can't find it.

**Comment by therealmikz** [comment]
Hey, I know that this issue is solved, but about that zlib thing - BUILD.md mentions installation of linux zlib development package, and it should be found by a compiler when it's installed, but there's no instruction regarding Windows installation (there's only link where to download it). Therefore I can't compile MultiMC on windows machine, neither using the Qt creator, nor from command line.
I've managed to solve it using CMake arguments pointing to zlib (-DZLIB_INCLUDE_DIR and -DZLIB_LIBRARY) but I'm still having problems with this solution. Could anyone point me the right direction?
