### ISSUE TITLE
How do I change my skin??

### ISSUE THREAD

**Issue by AwesomeDonut67** [MultiMC/MultiMC5#1631]
Guys, how do I change my skin in Multimc? I just get left with a steve skin and a alex skin everytime I launch the game. Please help!

**Comment by QuImUfu** [comment]
On https://minecraft.net/profile.
If you already set up a skin over this side, it should work with MultiMC.
If you already set up a skin over this side, and it doesn't work, try removing the {MMCDir}/assets/skins folder. This will force Minecraft to download all skins again.

**Comment by peterix** [comment]
Or there's a thing added for it in the current development version of MultiMC (Upload button in account settings):
![image](https://cloud.githubusercontent.com/assets/203326/17201773/e19cb79c-5491-11e6-8b35-a6cdf218a8de.png)

**Comment by LustyFarmer** [comment]
I tried to upload a skin in MultiMC, to change my skin in-game and profile in the loader for MultiMC, but it did not work at all. My profile image is the same as before despite the new skin I uploaded successfully

**Comment by theTisch21** [comment]
@LustyFarmer after uploading your skin, it can take MultiMC a while to update your profile image. Your skin will update in game immediately in online mode, but if it fails to change in offline mode, do what QuImUfu suggested to re-download skins. You can also delete {MMCDir}/accounts/skins as well as {MMCDir}/assets/skins to refresh all skins and your profile photo, but even doing that might not refresh it. It has sometimes taken up to a few days for it to refresh.

**Comment by OracleOfOranges** [comment]
> @LustyFarmer after uploading your skin, it can take MultiMC a while to update your profile image. Your skin will update in game immediately in online mode, but if it fails to change in offline mode, do what QuImUfu suggested to re-download skins. You can also delete {MMCDir}/accounts/skins as well as {MMCDir}/assets/skins to refresh all skins and your profile photo, but even doing that might not refresh it. It has sometimes taken up to ~a few days~ 2-3 hours for it to refresh.
> 
> Edit: Updated my skin today. Picture had refreshed when I checked it 3 hours later. It had probably updated before then, but that is when I noticed it.

I try that myself, but it just says "Failed to login!" 
Is it because of laptop security? If so, I can try to bypass it using a USB.

**Comment by theTisch21** [comment]
@OracleOfOranges 
Try logging out of your account and logging back in. To do that, go to settings, Accounts, click your account, then click "Remove". Once you do that, log back in using either the "Add Mojang" or "Add Microsoft" button depending on the type of account you have. Once you've done that, you should be able to update your skin.

**Comment by su2u4-1** [comment]
I am playing in normal mode and the skin can be displayed normally.
But when I lose the Internet connection and re-enter the save world, my skin will become Mojang's default
Later, I discovered that as long as I enter the world without the Internet, my skin will become the default. Even if Wu is not in offline mode, it will be useless even if the Internet connection comes back later. I have to restart the game. Can
Does this mean my skin will be re-downloaded every time I restart the game?
Otherwise, why would my skin change back to the default every time? (When the network is disconnected)
(Since my English is not good, the above text was translated using Google Translate. Please forgive me if the sentences are not fluent.)
