### ISSUE TITLE
Add Curse Modpack support

### ISSUE THREAD

**Issue by Firestar311** [MultiMC/MultiMC5#1649]
Add support for the Curse Minecraft Launcher's modpacks muck like the FTB Launcher modpack integration

**Comment by peterix** [comment]
Not going to happen.

**Comment by Firestar311** [comment]
Why?

**Comment by peterix** [comment]
It is easy enough to create an instance and copy over what needs to be copied over.

Like this for example:
https://www.youtube.com/watch?v=Akwh8F2bIq4

I also do not want to emulate other launcher's logic. Every single one is slightly different. What made FTB viable was that it started with an old MultiMC-based design.But it also made me keep certain things around for a lot longer than they should have been around.

Curse is too different. What *would* be viable is some sort of one-shot import function. Because once it's in MultiMC's format, I don't have to worry about the other launcher changing.

What would be ideal is directly connecting to the curse platform... but I talked to the curse people and their conditions for that happening are simply not acceptable. To put it plainly: I'm not interested in contributing to a private business/corporation for free while they dictate what OS I can do it on.

**Comment by peterix** [comment]
So, definitely not going to do this 'tracking' thing again with other launchers. Once the FTB launcher is obsolete, I will remove support for it, along with some other things (legacy instances, old LWJGL version list, possibly a few thousand lines of code).

Support for the curse platform is out of the question. It's still better than FTB where the FTB people just said 'NO', but nowhere near acceptable from my point of view.

Import... maybe. Given how simple it is already, I don't see it as a priority though.

**Comment by StarkRG** [comment]
If it helps increase the priority, I'm on linux and there's no easy way to download a curse modpack and launch it. The only way currently is to run a script (there's a python one, a java one, and another one I don't remember), then create an instance and copy the mods over. Having the functionality built into MultiMC would make things a lot easier. If it could also handle modpack updates that'd put it over and above the current download methods for linux.

**Comment by ExpertsGaming** [comment]
Where to get links to modpacks?

**Comment by joepie91** [comment]
I'm curious, do you have any documentation on Curse's stance on this? I've been getting increasingly irritated with Curse over a number of other things, and I'd like to know what kind of demands they make for integration. I pretty strongly get the impression that the community shouldn't trust them in the slightest, by now.

**Comment by peterix** [comment]
The develop version actually has a way to import curse modpacks now.

It's not connecting directly to curse APIs and it's not tracking... Basically, some awesome people cracked open the curse API and wrote a caching proxy that doesn't require me to implement any of the curse insanity.

See: https://cursemeta.dries007.net/
