### ISSUE TITLE
Default Settings on each new Instance

### ISSUE THREAD

**Issue by leonekmi** [MultiMC/MultiMC5#1667]
Hi,

I have this idea because of this : i have an AZERTY keyboard and i must for each new instance, re-set my AZERTY controls. A setting to set the default settings "Brightness" or "Render Distance" for each new Instance will be cool !

Sincerly,

@leonekmi

**Comment by peterix** [comment]
Hello!
That's a good idea... and like all good ideas, someone had it first :)
See: https://workflowy.com/s/2EyDMcp7CU#/f7fc9005845f

Anyway, until that's done (which may take quite a while), you can use this:
1. Create an instance... call it 'template'
2. Set it up with your personal settings
3. Use this instance as a template. Instead of clicking 'new instance' every time, just copy the template and rename it.

**Comment by peterix** [comment]
Added to workflowy:
https://workflowy.com/s/2EyDMcp7CU#/f7fc9005845f
