### ISSUE TITLE
Request - Automatically Send Crash and Full Log to Github

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [MultiMC/MultiMC5#1687]
I would like to be able to integrate my github into my multicraft instance so even if users forget I will still get crash logs. This would save me a lot of time testing.

**Comment by peterix** [comment]
Ok. I'll keep it in mind.

But just how would it be uploading? To do that, MultiMC would have to have a way to log in on github as *something*. That's quite a bit of work :)

Added to workflowy:
https://workflowy.com/s/2EyDMcp7CU#/9377e3bf53dd

**Comment by P3rf3ctXZer0** [comment]
Okay new thought I noticed pastee is free what if instead of github it was sent via email from pastee?

**Comment by peterix** [comment]
The problem of paste.ee is that it doesn't have a way to list all the pastes for a user.

**Comment by P3rf3ctXZer0** [comment]
Hmmm ... I will have to brainstorm on that. How does blizzard or riot do it?

**Comment by peterix** [comment]
They probably have their own servers and own software.

**Comment by P3rf3ctXZer0** [comment]
Hmmm I will get back to you on this.

**Comment by peterix** [comment]
Well, I have an oauth implementation somewhere, I think.

But this thing is kinda far down the line.

It needs either a new hardcoded launch step (easy, dirty, hard to get rid of), or scriptable/declarative launch steps (harder, but the right thing to do).
It elso needs pack support, because I really don't want to cram something like this into the base instances.

I'll go ask the paste.ee maintainer about having a list of uploaded pastes. That would make things easy.
