### ISSUE TITLE
Process Exited with code 1

### ISSUE THREAD

**Issue by HoppinAround** [MultiMC/MultiMC5#1691]
Game Exits with code 1

I just installed PortalGun Mod 1.7.10-Beta (with IChunUtil 2.2
and i just got an Error my Game wont start and I have a lot of errors In it please Help me!
I am using the internal Java64 version of MC (the runtimefolder on your desktop)
and i never had Problems with mods or anything now this Happens i dont know why Please help!
## Console

http://paste.ee/p/tNS3j

**Comment by HoppinAround** [comment]
Halp meh plis

**Comment by QuImUfu** [comment]
There should no mod be in coremods anymore since ?1.6.x? i think. Put them all into the mods folder.  
Make sure minecaft (java) can access the internet because CodeChickenLib gets downloaded automatically (i think). You can also download it from http://files.minecraftforge.net/CodeChickenLib/ .

**Comment by HoppinAround** [comment]
no its not because of coremods its because of the PortalGun Mod if i remove it it works otherwise it crashes but i want 2 play with it!

**Comment by QuImUfu** [comment]
Ohh, i just got you true problem :) You use the deobf version of iChunUtil. You have to use the normal version to make the PortalGun mod work.  
And you should maybe update you mods.

You are right, the coremod thing does not matter, because forge doesn't care, it just loads them from both folders in the same way.
