### ISSUE TITLE
[Request] Regex filtering of console, and other logs.

### ISSUE THREAD

**Issue by DrZed** [MultiMC/MultiMC5#1714]
If you don't mind, would you add this to a low priority request, to add regex filtering for the console, not only for searching but also "hide lines matching" for the console, there is a ton of spam I see quite often in the console I'd like to filter out with regex. And even more so a custom capability to replace text displayed matching with "custom text"

**Comment by peterix** [comment]
I already tried to do something like this and ran into some really bad performance issues. Mainly because the log can get quite big.

To be able to scroll around in a 100k line text file, you need to know the height of all lines - and with line wrapping, the lines have varying height.
If I do not use an optimized view, the performance goes to hell. However, the text-optimized view does not allow for filtering.
