### ISSUE TITLE
1.10.2 Crash When Attacking Creepers

### ISSUE THREAD

**Issue by Chelmuth1** [MultiMC/MultiMC5#1715]
System Information
-----------------------------
Intel i3-6100 3.7GHz
8 GB RAM
AMD Radeon R9 380 Videocard

MultiMC version:
0.4.11-751
Operating System:
Windows 7 Professional 64Bit SP1
Java 8_111 64bit
LWGJGL 2.9.1

Summary of the issue or suggestion:
----------------------------------------------
Minecraft 1.10.2 Client sometimes freezes when rapidly attacking creepers. This happens very inconsistently, but seems to happen most when jump-attacking. Minecraft freezes as in the linked screenshot. The background music continues, as does the last hiss from the creeper. At this point I have to force-kill java. MultiMC's log window reads as normal, with only one line being any kind of error:
"Process crashed with exitcode -805306369."
Restarting the game allows me to reload the world just fine, albeit from the previous savepoint.

I have not been able to re-create this in the vanilla MC launcher.

What should happen:
------------------------------
Nothing; game should continue normally.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Load a blank 1.10.2 Instance; launch it.

2.  Create a world, and then spawn creepers. Jump-attack them faster than the swing cooldown. It does not happen every time, but I haven't had to try more than 6 times in any given session to provoke a freeze.

Suspected cause:
---------------------------
I have no idea.

Logs/Screenshots:
----------------------------
http://paste.ee/p/Em1M9
http://imgur.com/4SqvgzC

**Comment by TheBlueTroll** [comment]
can you reproduce it on the vanilla launcher?

**Comment by Chelmuth1** [comment]
I have not been able to re-create this in the vanilla MC launcher.

**Comment by brodycas3** [comment]
And I assume you have no mods installed?

**Comment by jikuja** [comment]
Can you share every log you found? From both mmc and vanilla launcher.

Do you know how to share thread dump?

**Comment by Chelmuth1** [comment]
Yes, no mods. Vanilla 1.10.2 only.
Here's a log from the immediate after-crash window in MultiMC
http://paste.ee/p/GaGOc
The latest.log from that instance
[latest.txt](https://github.com/MultiMC/MultiMC5/files/595579/latest.txt)

Vanilla minecraft does not crash or produce any logs when doing this.
I now believe this is a java version issue; downgrading the java version used by MultiMC (8u111) to match the vanilla launcher (version 8u25) stops the crash.

I've found lots of how to threaddump through google, but can't find a download for the tool they all recommend: jstack.

**Comment by brodycas3** [comment]
I found this,
https://helpx.adobe.com/experience-manager/kb/TakeThreadDump.html

**Comment by TheBlueTroll** [comment]
Jstack is part of the JDK (Java Dev Kit) and so you would have to manually download the jdk version of java, and make sure that multimc is set to use the jdk version for it.
link to jdk download: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

another thing is that usually the path variable isnt set when you install the jdk ( it never is for me) so you may have to open a terminal at the place where the the jdk is installed (shift+ rightclick, and "pick open terminal here" on the jdk's bin folder. For me the jdk is installed at "C:\Program Files\Java\jdk1.8.0_102\bin" so open your terminal at the bin folder.
you should now have a command terminal that says "**C:\Program Files\Java\jdk1.8.0_102\bin>**"
at this point.
now you want to run **jps -l**
which should print 2 lines (assuming you only have minecraft running):
14120 sun.tools.jps.Jps
17164 C:/Users/<insert username here>/Desktop/MultiMC/jars/NewLaunch.jar
the first line is the jps command, so ignore it, and the second one says multimc. which is the one we want.

now open my computer and goto c drive, and make a new folder and call it "threaddump"

now we want to take the pid at the start of the line (which we got from the previous command) and put it into "**jstack <pid> >> C:\threaddump\threaddump.txt**"
you should now have a text file in the c:\threaddump folder.
be sure to only run jstack when minecraft is actually frozen, not when its running normally, because it wont show any issue. good luck.
