### ISSUE TITLE
Can you provide a windows x64 build

### ISSUE THREAD

**Issue by ppoozl** [MultiMC/MultiMC5#1716]
I'd like to use a 64bit MultiMC. OS X has a 64bit version Linux has a 64bit version.So I wonder if you can provide a 64bit version on Windows.

**Comment by peterix** [comment]
I could do that, but I don't see the reason for it. The 32bit version runs just fine and MultiMC definitely doesn't need that much memory - or a 64bit instruction set for that matter.

The only things affected are Windows Server system... if you are paying for Windows Server, I doubt you are running Minecraft on it. And you can still install 32bit support.

So, is there anything new in this area? Is Microsoft dropping 32bit?

**Comment by ppoozl** [comment]
OK. I have successfully build a x64 build on my own machine. Anyway thanks.

**Comment by wilsontulus** [comment]
To be honest, relying on a compatibility layer in order to save costs is a very bad idea and progressively becoming an issue for the future later on. Almost all modern OSes, be it Linux, macOS, iOS, and Android 14 have removed their 32-bit support, or in Linux's case, make it entirely optional and not usable by default. At this point Windows is the only "modern" OS when 32-bit support are kept. While almost all my rigs are running a Linux distro right now, recently I modded all other Windows installations to have their 32-bit support removed. It was kinda painful for every app built with 32-bit installers or is 32-bit only (like Discord and even MultiMC), but it works.

Forcing people to compile from source just to build the same app for a more supported architecture isn't going to resolve it either; many people didn't have a powerful enough CPU, and a spacious enough drive.

MultiMC must provide x64 and ARM64 Windows builds for the sake of future later on.

**Comment by wilsontulus** [comment]
> OK. I have successfully build a x64 build on my own machine. Anyway thanks.

By the way, in case
I'm actually trying to build MultiMC Windows x64 to test if it can run on Windows x64 without WOW64, and also ReactOS amd64 (for sake of testing). Tried everything including downloading Qt 5.6 MinGW-w64 and the MinGW-w64 build tools, but it failed here:
```
[ 20%] Building CXX object libraries/LocalPeer/CMakeFiles/LocalPeer.dir/src/LocalPeer.cpp.obj
C:\Launcher\libraries\LocalPeer\src\LocalPeer.cpp: In member function 'bool LocalPeer::sendMessage(const QByteArray&, in
t)':
C:\Launcher\libraries\LocalPeer\src\LocalPeer.cpp:173:14: error: 'std::this_thread' has not been declared
         std::this_thread::sleep_for(std::chrono::milliseconds(250));
              ^
libraries\LocalPeer\CMakeFiles\LocalPeer.dir\build.make:62: recipe for target 'libraries/LocalPeer/CMakeFiles/LocalPeer.
dir/src/LocalPeer.cpp.obj' failed
mingw32-make[2]: *** [libraries/LocalPeer/CMakeFiles/LocalPeer.dir/src/LocalPeer.cpp.obj] Error 1
CMakeFiles\Makefile2:1203: recipe for target 'libraries/LocalPeer/CMakeFiles/LocalPeer.dir/all' failed
mingw32-make[1]: *** [libraries/LocalPeer/CMakeFiles/LocalPeer.dir/all] Error 2
makefile:139: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
```
(NOTE: the error above is solved by adding the necessary MinGW-w64 headers for threads from https://github.com/meganz/mingw-std-threads)
I think I solved the error by myself. For Qt 5.6 MinGW-w64 it's in https://wiki.qt.io/MinGW-64-bit but unfortunately it doesn't include the build tools.
Fortunately the build tools with MinGW 4.9.2 is also available at Sourceforge: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/4.9.2/threads-win32/seh/x86_64-4.9.2-release-win32-seh-rt_v3-rev1.7z/download
You will also need https://github.com/meganz/mingw-std-threads, download the headers to the include folder and replace the `#include <thread>` with `#include <mingw64.thread.h>` in every files that error with "std::this_thread", such as `LocalPeer.cpp` for example.
For ZLib, replace the zlib1.dll in the bin folder with an x64 version of zlib1.dll with size of 122 kB or higher.

**NOTE: This is if you want to still make MultiMC x64 run on Windows Vista, XP x64 Edition, and ReactOS. You can still build MultiMC with Qt 5.15, msys2 and clang64 if you don't care about testing / running multimc on these OSes.**

**Comment by ppoozl** [comment]
Now I am build this Launcher using msys2 clang64 env. Also I used my own build of Qt 5.15.9.

**Comment by wilsontulus** [comment]
> Also I used my own build of Qt 5.15.9.

It's already possible to build MultiMC that way already. That's if the target system is Windows 7 or higher though.
For testing on ReactOS or Windows Vista, Qt 5.6 is still a way to go.
