### ISSUE TITLE
Early load crash

### ISSUE THREAD

**Issue by jacfalcon0** [MultiMC/MultiMC5#1725]
MultiMC version:
0.4.11-751

Operating System:
Win 7

Summary of the issue or suggestion:
Crashing very shortly after trying to boot. I copied a modpack from the Curse launcher for AllTheMods and copy pasted the contents into MultiMC 5. I'm guessing it's something simple but I've tried a bunch of googling with no luck...

Logs/Screenshots:
http://paste.ee/p/euA2S

**Comment by TheBlueTroll** [comment]
try coping the updated AllTheMods Modpack. (a update was released yesterday) and make sure to use forge version 2151, and see how that goes.

**Comment by TheBlueTroll** [comment]
I've just copy-pasted the modpack "AllTheMods" into a new instance in MultiMC, being sure to install forge version 2151 by doing "edit instance" -> "install forge" and picking 2151.
After which i copied in the .minecraft into the minecraft folder inside the instance folder. and it appeared to work. 
I cannot actually run it very well due to its high ram usage, but it did make it to the menu without a crash, so i assume it works, so try repeating the steps i did.
make a new instance
install forge ("edit instance" -> "install forge" and picking 2151.) on the new instance
copy the minecraft files from the curse instance (C:\Users\TheBlueTroll\Documents\Curse\Minecraft\Instances\All the Mods) to your MultiMC instance folder (C:\Users\TheBlueTroll\Desktop\MultiMC\instances\AlltheMods\minecraft) my multimc folder is set to my desktop, yours probibly is not.
and be sure to adjust ram allowances for it, all the mods modpack recommends 4.5gb, and multimc defaults for me is 2.5. to change go to edit instance-> settings tab, click the memory and change max to something near 4500.
