### ISSUE TITLE
LOADED GAME BUT STAYS ON DOWLOADING TERRAIN SCREEN FOR 10 MINUTES AND THE LOADS AND FREEZES!

### ISSUE THREAD

**Issue by Dog3403** [MultiMC/MultiMC5#1746]
evrytime i open it it loads sais its done but when i look its stll on dowloading errain screen and just stays there any help???

**Comment by HillustratedMike36** [comment]
Can you be more descriptive with your issue? So many questions I have.

**Can you reproduce this with the vanilla launcher to make sure this only affects MultiMC?**
**What Minecraft version?** _Vanilla, Forge, or ModLoader?_
**What type of world are trying to load...?** _Did you try re-creating the world?_
**What version of MultiMC do you have?**
**Is there any specific settings with your instance (ex. Java) or are you using the global settings?**

There's much more I could ask you, but I suggest trying to test it more, starting with my first suggestion, because it may happen on the vanilla launcher.

I wish you luck.
