### ISSUE TITLE
Randomly stopped working. HELP!

### ISSUE THREAD

**Issue by Jak3y** [MultiMC/MultiMC5#1819]
I was just playing on the modpack I was always playing on and it just crashed and stopped opening. Please help.

Here is the log down below.

https://paste.ee/p/6AzpO#s=0

**Comment by QuImUfu** [comment]
Did you place some block when the crash happened? Or look at some block you havn't looked at before?
Sadly the log only tells me that some block is returning a invalid texture. and does not include what block.

**Comment by Jak3y** [comment]
I'm not sure what block I was looking at but I believe what you said is correct or it's possible that the server I am on has a corrupted chunk that I ended up on...

**Comment by QuImUfu** [comment]
The only thing i can think of you could do in this case is asking the server owner/admin to modify the save to move you to an other location, for example the spawn.

**Comment by Jak3y** [comment]
This is what it is saying now.
https://paste.ee/p/hbxMz

I've never seen a problem like this before...

**Comment by QuImUfu** [comment]
Sooo. The same thing is happening again. O.o 
Maybe a block in your inventory? have you maybe picked up something before this happened? 
If it is possibly caused by a block in you inventory, you could ask the server owner to backup and remove your whole inventory so you can try if the error still occurs. 
In case it works you could ask him to cheat you the most important items back.

**Comment by Jak3y** [comment]
I don't think something your inventory can cause this problem. Also I've been told that that's just not how it works. I've tried almost everything up to this point but nothing is working.

**Comment by QuImUfu** [comment]
According to this issue: 
MinecraftForge/MinecraftForge#1319 
The crash has something to do with a block returning an invalid texture. (i think the main forge coder/maintainer is a valid source of information)

And because teleporting didn't help, i concluded it has to be something about your player => deleting/resetting your inventory/player data should fix this.
After all, not all players are unable to get on the server? 

If you don't want to try this, it does not matter to me, i just said what i think is the most likely reason. Something else you could try (but i don't think it will help/change anything) is reinstalling the mod pack.

However, this is not a bug/problem with MultiMC but with the modpack you are using, so the most logical location to file a bug report would have been the support page for your modpack. (If there is one)

**Comment by Jak3y** [comment]
I've asked the owner of the server to reset my account asap. I really appreciate the advice you have been providing me!
