### ISSUE TITLE
Version urls outdated

### ISSUE THREAD

**Issue by clienthax** [MultiMC/MultiMC5#1828]
Seems multimc is still using, https://s3.amazonaws.com/Minecraft.Download/indexes/1.7.10.json

We should be reading this
https://launchermeta.mojang.com/mc/game/version_manifest.json

And using the urn from it like this.
https://launchermeta.mojang.com/mc/game/hash/version.json
https://launchermeta.mojang.com/mc/game/016674e6940d040efe6df3a459a4fe10faaa6a40/1.7.10.json

currently the amazon one seems to be down, but the launchermeta urls are still working fine

```
Instance update failed because: Failed to download the assets index:
Job 'Asset index for lowramz' failed to process:
https://s3.amazonaws.com/Minecraft.Download/indexes/1.7.10.json.
```

**Comment by kashike** [comment]
Dinnerbone has stated that the S3 urls won't always be around:
```
2016-03-31 17:33:25     Gjum    will the old s3 urls go away eventually?
2016-03-31 17:33:30     +Dinnerbone     At some point yes
2016-03-31 17:33:43     +Dinnerbone     Nothing official points to it, only 3rd party scripts/launchers that haven't been updated yet
```

`launchermeta.mojang.com` is served through cloudfront, aditionally.

**Comment by zjmonk** [comment]
Yeah, cannot start game right now. Is there any way to fix this temporally?

**Comment by uxhy** [comment]
Apparently, I can play 1.11 just fine, but whenever I try to start an instance of b1.7.3, it won't start.

**Comment by joserobjr** [comment]
I'm unable to launch my instances in online mode, I gets stuck on updating assets, I think this is being caused by this issue because I can't open the amazon link now, it seems to be down.

It says: ERR_CONNECTION_TIMED_OUT, the mojang url downloads the json file instantly.

**Comment by xFMz** [comment]
any clue when we will be able to play?

**Comment by burntcheese** [comment]
Is there a quick workaround/hotfix that we can use for now?

**Comment by peterix** [comment]
Switch to the develop version of MultiMC. It's in the settings.

**Comment by peterix** [comment]
I will have a real release ready in a bit.

**Comment by peterix** [comment]
Then:
![https://cdn.discordapp.com/attachments/134843027553255425/286229839994945536/unknown.png](https://cdn.discordapp.com/attachments/134843027553255425/286229839994945536/unknown.png)

**Comment by TSKimball** [comment]
Looks like that's not working on the dev release for Windows, unless it did not update properly.  I just updated per the above and tried to launch WLR and Regrowth, still no good.  What (very few) 1.10 packs (i.e. Cid's Modded Life) I have do launch.

-----=====-----

MultiMC version: 0.5.0-develop-947

Minecraft folder is:
Q:/Misc_Games/FTB/WanderlustReloaded/minecraft

Java path is:
C:/ProgramData/Oracle/Java/javapath/java.exe

Java is version 1.8.0_111, using 64-bit architecture.

Instance update failed because: Failed to download the assets index:
Job 'Asset index for Wanderlust Reloaded' failed to process:
https://s3.amazonaws.com/Minecraft.Download/indexes/1.7.10.json.

Clipboard copy at: 28 Feb 2017 15:30:33 -0500

**Comment by clienthax** [comment]
Works fine here on dev branch

**Comment by joserobjr** [comment]
I hadn't tried the dev branch but the amazon link is up again.

**Comment by peterix** [comment]
yay

**Comment by clienthax** [comment]
End of the day, we shouldn't be relying on deprecated urls ;)

**Comment by TSKimball** [comment]
My issue appears to be isolated to packs that are managed from the old Java FTB Launcher (aka FTB.jar).  It still references the S3 servers, and is unlikely to be updated since FTB's focus is now on Curse Voice's client.  If S3 is now back, then it can be considered closed on my end.

[A workaround was discussed on Discord, which works, but is not a MultiMC issue and so is outside the scope of this ticket.]  :)

**Comment by peterix** [comment]
Yeah... we don't use this stuff anymore. And never will again.
