### ISSUE TITLE
Snap package of MultiMC exists

### ISSUE THREAD

**Issue by casept** [MultiMC/MultiMC5#1832]
System Information
-----------------------------
MultiMC version: aafac3934b9887ced77c9f5b3d6be988af06dbf0

Operating System: Ubuntu 16.04

Summary of the issue or suggestion:
----------------------------------------------
I'm trying to build a [snappy](https://snapcraft.io) package for MultiMC. I've set the PATH and JAVA_HOME env vars, however multimc's java checker still cannot detect java. 

What should happen:
------------------------------
MultiMC should allow to set the path to java manually in corner cases like this one.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Install snapcraft `sudo apt install snapcraft`

2.Clone my repo `git clone https://github.com/casept/snap-multimc.git`

3.`cd snap-multimc.git`

4. `snapcraft snap`

5. `sudo snap install --dangerous multimc5-casept_master_amd64.snap`

6. `multimc-casept.multimc`

7. Observe how no java version is offered

Suspected cause:
---------------------------
The java checker likely doesn't deal very well with the odd path snappy installs package files to. I'd suggest simply adding a command line flag which allows to force a java location (thus bypassing the java checker entirely).

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

```
    0.001 D MultiMC 5, (c) 2013-2017 MultiMC Contributors
    0.002 D Version                    :  "0.5.0-custom"
    0.002 D Git commit                 :  "160b5033a79e6b5ee9f3e2a001b96c677f41ddcb"
    0.002 D Git refspec                :  "refs/heads/develop"
    0.002 D Work dir before adjustment :  "/snap/multimc5-casept/x7"
    0.002 D Work dir after adjustment  :  "/home/david/snap/multimc5-casept/x7/MultiMC"
    0.003 D Adjusted by                :  "Command line /home/david/snap/multimc5-casept/x7/MultiMC"
    0.003 D Binary path                :  "/snap/multimc5-casept/x7/bin"
    0.003 D Application root path      :  "/snap/multimc5-casept/x7"
    0.012 D Detected default console font: "DejaVu Sans Mono" , substitutions: ""
    0.014 D FTB Launcher paths: "/home/david/snap/multimc5-casept/x7/.ftblauncher" and "/home/david/snap/multimc5-casept/x7/.ftblauncher"
    0.014 D Attempting to read "/home/david/snap/multimc5-casept/x7/.ftblauncher/ftblaunch.cfg"
    0.015 W Couldn't open "/home/david/snap/multimc5-casept/x7/.ftblauncher/ftblaunch.cfg" : "No such file or directory"
    0.015 W This is perfectly normal if you don't have FTB installed
    0.017 D Your language is "en"
    0.018 D Started watching  "/home/david/snap/multimc5-casept/x7/MultiMC/icons"
    0.022 W ""
    0.022 D Loading theme "custom"
    0.023 D Loading builtin version list.
    0.024 W Blacklisted legacy version ignored:  "rd-160052"
    0.025 D Instance path              :  "instances"
    0.025 D Loading Instances...
    0.025 D Loading accounts...
    0.026 C "Failed to read the account list file (accounts.json)."
    0.026 D Detecting proxy settings...
    0.026 D Using no proxy is an option!
    0.027 D Downloading Translations Index...
    0.027 D "Translations Index"  started.
    0.043 D Linux Java detection incomplete - defaulting to "java"
    0.044 D Probing the following Java paths: 
    0.044 D   "java"
    0.044 D "Java detection"  started.
    0.044 D "Running java checker: java-jar /snap/multimc5-casept/x7/bin/jars/JavaCheck.jar"
    0.072 D XmbTextListToTextProperty result code -2
    0.077 D XmbTextListToTextProperty result code -2
    0.077 D XmbTextListToTextProperty result code -2
    0.086 D "Translations Index" succeeded.
    0.087 D Task succeeded
    0.087 D Got translations index!
    0.087 D Download cache hit  "http://files.multimc.org/translations/index"
    0.087 D Java checker has failed to start.
    0.088 D "Java detection" progress: 1 / 1
    0.088 D Found the following valid Java installations:
    0.088 D Task succeeded
```

Additional Info:
---------------------------

**Comment by casept** [comment]
For some reason it seems to work properly now. As I can't reproduce the reason for requesting this feature in the first place anymore I'm closing the issue.

**Comment by peterix** [comment]
So, I am actually looking at this. And it is because I do not want a snap package of MultiMC to exist.

**Comment by peterix** [comment]
1. You cracked it and are passing it off as the real deal:
https://gitlab.com/AtRest7/MultiMC5/commits/cracked

So, either:
* You will take this down.
* You will change the name of your fork so it cannot be recognized as MultiMC and will remove all references to the names or identities of the original contributors AND the people who support the project.

**Comment by peterix** [comment]
2. the snap format is technical inferior to a simple tarball. It is bad, do not use it.

* The 'snap package' is a filesystem image that cannot be properly opened with normal archiver tools.
* It does not solve the fundamental issue of incompatibility between linux systems anyway. Pretending otherwise is foolish.

**Comment by casept** [comment]
The snap package is not cracked. Also, I have made it private now and am waiting on store admins to take it down.

**Comment by peterix** [comment]
Well, thank you.

I feel terrible for doing this.

I'm pretty sure you mean well and there's nothing bad actually going on. It's just that dealing with what's basically proprietary software correctly is tricky. I do not want to end up being swept up in some legal nonsense because someone else did something weird. What if Mojang/Microsoft actually starts going after all the people that pirate their stuff? They aren't activelly doing anything about it, but I do not want to be confused with that crowd if they do.

On the technical side of things...

The dev version should be easier to package as a real package. Not snap or anything like that. I still think it's kinda foolish to build one set of binaries and assume it will work elsewhere. I've seen too many examples of that approach failing too. The tarballs include all sorts of libraries, but they can't include everything. It is also sometimes necessary to remove some of the bundled libraries to make things work. You run into situations like the bundled libxcb being incompatible with the libxcb that is already loaded by the graphics driver... and you can't load both versions at the same time. The dependency issue is inherently messy and just putting the software in a differently shaped box will not fix the problem.

The minimal interface is between MultiMC and its immediate dependencies - Qt5, zlib, libstdc++ and glibc. Everything else is likely to cause extra problems. So the ideal kind of package would be built with old versions of Qt5, libstdc++ and glibc, while bundling only zlib. That's my theory anyway. Compared to the snap package, that's maybe 6-10MB of stuff, while making it a lot more compatible. I simply do not have enough time to test this approach on all the distros out there though.

**Comment by Ads20000** [comment]
I see things very differently. The _status quo_ of desktop Linux packaging is a complete mess. Having easy-to-get (i.e. in the software store with no external repositories needing to be added) automatically updated applications on a properly-stable-for-Linux-noobs base is practically impossible. Apps will expect different dependency versions to work perfectly and the dependency versions depend on the exact Linux distribution. An update to those dependencies could easily affect the applications on top (not always positively). So a distro upgrade (or rolling release update) can break applications.

With snappy, upstreams use the dependency versions that they know works with their application. They can bundle dependencies and versions that aren't available in any Linux distro, if they want. They can integrate building the snap with their CI, or just use the snapcraft build service (build.snapcraft.io), and distribute it directly themselves to all systems which will then be automatically updated to the new snap. Yes, you lose out on hard drive space, but there's work going on there where you can depend on, say, a gnome content snap, which is the same across all distros.

**Comment by peterix** [comment]
Well, I'll have to disagree with that.
These are just the same things with the same problem. The only difference is the external appearance of the package and it solves none of the actual problems.

You can't share anything more complicated than a hello world between different distros. Not without running into numerous problems. The more libraries you add, the bigger the surface of what you are packaging gets and the more problems you have.

To solve this problem, you would need a set of system frameworks with hard API and ABI stability guarantees, maintained for decades, like Microsoft does. There are a few libraries that try to do this on linux - glibc, libstdc++ and Qt. If someone built Qt 5.6 for every distro under the sun and called that the 'Standard UI Framework', it would be a huge win. Changing the package format is not.

**Comment by Ads20000** [comment]
To me this system resolves the rollings vs stable issue better than any other attempted solution I've seen (though Fedora's flexibility with packages seems pretty good, and Solus' model is interesting but I don't know how stable-for-noobs it is).

**Comment by peterix** [comment]
I have no use for gnome or gtk, even if it has the right properties. It doesn't exist on Windows and macOS.
