### ISSUE TITLE
Minecraft won't launch on MultiMc, but will on regular minecraft

### ISSUE THREAD

**Issue by bepeta** [MultiMC/MultiMC5#1972]
Latest crash report, more info can provided
https://pastebin.com/siHmdeDa

**Comment by Heufneutje** [comment]
Most likely you have an old Intel GPU that's no longer supported by newer versions of Java and the reason it works on the Mojang launcher is because they ship their own (older) version of Java. You could try this version of Java, which I believe is the same one Mojang ships: https://s3-eu-west-1.amazonaws.com/files.multimc.org/downloads/jre-8u51-windows-x64.zip

**Comment by peterix** [comment]
Yep, closing, known issue in intel drivers.
