### ISSUE TITLE
Provide system-installed builds of MultiMC

### ISSUE THREAD

**Issue by kruug** [MultiMC/MultiMC5#1974]
Why does MultiMC go against best practices when saving instances?

Windows should be saved in `%AppData%` and Linux/Mac should have `~/.local/share/multimc`.  Why go against user expectations?

**Comment by peterix** [comment]
Because I do not consider these to be best practices.

**Comment by peterix** [comment]
They are awful, really.

**Comment by kruug** [comment]
Why are they awful?  They are expected locations when looking for software data.

**Comment by brodycas3** [comment]
Expected doesn't always mean it's the best option.

**Comment by kruug** [comment]
Well, depends on what you consider "best".  I would consider it "best" when that means that files are put where you would expect them to be based on typical interactions with the file system you're using.

**Comment by peterix** [comment]
I think having a portable version of something is much more valuable than conforming to expectations of placing trash all over some undefined filesystem.

So, the short answer is: I thought about it, I chose the more flexible option.

If you really want data to be placed in a fixed location, there's a handy `-d` command line option you can use to tell it where that is...

**Comment by peterix** [comment]
That said, I'm not agains having an installed form of MultiMC available. It just is a single bullet point among hundreds.

**Comment by vdh** [comment]
@peterix Windows may be a free-for-all nightmare, but storing important data inside the app itself is the absolute *worst* possible location to keep something safe on a Mac app. It's common practise to overwrite an old app with a new one when installing updates, because the expectation will be that data is saved to either `~/Library/Application Support/Appname`, or some other logical location inside the user's home folder.

In general, the `/Applications` folder is designed to house only the executables, and each user's personal data is safely managed from their home folder.

**Comment by peterix** [comment]
MultiMC is a portable application. It doesn't really belong in `/Applications` or any such place.

This idea of having a bunch of unmanageable dot folders (or your local system equivalent) all over your home is IMO awful. You end up with the application spread all over the filesystem. MultiMC stays in one place and isn't meant to mess with your system.

**Comment by peterix** [comment]
And again, look at https://workflowy.com/s/2EyDMcp7CU#/632ef2844801 -- this is something I do want to address at some point.

It requires infrastructure changes - adding more platforms and update channels to the update repo, along with doubling the number of builds.
