### ISSUE TITLE
Share mods between instances

### ISSUE THREAD

**Issue by ChellieH** [MultiMC/MultiMC5#1988]
I love the versatility that MultiMC brings as I like to try different mod combinations out but it is a little clunky and tedious to keep my different instances up to date because I have to update each instance separately. This is particularly time-consuming as all 5 of my current instances have 39 mods in common.

My suggestion is, if it is at all feasible, to have the instances be able to load mods from a specified folder. In my particular case I would have a 'Core Mods' folder containing 39 mods that all of my instances use and a 'Colony Mods' folder containing 5 mods that 3 of my instances use. Each instance would still have its own mods folder for mods that are unique to the instance. This would also help in reducing disk space usage for people with smaller hard drives.

This would also make the central mods folder that MultiMC currently has much more useful - I have a folder in my downloads folder that does exactly the same job which is quicker to navigate to when downloading updates.

Apologies if this is something already suggested - i did try and search before posting. Also apologies if this is already a functionality, if it is I haven't figured out how to do it.

Thanks for all your hard work.

**Comment by peterix** [comment]
Similar things have been suggested many times...

It's just that there is no single clean way of doing it. You can achieve something close with different approaches on different operating systems.

* On linux and macOS, you can use symlinks. On Windows, these require admin rights for every operation or the Pro version to properly activate the feature for normal users.
* You can layer filesystems on top of each other on linux - with root access and some elbow grease.
* Forge, in most of the recent versions, allows loading mods from other locations. Almost noone uses it, so it was never really tested. And because it's not in every forge version, I can't apply it to everything, even if it was a good idea.

So, I've been thinking about this for a while, and I'm not happy with any of the (partial) solutions.

The thing you can do is write a script that does what you want. You have your operating system you can actually configure and enable the features needed. Something simple that either copies files or creates symlinks (or hardlinks) would work.

**Comment by QuImUfu** [comment]
Similar things were already suggested.

If i understand your idea correctly you want to be able to make dirs inside the a global mods folder that can be added to an instance as "modfolders".  This would make updating and managing the global mods easy but would break the concept that every instance folder contains all data to launch exactly the same instance on every computer. (which is already kind of broken by local libaries)
I don't know whether this is a god idea or would only complicate things.

However i had some ideas how this could be done on all supported platforms:
MultiMC could create a json from these files and feed it liteloader and forge via a command line argument (as far as i understand https://github.com/MinecraftForge/FML/wiki/New-JSON-Modlist-format this would be possible). This would however only work with newer versions of forge and liteloader.
Another, rather quick and dirty soulution would be moving the mods from the global folder to the local mod folder and moving them back afterward. This should be much easier to do but would prevent two instances sharing one global modfolder from running at the same time.
Hardlinking or symlinking instead of moving would require platform specific hacks and admin rights on windows but would be a cleaner soulution, imo. (this was the idea discussed previously, i think)

Non of these ideas are imo good enough to be included in MultiMC but you could make pre and post launch scripts doing it for you.

**Comment by peterix** [comment]
Hm. The idea of keeping instances complete is something I missed there, but it's probably the most important one.

The reason why I can keep mojang, forge and liteloader libraries outside of instances is that their online sources are quite reliable, actively maintained and I am fairly sure the files there can be downloaded at any time.

Keeping mods out of instances? There's no reliable source of mods.

**Comment by peterix** [comment]
And yes, you can have custom libraries in instances now:
![image](https://user-images.githubusercontent.com/203326/30254018-c5fcb044-9691-11e7-85df-6b391be6ef1e.png)

**Comment by peterix** [comment]
Not breaking the containment of instances is more important.
