### ISSUE TITLE
Account retreiving from json

### ISSUE THREAD

**Issue by TheNicolasM9** [MultiMC/MultiMC5#2006]
Hi, I don't remember my account password and I found the informations of it in my MultiMC files.
Some of you will say "just ask for a new password", but I can't receive mails from Mojang so I want to try to get my password back thanks to MultiMC (to change my skin).
Does someone know what is the crypting method used ?
Thanks for aswers.

**Comment by peterix** [comment]
What you are looking at in the file are authentication tokens. The password is never saved, it is sent directly to Mojang servers, once, at the point where you add your account.

So, you will have to go through Mojang if you don't remember your password.

**Comment by calloatti** [comment]
Use the contact form here: 

https://help.mojang.com/customer/portal/emails/new

**Comment by TheNicolasM9** [comment]
That's what I've done but they told me to ask for a password retreive..

**Comment by peterix** [comment]
Look, there's nothing I can do for you in this case. And that is a good thing, because the passwords are actually secure - by not being there at all.

I'm not sure what the Mojang support told you, but this is the help page they have on password recovery:
https://help.mojang.com/customer/portal/articles/329524-change-or-forgot-password

If you don't have access to the e-mail account you used for Minecraft, you will have to contact support and have some sort of proof of purchase in hand. So, refer to:
https://help.mojang.com/customer/portal/articles/361380-what-is-a-transaction-id-

**Comment by TheNicolasM9** [comment]
> I'm not sure what the Mojang support told you, but this is the help page they have on password recovery

But the problem is that I don't receive the mail with instructions..

> If you don't have access to the e-mail account you used for Minecraft, you will have to contact support and have some sort of proof of purchase in hand.

I have the e-mail but since it was a gift 8 years ago from a friend who's dead, I don't have any proof of buying

**Comment by peterix** [comment]
The reality of the situation is that you can either:
* somehow gain access to whatever e-mail account was used to register this copy of Minecraft
* get some sort of proof of purchase (or gift code if you got one - did your friend send you a gift code, or just login info?)
* try to get Mojang support to somehow handle this it for you

It is not in my power to directly help you.
