### ISSUE TITLE
PML Problem

### ISSUE THREAD

**Issue by XxThatOneFurryxX** [MultiMC/MultiMC5#2033]
Hi there!

I am trying to install a mod that requires the Partial Modification Loader (PML)

I have been asking the devs of it, and they don't know about MultiMC and well... didn't know how to help. I want the mod to work with a mod pack I am working on. 

I am so f***ing confused right now. I know that PML requires that you change the Java Arguements so I put the code from the installation guide into it, and guess what? IT DIDN'T WORK. I took the java arguements from the 1.8.9 edit in the vanilla launcher and put it in, and put the PML code into it afterwards, and didn't work either...

HELP!!

**Comment by mikroskeem** [comment]
What/where did you change exactly? Paste your launcher logs? Your issue does not contain any information what could help project's developers.

**Comment by peterix** [comment]
Right... this is a weird thing and it does really weird things to Java, Minecraft and Forge. There's a *chance* it might work under some undefined conditions, but I can't really tell you what the conditions are, or how to make that happen.

I am assuming you use the `develop` version of MultiMC. Stable ... just forget it. 

So, here's what I tried:
MultiMC has two launch mechanisms - the LauncherPart and DirectJava. LauncherPart is default and works around some Java bugs and security deficiencies. You can enable DirectJava (basically exactly what tje Mojang launcher does) by editing the instance.cfg like this:
```
ForgeVersion=10.13.4.1558
InstanceType=OneSix
IntendedVersion=1.7.10
JvmArgs=-javaagent:PMLCore/PMLPremain.jar=-MCSide:Client
LWJGLVersion=2.9.1
LiteloaderVersion=
LogPrePostOutput=true
MCLaunchMethod=DirectJava
OverrideCommands=false
OverrideConsole=false
OverrideJavaArgs=true
OverrideJavaLocation=false
OverrideMCLaunchMethod=true
OverrideMemory=false
OverrideWindow=false
iconKey=default
lastLaunchTime=1509750920767
name=Test PML
notes=
totalTimePlayed=67
```

The important parts are:
```
OverrideMCLaunchMethod=true
MCLaunchMethod=DirectJava
```

This ... sort of helps? But not really. The seasons mod:
* is flagged as duplicated if you put it in the mods folder - this has been reported before: https://github.com/TheWeatherPony/TheSeasonsMod/issues/113
* or crashes because of some json error when put in the PMLMods: https://paste.ee/p/D0jQ6

As this launch method is basically identical (or as close as I am willing to get it) to how vanilla would launch it, I just think the loader and the mod are buggy in some way.

Maybe it only works on oracle java on windows? Maybe with some specific version of it? It tries to patch some low level classes it IMO really has no business of touching.
