### ISSUE TITLE
Select folders or files in instances to sync between them.

### ISSUE THREAD

**Issue by MichaelPriebe** [MultiMC/MultiMC5#2052]
For example, I would like my servers.dat, or journeymap folder to sync between instances. So I can have my servers, and mapped worlds on any instance.

**Comment by peterix** [comment]
That... is quite tricky.

The efficient way to do that is symlinks. Depending on OS and configuration, you can already do that, but I can't use it everywhere, because Windows is not enabling them by default.

The inefficient way to do it  is to watch the files for changes and copy them around. This solves the issues on Windows systems, filesystems other than NTFS and so on... but introduces other problems.

Both have really weird corner cases. The kind of corner cases that will eat your files, corrupt your worlds and crash that minimap mod you are using. It is entirely possible to run two instances that share the same files with both writing into the same files. What happens when multiple 'synced' copies are changed? Do I somehow go and start merging those changes?

I don't think this should be exposed in the UI.

**Comment by peterix** [comment]
For reference:
https://workflowy.com/s/2EyDMcp7CU#/d3ba0e47c6c2
https://github.com/MultiMC/MultiMC5/issues/42
https://github.com/MultiMC/MultiMC5/issues/413
https://github.com/MultiMC/MultiMC5/issues/681
... and many others.

The most workable of all those ideas is to have a sort of template for new instances that puts in all the things you would end up setting manually anyway.
