### ISSUE TITLE
Minecraft mod crash again

### ISSUE THREAD

**Issue by SmallEnderman** [MultiMC/MultiMC5#2123]
I've removed some mods and added some new mods... but now it crashes again without saying this is the problem or that is the problem... can someone pls help me?

Link: https://paste.ee/p/qCRMl

**Comment by chaos234** [comment]
```Caused by: java.lang.ClassNotFoundException: amerifrance.guideapi.api.impl.abstraction.CategoryAbstract```

Suggesting to look if u have the correct version of GuideAPI installed and if not, download and install it and try again. If it crash again, look closly into the crash report if there are new "ClassNotFoundExceptions" because mostly you can see the mods name from which the calss comes and then u know what u've to download in addition ;).

**Comment by SmallEnderman** [comment]
it works now ty
