### ISSUE TITLE
Main Issue in MultiMC

### ISSUE THREAD

**Issue by Fred1124** [MultiMC/MultiMC5#2136]
System Information
-----------------------------
MultiMC version:
0.6.1
Operating System:
Windows 10 Home
Summary of the issue or suggestion:
----------------------------------------------
Minecraft 1.7.10 is not launching

What should happen:
------------------------------
Minecraft should launch

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Download the mods.

2.Rename it to "My Mod".

3.Launch.

Suspected cause:
---------------------------
The Main Issue

Logs/Screenshots:
----------------------------
https://paste.ee/p/Vg2iS

Additional Info:
---------------------------

**Comment by Fred1124** [comment]
Issue solved

**Comment by peterix** [comment]
There are multiple issues present. At the very least:

You are using 32bit Java. That probably won't be an issue with this few mods, but you should consider using 64bit, just like the log says:
```
Java is version 1.8.0_161, using 32-bit architecture.
Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.
```

You are mixing mods for different version of Minecraft in one instance:
* appliedenergistics2-rv5-stable-8 -- 1.12.2
* MatterOverdrive-1.7.10-0.4.2 -- 1.7.10
* ProjectE-1.12-PE1.2.0 -- 1.12, 1.12.1, 1.12.2

Because Matter Overdrive's last release is for 1.7.10, you will have to use the 1.7.10 version of the other mods if you want to use it.
