### ISSUE TITLE
MCBuild "Not authenticated with minecraft.net"

### ISSUE THREAD

**Issue by ZafotheNinja** [MultiMC/MultiMC5#2148]
System Information
-----------------------------
MultiMC version: 0.6.1-1177

MCBuild version: 2.0

Operating System: Windows 7 64bit (jre 1.8.0 161-b12)

Summary of the issue or suggestion: 
----------------------------------------------
When running with MCBuild, Minecraft refuses to authenticate.

What should happen: 
------------------------------
Successful login to any multiplayer world

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch MCBuild

2. Launch any Minecraft (tested with 1.11.2 and 1.12)

3. Connect to 127.0.0.1

Suspected cause:
---------------------------
MultiMC is not transmitting the login token in a way that MCBuild can forward it.

Logs/Screenshots:
----------------------------
https://paste.ee/p/HBv04
https://imgur.com/mN0UN2I

Additional Info:
---------------------------

Error not existent using regular Minecraft launcher.

**Comment by peterix** [comment]
That's the weirdest thing I've seen yet.

I cannot help you with this one, as it does some magical things and directly depends on some files from the mojang launcher:

**Comment by peterix** [comment]
This whole thing would have to be replaced with something that isn't crazy:
https://github.com/broese/mcbuild/blob/41b4d03bdf64420a514e0291820f018e1a556269/mcproxy.c#L793-L866

**Comment by broese** [comment]
MCB dev here. I took a look at the issue. If I see right, MultiMC saves profiles at MultiMC/build/accounts.json . I think I just need to extend the profile parser to support this format and extract the authentication token. I'm on it.

**Comment by broese** [comment]
I implemented the parser, it works now fine with MultiMC.
https://github.com/broese/mcbuild/issues/21

I think this issue can be closed on your side. Although, my general suggestion would be that MultiMC should just use the default location of the user profiles (i.e. ~/.minecraft/laucher_profiles.json) and their format. You have pretty much identical information there, just in a different format. This would also keep vanilla MC installation authenticated.

MCBuild uses the authentication tokens from the profile in order to authenticate itself against the remote server and Mojang. The client traffic is hijacked as in a man-in-the-middle attack, so MCBuild can inject its packets directly into the protocol. Makes everything compatible with any client mods / custom clients.

**Comment by peterix** [comment]
That is simply not going to happen, because MultiMC is not meant to intersect with the vanilla stuff. It does not have any default installation path (as there is no installation), and it is expected that the user puts it (along with all necessary data) wherever they want - including network shares, USB sticks, cloud storage, etc. You can have multiple copies on the same machine and they should never intersect either. The formats are my own, and I see any dependency on a third party (and yes, Mojang **is** a third party in this case) as a serious flaw and a big problem waiting to happen.

I think that this sort of interaction between MultiMC and mcbuild can cause problems in the future, in case I need to change this format. It would be best to stay in contanct. You can always test with the dev version of MultiMC and in case there's breakage, tell me. Such problems should not end up in stable versions.

Also, the authentication is per client, and you can have any number of authenticated clients for your account. Two launchers using the same set of auth tokens would lead to desync and problems if they were used at the same time (sharing auth files one the same machine without locking is a big NO-NO, you would end up with invalid tokens).

I've never really looked at the session and auth flows between the client and server, but isn't there a way to just reuse the existing session tokens already passed to the server? That is, session tokens are passed to server A (MITM), which would pass them to server B (real) transparently? Is there a reason for mcbuild to even deal with the mojang auth stuff?

**Comment by broese** [comment]
Doing pure MITM was possible before, but at some point, Mojang has enforced a three-way authentication:
1. client authenticates against the server and they establish encryption keys
2. client authenticates against sessionserver.mojang.com (via HTTP)
3. server also authenticates against Mojang to verify that the client is valid and then login process is complete.
MCB has intercept the step 1 by doing MITM and then complete step 2 as if it was the real client. Therefore it needs access to the authentication token stored in the profile. The token itself is not transmitted in the protocol, only used to produce correct message.

The only other way to do this would be to supply full username/password to MCBuild, which is obviously less secure and will cause conflicts with the launcher. Or by doing MITM on HTTPS traffic, which is not quite easy.

Regarding the profile - I agree it's the MCB's task to support the launcher, not the other way around. It wasn't difficult to adapt the format, and I already had to deal with Mojang's own format changing several times in the past.

**Comment by peterix** [comment]
Alright. I'd have to stare at http://wiki.vg/Protocol_Encryption#Authentication for a while and play with it to see if there's some other way, but it seems that there isn't, because both the client and the server need to report the same 'server hash', which depends on setting up the encryption keys.

The other way to get the auth token to MCB would be to pass it directly, like it does this with the client (using standard input or some similar mechanism).
