### ISSUE TITLE
Why my skin does not appear?

### ISSUE THREAD

**Issue by wpmidia** [MultiMC/MultiMC5#2152]
System Information
-----------------------------
MultiMC version:  0.6.1-1177

Operating System: Windows 10 64bits

Summary of the issue or suggestion:
----------------------------------------------

What should happen:
------------------------------
Mojang skins server status OFFline to me, but in help.mojang.com, server status is ON.
My skin doesn't appear for me :(
![multimc_skins_problem](https://user-images.githubusercontent.com/3352842/36340562-0f9279f2-13c7-11e8-9f7c-39f0398db94e.JPG)

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by tehbasshunter** [comment]
As mentioned in #2143 Mojang dropped the previous way to monitor skins and switched to a new one. This has already been fixed in the dev version. You can switch to it and fix this by going into MultiMC settings and [changing this to development](https://mom-get-the.camera/9bhfwh.jpeg). Check for updates again and you'll be good to go.
