### ISSUE TITLE
instance flashing colors {Solved}

### ISSUE THREAD

**Issue by MeralMiral** [MultiMC/MultiMC5#2371]
whenever i start an instance it just flashes black and white
![aug-11-2018 19-40-40](https://user-images.githubusercontent.com/42306925/43997376-bdf7268a-9d9e-11e8-8cf1-43e4b374870a.gif)

**Comment by Heufneutje** [comment]
Does this happen when you use the vanilla launcher? Also hit the "Upload log" button in your MultiMC console window.

**Comment by MeralMiral** [comment]
yes and heres the console log https://paste.ee/p/9Ib6t

**Comment by tehbasshunter** [comment]
Pretty sure Java 10 won't work with old beta versions

**Comment by MeralMiral** [comment]
oh ok

**Comment by MeralMiral** [comment]
is there a way to play old beta versions

**Comment by Heufneutje** [comment]
Yes, by not using Java 10. Install an older version of Java.

**Comment by peterix** [comment]
That only applies to the vanilla launcher, it should work in MultiMC.

You need to grab the game resources folder and put it in manually, because the server the game was downloading that from is gone.

You can get the beta resources here:
https://mega.nz/#!R7hV0C5Z!HG2Bv69RTnAuxO0cHeQypuq8IrZYbl0_aCRUWR9IpWg

Put the `rescources` folder into the `.minecraft` folder that's inside the instance.
