### ISSUE TITLE
[Feature Request] Mojave Dark Mode when using System Theme on macOS

### ISSUE THREAD

**Issue by oitsjustjose** [MultiMC/MultiMC5#2442]
System Information
-----------------------------
MultiMC version: 0.6.2-develop-1188

Operating System: macOS Mojave 10.14.1

Summary of the issue or suggestion:
----------------------------------------------

Using the "System" theme on macOS always yields the default (now Day-mode) theme. It'd be *nice* if it changed to Night mode with the system, and while I don't fully understand *these* libraries (never got far into C++ in my Survey course) I can't imagine it'd be impossible considering the system theme you get is dynamic; in theory, this should allow you to get a night theme from the system just as easily.

What should happen:
------------------------------

System theme on macOS should shift to Dark mode with the system preference.

**Comment by peterix** [comment]
I target 10.7, not 10.14.

**Comment by peterix** [comment]
Also:
https://bugreports.qt.io/browse/QTBUG-68891?focusedCommentId=424230&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-424230

**Comment by peterix** [comment]
So, I would have to cut off everyone not using 10.14... That's just not happening.

**Comment by peterix** [comment]
Is it worse than using the light theme? Is anything fundamentally broken?

**Comment by peterix** [comment]
Mainly, there's apparently a bug in the dark mode stuff itself: https://openradar.appspot.com/41206326

**Comment by oitsjustjose** [comment]
I guess that's a fair point, I just didn't realize that QT even was unable to adjust for Dark Mode yet. For now I'm just using the packaged Dark theme, I'm just generally a purist about UI crap ¯\\\_(ツ)\_\/¯

**Comment by oitsjustjose** [comment]
Oh - sidenote: is there an place that MultiMC Custom themes are generally hosted? Just curious

**Comment by peterix** [comment]
Not really? The idea was to do something with those at some point, but there's just nothing in place.

If you make one, put it on github and let me know :)

----

Also, keeping this open so it can be tracked.

I'm not sure if or when can this be fixed... I assume I'd have to backport some of the Qt fixes myself and make this theming support a runtime decision instead of a build time decision (looking up symbols in system libraries manually from code).

**Comment by JacksonChen666** [comment]
It seems like the [issue](https://bugreports.qt.io/browse/QTBUG-68891) has been fixed in Qt 5.12.0 alpha, and I had a version newer than that. It finished with a [complete dark mode version of the app](https://imgur.com/a/GiCttz5).

I had to also follow #3564 in the process, but no modifications to the code were made.

**Comment by peterix** [comment]
We cannot use Qt 5.12

**Comment by AverageComet250** [comment]
Why

**Comment by kb-1000** [comment]
Compatibility with old OS versions, from what I know.

**Comment by peterix** [comment]
Fixed in dev.
