### ISSUE TITLE
Request: Import launch configurations from vanilla launcher

### ISSUE THREAD

**Issue by GiovanH** [MultiMC/MultiMC5#2466]
**Request:** Import launch configurations from vanilla launcher

MultiMC should have an option to read launch configurations from the vanilla minecraft launcher and create equivalent MultiMC instances.

Because MultiMC supports every feature of the vanilla launcher, such an import should be possible. 

This would only be a one-way conversion: MultiMC would not be expected to *export* multimc instances to the vanilla launcher.

**Use case:**
I would like to switch over to MultiMC, but I already have a lot of custom launch configurations in the vanilla launcher, including modpacks. 

It seems that this could probably be accomplished as easily as reading the `%appdata%/.minecraft/launcher_profiles.json` file

**Comment by GiovanH** [comment]
Given how MultiMC handles instances, though, there would have to be some copying of directories.

**Comment by peterix** [comment]
Import should be fine, tracking or otherwise directly using those wouldn't be.

There's just the issue of having to either:

* produce a low quality instances (libraries with uncertain origin made local, large amount of data duplication)
* Guide the user through the process somehow, and ask questions when something ambiguous is encountered
* Guess and hope it's right

Maybe some combination of the above. There are some ugly corner cases involved if this should produce decent results.
