### ISSUE TITLE
Allow correct launching of multiple MultiMC 'instances' from Steam

### ISSUE THREAD

**Issue by Altreus** [MultiMC/MultiMC5#2518]
System Information
-----------------------------
MultiMC version: 0.6.4-1291

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
One can use the command line to add a game to Steam which can then be used by in-home streaming to launch a particular instance of Minecraft from a remote computer:
 
    "D:\Games\MultiMC\MultiMC.exe" --launch "Enigmatica 2"

An issue arises if MultiMC is already running on this computer, because it reuses the existing instance instead of launching a new one. Steam decides the operation failed, and stops attempting to stream.

One could add a parameter to prevent MultiMC from reusing the existing instance on launch, solving the problem.

    "D:\Games\MultiMC\MultiMC.exe" --launch "Enigmatica 2" --no-reuse-process

What should happen:
------------------------------

When Steam launches the application, it should not be under the impression it failed to run.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create a Steam game similar to above
  * Steam -> Add non-steam game to my library -> Select MultiMC
  * edit new game to launch specific instance

2. Run MultiMC manually

3. Stream this new game from another computer on the same network

4. Observe that Minecraft runs, but Steam gives up before it has even launched.

5. Close MultiMC and the new Minecraft

6. Try streaming again. Now it works.

Suspected cause:
---------------------------

I suspect Steam launches the process and is given a PID, or whatever Windows has instead of PIDs. This PID then looks for an existing instance, finds one, communicates with it, and exits. Steam believes the game to have exited.

Pressing Stream again in this situation actually causes the console window to launch and come to the foreground.

**Comment by Altreus** [comment]
I had another thought. When I launched MultiMC to find out what the version was, an instance was already running through Steam. So the executable latched onto this and spawned the main UI window. So when I exited Minecraft from Steam streaming, it just switched to this window and kept "playing".

Perhaps a second flag that prevents it from *being discovered* might also be worthwhile? Although this is a very edge case in this situation, it might be useful in other situations, although I can't think of any.

Alternatively, a single flag that runs it in a sort of "ringfenced" mode that stops any other MultiMC from interacting with it.

**Comment by peterix** [comment]
It would be unsafe to have two instances of MultiMC running on top of one folder. The first running copy will act as a service and any other copies detect it and send it simple commands to execute.

The second MultiMC would have to tell the main MultiMC that an instance is being started, start it as a child process, stay around while the game is running, and communicate with the main MultiMC (pass through logs and other status info).

Doable, but this is a weird edge case, and there are many other things that need doing.

So, maybe if someone who cares about this picks this up and does it?

**Comment by Sakata-MC** [comment]
Any luck on this?  Would love to be able to stream, though I can understand that there are likely more pressing matters to develop for.

**Comment by peterix** [comment]
Something weird as this shouldn't be stopping you from streaming... Just load up OBS and go.

**Comment by DecentM** [comment]
I want to necro this issue, as it came up for me too and I think there's miscommunication here.
> Just load up OBS and go.
I don't think OP was talking about live streaming to an audience, but instead the feature in Steam where you can have your more powerful PC sitting in the office, while you can play from a weak laptop from a couch over the network. Steam calls this in-home streaming. It will transmit user input on the client over the network to the host PC and stream video ouput from the game to the client, therefore, making it possible to play heavy games on underpowered computers. OBS is not capable of this functionality.

In-home streaming requires Steam to be able to directly launch the game process so that it can attach input emulation and start the video stream from the opened window (the window doesn't have to directly open from the launched process, not quite sure how but it seems to figure it out, I guess based on the process subtree).

A turbo hacky workaround could be to run `taskkill /IM "MultiMC.exe" /F` in a batch script before starting the needed instance. It will probably leave orphaned processes, so I guess the best idea is to ensure MultiMC is not running before starting remote play.

BTW this issue also occurs with Chrome for the exact same reason.

> It would be unsafe to have two instances of MultiMC running on top of one folder.
Just out of curiosity, what would the complications be if MultiMC would allow itself to be ran multiple times (provided that the user doesn't care about passing logs and whatnot through)?

It may also be an option to add instances to steam while bypassing MultiMC and manually constructing the launch command. Of course, this will lose us the log output and other features, but it could allow for in-home streaming.

**Comment by peterix** [comment]
In any case, this works as intended, and it is steam that should implement a more comprehensive version of it's crazy hack.

**Comment by peterix** [comment]
Nothing will be done here.
