### ISSUE TITLE
Aristois 1.13.1 and MultiMc not working

### ISSUE THREAD

**Issue by Volteius** [MultiMC/MultiMC5#2560]
Hi, I'm trying to launch Aristois 1.13.1 using MultiMc 0.6.5-1302 but I can't get this to work. I tried "add to minecraft jar" and even adding it as "Loader mods". Is there a way to make it works?

**Comment by Timardo** [comment]
Cheaters should find their own ways to use cheats. It took me a while until I got wwe client to work, but I didn't ask anyone and I won't told anyone how even if someone ask. I shouldn't be using it at all, but I just want the HUD and fullbright stuff.

**Comment by Volteius** [comment]
I'm not using it for cheating. The server where my friends and I are playing since 2017 is closing, the admin let use save our buildings, but they are very distance from each others. I saw that Aristois let me use infinite elytra and so I'm trying to use it with world dowloader to save how much that I can.

**Comment by spannerman79** [comment]
> the admin let use save our buildings

then the admin should give you the correct worldedit perms, or connect in via forge and use the schematica mod

**Comment by peterix** [comment]
ask your admin for a world backup

**Comment by Volteius** [comment]
The server is on 1.13.1, no forge. Only the overworld is over 100 gb. They say they are not giving as the entire world.

**Comment by QuImUfu** [comment]
Installing EMC (the Modding framework Aristois uses) is possible by adding a file named:
```me.deftware.emc.json```
in {path to instance}/patches.  
And by changing 
```mmc-pack.json```
in {path to instance}
```me.deftware.emc.json``` should contain:
For 1.12.2:
```
{
    "formatVersion": 1,
    "+libraries": [
        {
            "name": "net.minecraft:launchwrapper:1.12"
        },
        {
          "name": "me.deftware:EMC:13.5.6-1.12.2",
          "url": "https://gitlab.com/EMC-Framework/maven/raw/master/"
        },
        {
          "name": "org.spongepowered:mixin:0.7.1-SNAPSHOT",
          "url": "http://dl.liteloader.com/versions/"
        },
        {
          "name": "net.jodah:typetools:0.5.0",
          "url": "https://repo.maven.apache.org/maven2/"
        }
    ],
    "+tweakers": [ "me.deftware.launch.Launcher" ],
    "fileId": "me.deftware.EMC",
    "mainClass": "net.minecraft.launchwrapper.Launch",
    "requires": [
        {
            "uid": "net.minecraft",
            "equals": "1.12.2"
        }
    ],
    "name": "EMC",
    "uid": "me.deftware.emc",
    "version": "1"
}
```
For 1.13.2:
```
{
    "formatVersion": 1,
    "+libraries": [
        {
            "name": "net.minecraft:launchwrapper:1.12"
        },
        {
          "name": "me.deftware:EMC:13.8.1-1.13.2",
          "url": "https://gitlab.com/EMC-Framework/maven/raw/master/"
        },
        {
          "name": "org.spongepowered:mixin:0.7.1-SNAPSHOT",
          "url": "http://dl.liteloader.com/versions/"
        },
        {
          "name": "net.jodah:typetools:0.5.0",
          "url": "https://repo.maven.apache.org/maven2/"
        }
    ],
    "+tweakers": [ "me.deftware.launch.Launcher" ],
    "fileId": "me.deftware.EMC",
    "mainClass": "net.minecraft.launchwrapper.Launch",
    "requires": [
        {
            "uid": "net.minecraft",
            "equals": "1.13.2"
        }
    ],
    "name": "EMC",
    "uid": "me.deftware.emc",
    "version": "1"
}
```
```mmc-pack.json``` needs a component added looking:
```
        {
            "cachedName": "EMC",
            "cachedVersion": "1",
            "uid": "me.deftware.emc"
        }
```

Additionally you need to use curl or some similar program that allows setting Request Headers to download Aristois. e.g.:
for 1.13.2:
`curl -v -H "User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36" -H "token:" -H "file:1.13.2/232/free.jar" https://aristois.net/maven/download --output ./Aristois.jar`
for 1.12.2:
`curl -v -H "User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36" -H "token:" -H "file:1.12.2/220/free.jar" https://aristois.net/maven/download --output ./Aristois.jar`

Because The path where EMC looks for mods is hardcoded here:
https://gitlab.com/EMC-Framework/EMC/blob/master/src/main/java/me/deftware/client/framework/utils/OSUtils.java  
you need to put the file in `.minecraft/libraries/EMC/1.12.2` or `.minecraft/libraries/EMC/1.13.2` where ever that is on your system. Or you could create an issue asking them to un-hardcode the location.

After that it should work.

**Comment by peterix** [comment]
Hardcoding the `.minecraft` location in anything is definitely a bug, because you can change it in the vanilla launcher too.

**Comment by Volteius** [comment]
Thank you very much for the help, i figured out 2 days ago. I simply clicked “ add empty” and added emc and his uid, edited it with a similar code but without downloading the jar. So I’m now able to use aristois & world downloader together on multimc.

**Comment by QuImUfu** [comment]
if you used the Aristois installer before, it downloaded and installed the jar for you to .minecraft/libraries/EMC/1.13.2.

**Comment by Floatingamer** [comment]
hi could someone reply and send me the instance because it wont work for me thanks
