### ISSUE TITLE
Add Multimc "Plugins"

### ISSUE THREAD

**Issue by loper12** [MultiMC/MultiMC5#2562]
It would be nice just to add something that would help alot of people add their own flare to multimc

**Comment by Heufneutje** [comment]
Pretty sure this has been rejected many times before already.

**Comment by Janrupf** [comment]
Correct, the problem is that MultiMC's API would be pretty unstable if it would have one.

**Comment by peterix** [comment]
The main issue is that I really do not want to make an API (designing a good API is a lot of hard work) and definitely do not want to maintain it afterwards (this ultimately results from designing the API wrong, and EVERY API will be wrong, because nobody knows the future).

Those people are free to work with the code as is and send pull requests.
