### ISSUE TITLE
Allow storing instances outside the instances folder

### ISSUE THREAD

**Issue by rootbear75** [MultiMC/MultiMC5#263]
For example: if I am working on an instance, I could set specifically that instance's working directory to a folder in Dropbox.  Obviously this could cause corruption in world saves due to multiple people playing out of the same directory at the same time, however, that would be something you would warn the user.

Could also allow people to use their worlds on multiple computers, e.g. at work, on the road, on other computers.  Or it could allow people to customize the way MMC is organized.

**Comment by peterix** [comment]
This is indeed better done with external tools. Git specifically is a great tool for working on modpacks and testing them in a small team.

Symlinks can be used even on Windows, as long as you are the administrator. For whatever silly reason, Microsoft doesn't trust people with symlinks...

**Comment by peterix** [comment]
So. I thought about it a bit. And it can be done.

On Windows, I can teach MultiMC how to resolve `.lnk` files. Elsewhere, I can use actual symlinks.

It works on the instance level, because there is full control over the resolving mechanism. `.lnk` files likely do not work for things like sharing resource packs between instances.

**Comment by peterix** [comment]
[Moved to workflowy (Ideas -> Instances outside the instances folder)](https://workflowy.com/s/2EyDMcp7CU)
