### ISSUE TITLE
Process exited with code -1?

### ISSUE THREAD

**Issue by Radulars** [MultiMC/MultiMC5#2654]
System Information
-----------------------------
MultiMC version: 0.65-1302

Operating System: Windows 10 64-bit

Summary of the issue or suggestion: Launch MC and crash
----------------------------------------------

What should happen:
------------------------------
Launch Minecraft, load up mods, and play

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open a modded instance

2. Load until half-way or so

3. Crash

Suspected cause:
---------------------------
Not entirely sure.

Logs/Screenshots:
----------------------------
https://paste.ee/p/01WYk

Additional Info:
---------------------------
N/A

**Comment by QuImUfu** [comment]
Upgrade Immersive Engineering or downgrade forge.

**Comment by MorphalFSR** [comment]
> Upgrade Immersive Engineering or downgrade forge.

I had somewhat the same issue and I don't understand why I would need to downgrade forge if the modpack is in the same version and how to upgrade Immersive Engineering.

**Comment by QuImUfu** [comment]
The newer forge versions for 1.12.2 changed, making the old version of Immersive Engineering crash.  
Because of that you need to downgrade forge (to a version that works with old Immersive Engineering) or upgrade Immersive Engineering (to a version that was updated to work with new forge versions).
