### ISSUE TITLE
Unable to resolve mod IDs when adding curseforge modpacks

### ISSUE THREAD

**Issue by StarkRG** [MultiMC/MultiMC5#2701]
System Information
-----------------------------
MultiMC version: 0.6.5-develop-1234

Operating System: Linux - Ubuntu 18.10 - Kernel: 4.18.0-21-generic

Summary of the issue or suggestion:
----------------------------------------------

This is very possibly an example of issue #1977 however the errors in the log are different so I didn't feel comfortable adding it to that issue.

Trying to add [Antimatter Chemistry](https://minecraft.curseforge.com/projects/antimatter-chemistry/files/2727257) to MultiMC starts out ok, but ultimately fails saying that there are some mod IDs it can't resolve. Looking at the log shows that most of the mods are resolved just fine, but there are two that aren't.

Using the IDs found in the log I've determined that the two files MultiMC aren't able to download are [JustEnoughEnergistics-1.12.2-1.0.7.jar](https://minecraft.curseforge.com/projects/just-enough-energistics-jee/files/2726897) and [tombstone-3.5.4-1.12.jar](https://minecraft.curseforge.com/projects/corail-tombstone/files/2726888)

What should happen:
------------------------------

The mod IDs should be resolved and the files downloaded.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Click "Add Instance"

2. Select "Import from zip"

3. Either enter the [url of the download file](https://minecraft.curseforge.com/projects/antimatter-chemistry/files/2727257/download), or download it and choose the downloaded zip.

4. Click "OK"

Suspected cause:
---------------------------

It looks like maybe curse has changed their API in some way that works with some files but not others. In particular the returned value "FileNameOnDisk" is null and another value "__comment" is "WARNING: Deprecated API, Should only be used by existing users."

On further investigation, it seems that the site MultiMC gets its information from is broken. https://cursemeta.dries007.net/ displays the message "Warning: Everything is broken. For a working version (that is still in development), visit staging_cursemeta.dries007.net." However, the staging site returns "Internal Server Error", and it looks like the author hasn't been doing much with the API since November.

Logs/Screenshots:
----------------------------
Here is the relevant section of the MultiMC log showing the errors: https://pastebin.com/L6ZZL3g6

**Comment by Nezarn** [comment]
Happens with [VolcanoBlock 1.0.8](https://minecraft.curseforge.com/projects/volcano-block) too

> 6795.574 D Task "NetJob(Mod id resolver)" succeeded
 6795.577 C Exception: "'FileNameOnDisk' is not a string"
 6795.578 C Resolving of 243707 2726888 failed because of a parsing error:
 6795.578 C "'FileNameOnDisk' is not a string"
 6795.578 C JSON:
 6795.578 C "{\"Id\":0,\"DisplayName\":null,\"FileName\":null,\"FileDate\":\"0001-01-01T00:00:00\",\"FileLength\":0,\"ReleaseType\":0,\"FileStatus\":0,\"DownloadURL\":null,\"IsAlternate\":false,\"AlternateFileId\":0,\"Dependencies\":[],\"IsAvailable\":false,\"Modules\":[{\"Foldername\":\"META-INF\",\"Fingerprint\":724191878},{\"Foldername\":\"ovh\",\"Fingerprint\":4199845908},{\"Foldername\":\"assets\",\"Fingerprint\":1376225021},{\"Foldername\":\"mcmod.info\",\"Fingerprint\":1835280330}],\"PackageFingerprint\":0,\"GameVersion\":[\"1.12.2\"],\"InstallMetadata\":null,\"ServerPackFileId\":null,\"HasInstallScript\":false,\"GameVersionDateReleased\":null,\"FileNameOnDisk\":null,\"__comment\":\"WARNING: Deprecated API, Should only be used by existing users.\",\"_Project\":{\"Path\":\"mods\",\"PackageType\":\"Mod\"}}"
 6795.580 C Task "Flame::FileResolvingTask(0x7384900)" failed:  "Some mod ID resolving tasks failed."
 6795.580 C Task "InstanceImportTask(0x72f2af8)" failed:  "Unable to resolve mod IDs:\nSome mod ID resolving tasks failed."
 6795.709 C Task "InstanceStaging(0xdf2d668)" failed:  "Unable to resolve mod IDs:\nSome mod ID resolving tasks failed."

**Comment by dries007** [comment]
Has been fixed. It was a caching issue (corrupt data was returned by Curse without any error code and it got into the cache.)
