### ISSUE TITLE
Process exited with code 1

### ISSUE THREAD

**Issue by Hillionliat** [MultiMC/MultiMC5#2755]
I need help I can't run instances i have tried multiple versions but it always gives me the same error
Process exited with code 1

Here is a full log
MultiMC version: 0.6.

Minecraft folder is:
C:/Users/Evgen/Desktop/MultiMC/instances/1.12.2/minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_211/bin/javaw.exe

Java is version 1.8.0_211, using 64-bit architecture.

Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/Users/Evgen/Desktop/MultiMC/instances/1.12.2/natives

Libraries:
  C:/Users/Evgen/Desktop/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  C:/Users/Evgen/Desktop/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/Evgen/Desktop/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Window size: 854 x 480

Minecraft process ID: 9272

Exception in thread "main" java.lang.NoClassDefFoundError: com/mojang/authlib/AuthenticationService
	at net.minecraft.client.main.Main.main(SourceFile:38)
Caused by: java.lang.ClassNotFoundException: com.mojang.authlib.AuthenticationService
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 1 more
Process exited with code 1.

**Comment by Zetabite** [comment]
Do you have a legit copy of MC and did you download MMC from the MMC website?

**Comment by Hillionliat** [comment]
I think i do

**Comment by KevenBlazerx** [comment]
I'm with the same problem

**Comment by S10MC2015** [comment]
Maybe your antivirus is blocking Minecraft or MMC. Or you are using a cracked version of MMC which you shouldn't.
You can also reinstall multimc from https://multimc.org/#Download

**Comment by peterix** [comment]
Delete C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
And see if it works.

**Comment by KevenBlazerx** [comment]
Now this

MultiMC version: 0.6.


Minecraft folder is:
C:/Jogos/Minecraft/LAUNCHERS/MultiMC/instances/Machinima/.minecraft


Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe


O Java é da versão 1.8.0_211, usando arquitetura de 64-bits


Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/instances/Machinima/natives

Libraries:
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2838/forge-1.12.2-14.23.5.2838-universal.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Jogos/Minecraft/LAUNCHERS/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  [1.12.2]+SecurityCraft+v1.8.12
  AutoRegLib-1.3-26
  blockbuster-1.6-1.12.2
  Carry-On-Mod-1.12.2
  DecoCraft-Mod-1.12.2
  Dynamic-Lights-Mod-1.12.2
  MCJoypad-Mod-1.12.2
  mclib-1.0.2-1.12.2
  metamorph-1.1.8-1.12.2
  More-Player-Models-Mod-1.12.2
  placeableitems 1.12.2
  Quark-r1.5-168

Window size: 854 x 480

ID do Processo do Minecraft: 6056


2019-07-27 13:18:35,937 main ERROR Error processing element Queue ([Appenders: null]): CLASS_NOT_FOUND
2019-07-27 13:18:36,180 main ERROR Unable to locate appender "ServerGuiConsole" for logger config "root"
[13:18:36] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[13:18:36] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[13:18:36] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
Exception in thread "main" java.lang.NoClassDefFoundError: com/mojang/authlib/exceptions/AuthenticationException
	at net.minecraftforge.fml.common.launcher.FMLTweaker.acceptOptions(FMLTweaker.java:123)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:114)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.mojang.authlib.exceptions.AuthenticationException
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 3 more
Minecraft foi fechado com o código de saída 1.

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
