### ISSUE TITLE
Do not copy play time when copying an instance

### ISSUE THREAD

**Issue by VADemon** [MultiMC/MultiMC5#2769]
MultiMC version: 0.6.6

Summary of the issue or suggestion:
----------------------------------------------
When copying an instance, MultiMC also copies old instance's played time. Thus the new (independent) instance has the same amount of time played (total time is doubled over real time spent), confusing the user, making the statistic useless and it will cause problems with #2345 #2736 (total time played)

What should happen:
------------------------------
Reset stat for new instance to zero. Imported instances should probably ask a user what to do

**Comment by peterix** [comment]
Honestly, that shold probably be a checkbox, because copying instances can be used in different contexts.

Like this:
* You are updating some mods
* You make a copy of the instance to do that in, because you don't want to mess up the current one
* It goes well and you delete the old version

Yes, you can mess with the old copy and not lose your play time stats, but the proposal here would make it something you can accidentally lose if you don't pay attention.

**Comment by peterix** [comment]
Implemented in develop.
