### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by xag803** [MultiMC/MultiMC5#2782]
System Information
-----------------------------
MultiMC version: 0.6.6

Operating System: win 32

Summary of the issue or suggestion: crash 
----------------------------------------------

What should happen: it should load 
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. I do not know

2.

3.

Suspected cause: n/a
---------------------------

Logs/Screenshots: [_**minecraft log**_](https://pastebin.com/AUm8cJW70)
                              [_**Crash log**_](https://pastebin.com/yZ9Ff0En)
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Janrupf** [comment]
You are having issues with the graphics driver. Please use the "Upload log" button next time so we have all information. For now try updating your drivers and using the approciate tool to tell it to force java to run on the GPU. (you can find more information about this online)

**Comment by xag803** [comment]
> You are having issues with the graphics driver. Please use the "Upload log" button next time so we have all the information. For now, try updating your drivers and using the appropriate tool to tell it to force Java to run on the GPU. (you can find more information about this online)

[https://paste.ee/p/PzfWz](I tried fixing java by reinstalling it before you said this hear is my upload log button link)

**Comment by peterix** [comment]
If you use an older integrated Intel GPU (HD2000, HD3000), you will have to use an older version of Java.

This should work:
* https://files.multimc.org/downloads/jre-8u51-windows-x64.zip (64-bit)

Download it, extract it into the MultiMC folder so it shows up like this:
![image](https://cloud.githubusercontent.com/assets/203326/24775694/31ee8d8a-1b1e-11e7-81d5-eff24add7de2.png)

Then set it up in MultiMc like this:
![image](https://cloud.githubusercontent.com/assets/203326/24775746/5c45fb22-1b1e-11e7-8615-e9ba6d667d7f.png)

Obviously only on Windows 10 :)

If you want the full background about this issue, see:
<details>
https://github.com/LWJGL/lwjgl/issues/119
https://github.com/MultiMC/MultiMC5/issues/1276 (and many other)

I tried contacting Intel about it, they said they will not fix their drivers because the hardware is unsupported on Windows 10:
http://www.intel.com/content/www/us/en/support/graphics-drivers/000005526.html
And Microsoft got an another person to boost their Windows 10 numbers, even though the hardware is not supported properly there.
</details>

**Comment by xag803** [comment]
[I ran DxDiag and this is what it gave me.](https://github.com/MultiMC/MultiMC5/files/3478691/DxDiag.txt)

**Comment by xag803** [comment]
thank you for your help I got it to work
