### ISSUE TITLE
[Usability/Feature] show library/mod dependencies

### ISSUE THREAD

**Issue by AngleWyrm10** [MultiMC/MultiMC5#2889]
After a while of adding/deleting mods to an instance, a bunch of orphaned libraries clutter the set.

---
MultiMC 5 version: 0.6.7.1375
Windows 10

**Comment by Heufneutje** [comment]
As far as I know MultiMC has no way to tell what depdencies a mod has.

**Comment by peterix** [comment]
This is not possible in the general, unreliable in the vast majority of cases, and basically would need a reliable source of this data.

This source does not exist.

**Comment by AngleWyrm10** [comment]
Just cause you don't know how does not make it impossible, or even difficult.
CurseForge does a fine job of listing dependencies, Twitch does it as well, the gradle framework downloads mod dependencies automatically, and I'm sure there are plenty others I don't know about.

**Comment by peterix** [comment]
It doesn't do a good job.

**Comment by Heufneutje** [comment]
The big difference here is that Twitch uses CurseForge and CurseForge has its own database of mods. Because mod devs manually specify which dependencies their mod has they make it work. Twitch does it because it uses CurseForge so same story there. MultiMC has no way of knowing what dependencies a random jar file you downloaded from the internet has.

Please refrain from telling people they don't know how things work when you don't even know what you're talking about.

**Comment by jikuja** [comment]
More points:
* Curse does not offer API to read dependency data 
* Current dependency data contain dependencies only for project level. No different dependency lists for different mod version.
* No proper way to have dependencies to some particular version range of the mod.

**Comment by Zetabite** [comment]
Also to consider is that even if only one version available some mods still dont have all dependencies listed. And iirc there is an api but you need to pay for it or something that isnt in favor of any non curseforge/twitch dev.
