### ISSUE TITLE
Can't extract native JAR, paired with inability to launch online.

### ISSUE THREAD

**Issue by SpongebobVEVO** [MultiMC/MultiMC5#2965]
System Information
-----------------------------
MultiMC version:
     0.6.7-1375

Operating System:
     Windows 10

Summary of the issue or suggestion:
----------------------------------------------
     This issue started with being unable to launch online, the program asking for an offline name, and an invalid session ID error if you went through with it. Then, it progressed to another error this time within MultiMC, stating that the JAR could not be extracted.

What should happen:
------------------------------
     The instance should launch and be able to join servers.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
I'm unsure if this is reproducable but what happened for us is:

1. I closed MultiMC last night, shut computer off.

2. This morning I woke up and tried starting Skyfactory 3, I was able to but when I tried to connect to a server I was told I had an invalid session ID.

3. I closed and restarted a few times, invalid ID repeatedly. I then restarted my computer to see if that would help.

4. I installed RL craft after restarting, to see if that would work.

4. After restarting and installing RLCraft, when I tried to launch RLCraft the unable to extract JAR issue occured. I've been unable to fix it from here.

Suspected cause:
---------------------------
     I'm unsure, but maybe something to do with restarting the computer while the invalid session ID error was occuring?

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
     
     https://paste.ee/p/dyW8t

Additional Info:
---------------------------
     The pack this started happening with was Skyfactory 3. I then installed RLCraft, and that is when the error begun to occur.

**Comment by Heufneutje** [comment]
Delete the libraries folder in your instance and try again.

**Comment by Sheldor5** [comment]
I have the same issue.

`Couldn't extract native jar 'D:/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar' to destination 'D:/MultiMC/MultiMC/instances/FTB Revelation [3.2.0]/natives'
Couldn't extract native jar 'D:/MultiMC/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar' to destination 'D:/MultiMC/MultiMC/instances/FTB Revelation [3.2.0]/natives'
`

This started **after I had to kill minecraft** because it was not responding (I am on Windows 10 if this helps).

The broken instance worked for over 4 months and after the forced kill it seems broken somehow ...

I tried deleting the libraries folder (MultiMC re-downloads everything fine) without luck.

**Comment by peterix** [comment]
If you still have this problem, ask for help on Discord.
