### ISSUE TITLE
Modpack crashing right away.

### ISSUE THREAD

**Issue by ImCogs** [MultiMC/MultiMC5#3008]
System Information
-----------------------------
MultiMC version: 0.6.8-1359

Operating System: osx

Summary of the issue or suggestion:
----------------------------------------------
I go to launch the instance for a modpack and it crashes right away.

What should happen:
------------------------------
Should launch normally

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch an instance

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/cFkiF

Additional Info:
---------------------------
MC.Eternal 1.3.2
am running java 8

**Comment by Zetabite** [comment]
How did you download eternal. Cause you need to download the zip (Not Server!) from curseforge and import with mmc

**Comment by ImCogs** [comment]
That's exactly what I did, I didn't download the server pack

**Comment by spannerman79** [comment]
`Instance update failed because: Game update failed: it was impossible to fetch the required libraries.`

Happens when you have blocked MultiMC from accessing the internet, you were offline during pack import of some sort of network based issue.

Suggest: Re-import the pack again (zip download) while online and have a **stable** internet connection.
