### ISSUE TITLE
minecraft crashes on launch through multi mc everytime without fail but runs from the regular laucnher fine

### ISSUE THREAD

**Issue by blockstasher** [MultiMC/MultiMC5#3087]
so im pretty new to modding in general and im just trying to get vanilla mc to launch from multi mc but i get this code -1 error or whatever everytime please help ive been stuck on this for a week

https://paste.ee/p/1t3Uh

**Comment by Gustavoserafim1** [comment]
isso ta acontecendo cmg  tambem e nao estou coseguindo resolver

**Comment by Janrupf** [comment]
Ok, so there are 2 issues here:
1. Looks like the MultiMC meta service is broken and doesn't supply `lwjgl-tinyfd`, however, thats not directly causing the crash
2. It looks like GLFW fails to create the window (this is the problem which is really causing the crash), but due to the fact that, that the real error is not visible, I can only guess.

Try following [this](https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java) guide. Also make sure your graphics drivers are up-to-date.

**Comment by Forkk** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
