### ISSUE TITLE
Minecraft 1.8.9 crashes when using forge, because "It was impossible to fetch the required libraries."

### ISSUE THREAD

**Issue by TheNanoMachi** [MultiMC/MultiMC5#3154]
System Information
-----------------------------
MultiMC version: MultiMC5-Version 0.6.11-1430

Operating System: Windows 10

Summary of the issue or suggestion: when trying to play 1.8.9 with Forge 11.15.1.1722, the game crashes because of the following error:
Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
----------------------------------------------

What should happen: The Game should load.
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create a new instance of 1.8.9 Minecraft, with forge installed.

2. Attempt to run said instance.

3. Game crash.

Suspected cause: Unsure, may be forge because vanilla 1.8.9 works fine.
---------------------------

Logs/Screenshots: https://paste.ee/p/gyhJ9
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by peterix** [comment]
Hmm... looks like forge people accidentally deleted some files.

**Comment by jvEhrlinger** [comment]
I'm experiencing the same issue, identical log excluding the instance name. For me, it's occurring on 1.7.10, with forge 10.13.4.1614.

**Comment by embeddedt** [comment]
I'm using Forge and MC 1.8.9 on Ubuntu 18.04 and I'm not seeing this problem. Maybe the issue is fixed?

**Comment by acrinym** [comment]
I'm using several different modpacks, several different forge versions. And it's 1.16, 1.16.5, 1.16.5RC1, 1.15.2, and others. 

@peterix I can download the file manually, 
[https://files.minecraftforge.net/maven/de/oceanlabs/mcp/mcp_config/1.15.2-20200515.085601/mcp_config-1.15.2-20200515.085601.zip](url)

but even when I place the file where MMC is looking for it (in this case, it's 
**MultiMC\libraries\de\oceanlabs\mcp\mcp_config\1.16.5-20210115.111550**  .  

Still, the instance fails to update. 

I'm on MMC 0.6.12-dev1500. 

Exact error is " Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance FTB Presents Direwolf20 1.16' failed to process:
https://files.minecraftforge.net/maven/de/oceanlabs/mcp/mcp_config/1.16.5-20210115.111550/mcp_config-1.16.5-20210115.111550.zip

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. @acrinym do you have an specific Forge version example? I was not able to reproduce this and if this was a widespread issue I feel like this would be reported all day. My only guess is there's an antivirus or something blocking those downloads? If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
