### ISSUE TITLE
Feature request: shared mods / cache / Downloads folder for curseforge packs

### ISSUE THREAD

**Issue by dlehman83** [MultiMC/MultiMC5#3159]
System Information
-----------------------------
Intel I7 16GB RAM
MultiMC version:
0.6.11
Operating System:
Windows 10
Summary of the issue or suggestion:
----------------------------------------------
I have a fairly slow DSL connection and many of the mods are the same between packs of the same Minecraft version. Also updating a pack, not all mods are updated.  
This is when downloading the zip version of a pack from curseforge / twitch using the import zip feature.  
Even if I import the same zip twice, it downloads all the mods again.  

What should happen:
------------------------------
I would like to see a central downloads folder for all the mods.  Once one pack has downloaded the mod, others can see the file already exists and use it.  
If MultiMC can point it at the one file we would save disk space as well and bandwidth.  However if it is just a downloaded mods cache and the mod is copied to the instance folder, that would be a big help

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download a zip modpack from curseforge 

2. import the pack

3. import the pack again or a similar pack, all the mods are downloaded again.  

Suspected cause:
---------------------------
Feature not developed / implemented yet

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by sambhavsaggi** [comment]
This would require some sort of version-checking of the mods downloaded. Curseforge does provide an MD5 sum for the files, and this could be used to check if you have the right version of the mod installed. Maybe something in their API could do this?

**Comment by kb-1000** [comment]
It could be used if MultiMC even knew which mod it was, and if some web scraping is done in the client. However, you can NOT find out which mod it is given an md5 sum, and do you really want to have it download every single mod page? In addition to that, adding web scraping in mmc is extremely unlikely from what I heard. The API does not help at all. And the MD5 sum field on downloads is sometimes even missing/not computed.

**Comment by sambhavsaggi** [comment]
MultiMC would know what mod it is: The Twitch modpacks have a manifest of all the mods in the pack. By using the manifest, MultiMC could create an association between the mod file and the MD5 sum, eliminating the need for getting the checksum from all of the results. However, we can use the project file ID instead of checksums. This would warrant some type of SQLite database (or something simpler) where files are associated with the file ID on Twitch. The API currently used in the Twitch download function in the Twitch search function has that capability. If we want to simplify further, just use filenames. If the filenames match, don't download and create a symbolic link (idk the equivalent in Windows). These solutions all have their flaws but in theory it may work.

**Comment by peterix** [comment]
No more will be done towards any sort of integration with Twitch.
