### ISSUE TITLE
Can you add a minecraft and forge download address from mainland China?

### ISSUE THREAD

**Issue by graytoowolf** [MultiMC/MultiMC5#3164]
Downloading official resources from mainland China users will be slow. Can you add the download address of the mirror source provided by mainland China? For example“ https://bmclapidoc.bangbang93.com/ "

**Comment by ZekerZhayard** [comment]
related to https://github.com/MultiMC/MultiMC5/issues/2246

**Comment by ZYLHL** [comment]
Due to the existence of the Great Firewall in China, many Chinese cannot easily and fast enough to get files about Minecraft. So, a Chinese developer made a mirror to help these Chinese get these files. MultiMC is the best third-party Minecraft launcher I have ever met, I hope more Chinese people could use MultiMC to play Minecraft and manage their instances.
So, mirror download source, please!
