### ISSUE TITLE
Recursively search fabric mods for additional mods stored jar in jar and display them on the modlist

### ISSUE THREAD

**Issue by i509VCB** [MultiMC/MultiMC5#3191]
Description:
Fabric's mod specification allows for mods to bundle additional dependencies/other mods within their jar. For sake of words, Jar in Jar = JIJ. Some mods do this for modularity (Fabric API being the main example).

The idea is to allow multimc to recursively scan the mod metadata (all fabric.mod.json files have their JIJ mods specified inside of a `jars` block). Then display in the mod list (likely as a tree of child mods for JIJ entries) all the bundled mods within each mod jar (as it's corresponding mod entry).

**Comment by peterix** [comment]
This really should not be supported in any way.

**Comment by TheMadHau5** [comment]
Why not? I don't see an issue with doing that, so maybe you could explain why you made that statement?

**Comment by Zetabite** [comment]
I wouldnt go recursively through them and display them, since thats ugly way to do it. There is a tool tho, that extracts those mods and cleans them up, so you would rather have this being done in MMC. But since this is prone to break at some point and many modders isnt to be trusted, MMC shouldnt bother with this, and you should use that script if you really need the mods to be cleaned and showed

**Comment by peterix** [comment]
Nah.
My reasoning is that this is a really stupid practice and should not be enabled. A mod is a file. You put it in the mods folder. It doesn't have multiple things inside.

That's it.
