### ISSUE TITLE
Failed to create an instance: Failed to fetch version list file

### ISSUE THREAD

**Issue by misamisk** [MultiMC/MultiMC5#3224]
System Information
-----------------------------
MultiMC version: 0.16.2-develop-1391, 0.16.1-13.70

Operating System: OSX 10.10 x64

Summary of the issue or suggestion:
----------------------------------------------
List update failed:
Job 'Download of meta file net.minecraft/index.json' failed to process:
https://meta.multimc.org/v1/net.minecraft/index.json

What should happen:
------------------------------
Minecraft version list should appear

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch MultiMC

2. Add your Mojang account

3. Click "Add Instance"

Logs/Screenshots:
----------------------------
![Screen Shot 2020-06-29 at 20 31 00](https://user-images.githubusercontent.com/42472132/86037680-6b5ead80-ba48-11ea-9ff6-61e789fb192d.png)
![Screen Shot 2020-06-29 at 20 36 42](https://user-images.githubusercontent.com/42472132/86037687-6dc10780-ba48-11ea-99c6-707de0c539e8.png)

Additional Info:
---------------------------
System Hardware:
Prozessor: Intel Core i5 2.4 GHz
Memory: 16GB 1600MHz DDR3
Graphics: Intel HD Graphics 3000 512 MB

**Comment by gemmasd** [comment]
Having a similar error on Windows 10. MultiMC 0.6.11-1430. 

![ListFetch](https://user-images.githubusercontent.com/67651869/86155707-d5bc3000-bad2-11ea-827e-b7a0df81043d.png)

I can't seem to create new instances, either. Attempts to download from version net.minecraft, but can't. Not sure what the issue is there, either.

I vaguely recall seeing something on MultiMC not being able to fetch Minecraft jars anymore because of something Microsoft did once acquiring the property? Not totally sure because I can't find it now, but IDK if it's a Minecraft thing and not a MultiMC thing.

**Comment by Zetabite** [comment]
its been a long time since Microsoft took over, so thats not it. There are possibilities of antivirus and internet provider blocking or corrupting the json data. First could be tested by disabling antivirus, second by VPN

**Comment by gemmasd** [comment]
> its been a long time since Microsoft took over, so thats not it. There are possibilities of antivirus and internet provider blocking or corrupting the json data. First could be tested by disabling antivirus, second by VPN

Yeah, fair enough. It's been a long time since I messed around with Minecraft. Trying to set it up for my younger sibling on their computer. Disabled Windows Firewall, had to install 64-bit Java and did a clean install of MultiMC (they apparently messed up the permissions in the directory it was installed.) 

It's working now!

**Comment by Zetabite** [comment]
Good to hear :)

**Comment by misamisk** [comment]
But in browser this link (https://meta.multimc.org/v1/net.minecraft/index.json) opens correctly.

**Comment by misamisk** [comment]
And I have disabled MacOS Firewall.

**Comment by misamisk** [comment]
I have launched MultiMC in terminal as sudo and here is log: https://pastebin.com/Yg9LxDgH

**Comment by Zetabite** [comment]
Could be your internet provider then, changing data when you download it via MMC and not browser, idk if you have a vpn around to test

**Comment by misamisk** [comment]
And now Mojang Services Status is red. Auth, Session, Skins and API is red.
![Screen Shot 2020-07-02 at 10 15 04](https://user-images.githubusercontent.com/42472132/86328084-eb556500-bc4c-11ea-9a9b-9483f76ce0c9.png)

**Comment by QuintBrit** [comment]
I had this problem before. Once I updated my OS and redownloaded MultiMC it was fine. Can you try that?
