### ISSUE TITLE
Proposal: "Install OptiFine" button.

### ISSUE THREAD

**Issue by Drison64** [MultiMC/MultiMC5#3342]
Hey!

I propose a "Install OptiFine" button.
I have made a working proof of concept, you can find the code here: https://github.com/Drison64/optifineExtractor
and a video showing it here: https://youtu.be/A98woAFzki8

OptiFine installer could be downloaded from my GitHub repository: https://github.com/Drison64/OptiFine-Archive.
Minecraft clients could be downloaded from original minecraft download links from json file from MultiMC/meta repository.

**Comment by Janrupf** [comment]
This would be a violation of the OptiFine license.

**Comment by Drison64** [comment]
Oh, where can i find it? I could not find it /shrug

**Comment by Drison64** [comment]
Ok, what about using Jsoup to connect to the download website and download it from there? That should not be violating OF license. amirite?
(Tested it, works)

**Comment by UltraBlackLinux** [comment]
**First of all:** 
Optifine wants you to go through their ad-heaven at any costs. Nomatter what you do, theyll propably only accept this feature if the user actively sees ads & gets tracked from, the OF website. And Im not a fan of MultiMC containing ads.
Ever wondered why OF uses encrypted link-parts (whatever)?

**(Propably) The first link you encounter (if you dont click on mirror):**
http://adfoc.us/serve/sitelinks/?id=475250&url=http://optifine.net/adloadx?f=OptiFine_1.16.1_HD_U_G2.jar&x=81fb
This is already a link shortener you can make money with.

**The second link:**
https://optifine.net/adloadx?f=OptiFine_1.16.2_HD_U_G3.jar
This link is litterally useless. If you change the OF version to e.g. OptiUnFine, the website will change the title of the download button, but it wont work then:
https://optifine.net/adloadx?f=OptiUnFine_1.16.2_HD_U_G3.jar
This essentially makes you unable to not see any ads, because this link is required 
for the next step:

**The Download Link:**
https://optifine.net/downloadx?f=OptiFine_1.16.2_HD_U_G3.jar&x=81fbd5138b6246a794712f5d45506c45
The last part (&x=81fbd5138b6246a794712f5d45506c45) makes the Request valid, and every download link has a different one, I wonder why. (If you dont get it, this is the way of the OF owner to prevent any automated downloads that somehow skip the OF ads)

**Comment by kb-1000** [comment]
> Forge is, tbh, not the best minecraft modloader anymore

that's your opinion.
There is no "best" modloader.
Also, Optifine will probably stick around, whether you believe it or not.

If peterix wanted, we could implement this through parsing the html of the second link, and then getting the third link from there. However I think that the Optifine owner would probably react to this, and not in a good way.

> what about using Jsoup

MultiMC is not written in Java.

**Comment by Drison64** [comment]
Hello!

OptiFine can be added to MultiMC instance by extracting it and then adding it there by clicking Add to Minecraft.jar.
This method does not need any modloader.

I know that MultiMC is not written in Java.
Since my code just downloads everything needed and extaracts optifine .jar mod file it could be just run from MultiMC and then MultiMC takes the file and adds it to the instance then removes created folders.

What could OptiFine owner do apart from making it impossible to get the Request token?

**Comment by QuImUfu** [comment]
Add a captcha?

**Comment by UltraBlackLinux** [comment]
captchas dont fix the see-ads thing

**Comment by QuImUfu** [comment]
But if we should automated parsing and downloading it is an efficient way to stop us (was an answer to "What could OptiFine owner do apart from making it impossible to get the Request token?")

**Comment by kb-1000** [comment]
Why are you even trying to discuss this

**Comment by QuImUfu** [comment]
Many people want an easy way to install OptiFine, @Drison64 made an suggestion for a AFAIK perfectly legal and currently possible solution and asked for an reason not to do it without the ok from OptiFines creator by asking what he could do against it. I answered. With that i only expanded on what you said: "I think that the Optifine owner would probably react to this, and not in a good way".  
My second comment was because i think @UltraBlackLinux missed the point of my first comment and i wanted to explain it better.  
Could you explain why not continuing this discussion would have been a better reaction?  

If the question was not meant as an criticism but an more philosophical question, then IMO the best answer is: To create a common understanding of the problem and to spread knowledge. :)

**Comment by kb-1000** [comment]
"not in a good way" can also mean many other things. Did you think about legal actions? About ```java
StringWriter sw;
new Exception().printStackTrace(new PrintWriter(sw));
if (sw.toString().containsIgnoreCase("MultiMC")) {
    throw new Exception();
}```?
I would believe them to behave like that.

**Comment by Drison64** [comment]
I think they could stop this by adding captcha.

> Did you think about legal actions?
What legal actions?
As far as i know my prototype is 100% legal.

**Comment by kb-1000** [comment]
Well, no:
![image](https://user-images.githubusercontent.com/18211838/93245189-37637080-f78b-11ea-8eaa-1d53ee23435b.png)
You may not redistribute it.

**Comment by peterix** [comment]
The sensible thing would be to add a way for metadata files to reference files without having a download URL, and then the launcher asking the users to provide the files (either directly, or by scanning a folder for them).

**Comment by Drison64** [comment]
@kb-1000 
Yea, that is not used. It is very old thing. I thought it is private. Gonna make it private.

**Comment by Drison64** [comment]
Hey, it got little quiet here.

Could we discuss this more? Or is this simply not happening?

> The sensible thing would be to add a way for metadata files to reference files without having a download URL, and then the launcher asking the users to provide the files (either directly, or by scanning a folder for them).

Yeah, this could be used. But in my opinion it is not as user-friendly as I imagined.

**Comment by Scotsguy** [comment]
Closing as wontfix, user-provided mods should be in a different issue.

**Comment by luckydonald** [comment]
If it's impossible to do automated, e.g. "please browse where optifine-download.jar is located" + unzip,
Could there at least be an installation guide? 

Been a while since I used minecraft, and the stock launcher at least works with optifine.

**Comment by phit** [comment]
check the wiki https://github.com/MultiMC/Launcher/wiki/MultiMC-and-OptiFine
or any of the countless tutorials out there

**Comment by luckydonald** [comment]
Thanks!
As I also wanted to use Fabric, I went ahead with the proposed alternative of switching to [Iris](https://curseforge.com/minecraft/mc-mods/irisshaders) and [Sodium](https://modrinth.com/mod/sodium) instead:
[Source: Optifine alternatives](https://lambdaurora.dev/optifine_alternatives/)  ([GitHub mirror](https://github.com/LambdAurora/optifine_alternatives))
