### ISSUE TITLE
Crashes when I try to load up minecraft

### ISSUE THREAD

**Issue by TPsquid** [MultiMC/MultiMC5#3362]
hello everyone, I am pretty new to using multimc to load modpacks into minecraft, so this might be a PEBKAC moment (problem exists between keyboard and chair) I have been trying to load modpacks. I am on minecraft 1.14.4 using forge 28.2.0 it loads all of the mods fine and opens minecraft to the forge loading screen, then it stops, saying "process exited with code 225." I don't know if this is a crash, something I am doing wrong, or both. I would appreciate any help, thank you!

Edit: I downloaded the correct java files and it loads up to the point where it gives the "freezing data" message, then it stops, it won't load anymore. The error is "exit code 9"

**Comment by giukio06** [comment]
you mean code 255?

**Comment by QuImUfu** [comment]
exit code 9... if you are using Linux possibly means the kernels OOM killer has reaped that process to free memory, because your system ran out of memory.  
However, you have given no information about your system, so that's just a guess. The issue template exists for a reason, please (at least) post a full log.
https://github.com/MultiMC/MultiMC5/wiki/Minecraft-Logs#uploading-logs

**Comment by Scotsguy** [comment]
This is not a MultiMC issue, closing.
