### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by calebmennen** [MultiMC/MultiMC5#340]
None of my instances have any sound in them. I tried creating a vanilla 1.6.4 instance, no sound. My best guess is that MMC isn't properly getting the files when it creates an instance. Note, only seen in 1.6.* packs, not sure if it is past those versions.

**Comment by peterix** [comment]
Odd.

The portion of the log shows a completely different issue than 'no sound'. It's more along the lines of 'the instance fails to update because the version file can't be read'.

After that, it would normally grab the MC assets - sound... and it doesn't. Anyway, in current MultiMC, this would just refuse to launch - therefore closing.
