### ISSUE TITLE
access all instances simultaneously like vrchat

### ISSUE THREAD

**Issue by allenwrench** [MultiMC/MultiMC5#3409]
System Information
-----------------------------
MultiMC version: latest

Operating System: windows 10

Summary of the issue or suggestion: being able to switch instances on the fly
----------------------------------------------

What should happen: like vr chat you enter a portal and you go to that instance
------------------------------

Steps to reproduce the issue (Add more if needed): uh using the spigot or bukkit to connect instances together then use a wrapper to stream multiple versions at the same time using viaversion or what now
-------------------------------------------------------------
1. bukkit

2. viaversion

3. wrapper

Suspected cause: not easily integrated
---------------------------

Logs/Screenshots: n/a
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info: multimc rocks!!!
---------------------------

**Comment by LordMZTE** [comment]
this is impossible in so many ways. what if you take items through the portal which the other instance doesnt have? what should happen when the player goes away from a singleplayer world? (that may cause crashes because thats not meant to happen) what if the portal is not loaded? how to know if theres even a portal? what if theres multiple portals? how do you even communicate between instances? there would have to be some sort of host instance in the background.

and even if this were do be done, it would be a mod's job and not for multimc to do

**Comment by peterix** [comment]
As a MultiMC feature? Never.

**Comment by peterix** [comment]
Sounds cool tho.
