### ISSUE TITLE
my multy mc crach whith the error code 255

### ISSUE THREAD

**Issue by BulgariaJones** [MultiMC/MultiMC5#3443]
System Information
-----------------------------
Multi-MC version:5

Operating System:Linux Mint 20 Cinnamon

Summary of the issue or suggestion:
----------------------------------------------
when i try to launch forge it´s work but then its close

Steps to reproduce the issue :
-------------------------------------------------------------
1. install forge

2.install creative-core & little-tiles

3.try to launch mmc

4.when it´s start crash

Suspected cause:
---------------------------
i think creative-core and little-tiles not work together but little-tiles needs creative-core

Additional Info:
---------------------------
i use forge15.23.5.2852

**Comment by TheGayInThewather** [comment]
sorry forge14.23.5.2852

**Comment by Janrupf** [comment]
![image](https://user-images.githubusercontent.com/25827180/99157920-8cf5c400-26cd-11eb-964c-3dc7ea1e5b53.png)

**Comment by mylesbartlett72** [comment]
Nobody can help you with this issue with only an error code (especially a common one like 255), you should supply:
Crash log
FULL mod list, including Forge and/or LiteLoader or Fabric and/or other mod loaders, preferably with download links from the websites you got the mods from.
Minecraft version
Mod(s) version(s)

Also, if you think there is an issue with littletiles and creativecore creating a conflict, you should open a bug report for littletiles, NOT MultiMC.

The developers hate issues like yours, because they simply cannot be fixed.  Please, anyone who is thinking of opening an issue on any bug tracker, **don't do it like this**!  An example of a good issue is #3413.

Finally, make sure you got your mods from the official sites.  For most (including littletiles and creativecore) this is Minecraft Curseforge, however some developers such as _cough_ MrCrayfish may distribute them from their own sites.  If you are not sure about this, [click here.](https://stopmodreposts.org/)  Some mod repost sites may offer mods for versions that they do not support, to provide malware (you may have not heard this term, it is the proper name for computer viruses, which are actually a subset of malware).  

P.S. you can edit comments on Github, say when you wrote your forge version number and had to correct it, you could have edited your original comment.  However, you seem new, so i'll let it slide.

**Comment by peterix** [comment]
Nobody here is interested in crash logs. Please simply follow what @Janrupf posted.

**Comment by BulgariaJones** [comment]
ok
https://paste.ee/p/CQqdp

**Comment by BulgariaJones** [comment]
https://paste.ee/p/Y9Rol

**Comment by Zetabite** [comment]
where did you get the mods from?

**Comment by phit** [comment]
as mylesbartlett72 said, download the mods from their official source
https://www.curseforge.com/minecraft/mc-mods/creativecore/files
https://www.curseforge.com/minecraft/mc-mods/littletiles/files

wherever you got these mods from is not the official source and is most likely ancient and broken
