### ISSUE TITLE
Certain vanilla versions aren't obtainable

### ISSUE THREAD

**Issue by BlueManedHawk** [MultiMC/MultiMC5#3472]
System Information
-----------------------------
MultiMC version:
0.6.12-develop-1401
Operating System:
GalliumOS 3.1
Summary of the issue or suggestion:
----------------------------------------------
There are several vanilla versions of the game which cannot be obtained through the regular interface for installing vanilla versions, mostly old Indev and Infdev versions.

What should happen:
------------------------------
These old versions should appear.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.  Open the Vanilla tab of New Instance and see that these old versions aren't there.

2.

3.

Suspected cause:
---------------------------
I'm assuming this is because MultiMC grabs these versions from the regular Minecraft launcher, or whatever that grabs them from.  However, that doesn't explain the existence of Minecraft 4K.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------
While there are some of these versions that are lost ( :,-( ), others have download links accessible through the Wiki.

**Comment by peterix** [comment]
These are fundamentally broken and have been filtered out on purpose.

**Comment by BlueManedHawk** [comment]
I'm not quite sure what you mean by "fundamentally broken".  Additionally, the fact that Mojang Studios doesn't ship them shouldn't be a reason for MultiMC not shipping them, as many people may want to play these versions.

**Comment by Zetabite** [comment]
Ya know, MMC cant ship those versions, since there is no good archive to access them from, Additionaly for legal reasons

**Comment by BlueManedHawk** [comment]
What do you mean "there's no good archive"?  There's the Minecraft Wiki.  Additionally, what does "legal reasons" mean in this context?

**Comment by jotoho** [comment]
> What do you mean "there's no good archive"? There's the Minecraft Wiki. Additionally, what does "legal reasons" mean in this context?

I think that "legal reasons" means copyright in this case. Unless Mojang has given explicit permission otherwise, I imagine that MultiMC is only legally allowed to get game files directly from the official mojang servers, since Mojang obviously holds the copyright to the game.

Buyers of Minecraft Java Edition only really buy a license to download and use Minecraft Java Edition under the license terms dictated by mojang. I do not know the contents of the license agreement but until proven otherwise I would suspect that redistributing the game files - even only to other license owners - is prohibited. 

(That Minecraft Wiki is providing file downloads to some versions of minecraft is their risk and just because Mojang isn't doing anything about it does not mean Launchers like MultiMC can do as they please. Note that the Forge Installer for example also downloads the game files directly from mojang last I checked.)

**Comment by BlueManedHawk** [comment]
Damn.  I suppose that it should be checked wherther it's legal to use those files.

**Comment by Zetabite** [comment]
Peterix works at mojang....

**Comment by BlueManedHawk** [comment]
I still think that if it's possible to legally put these versions in, it should be done.
