### ISSUE TITLE
Can't connect to realms with MultiMC instance

### ISSUE THREAD

**Issue by DownLoude** [MultiMC/MultiMC5#3498]
System Information
-----------------------------
MultiMC version: 0.6.11

Operating System: Windows 10

Summary of the issue or suggestion: 
----------------------------------------------
When I launch with MultiMC, I cannot connect to a realm, I stay on the loading screen indefinitely.

What should happen: 
------------------------------
I should connect to the realm and play

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch an instance with MultiMC

2. Go to minecraft realms

3. Select and connect to a realm

4. The game will stay on the loading screen

Suspected cause: 
---------------------------
MultiMC not supporting realms?

Logs/Screenshots:
----------------------------
Imgur seems to not want to work, but its literally just a picture of realms loading

Additional Info:
---------------------------
I did originally launch with forge, after suspecting this to be the cause, I tried with forge updated, without any mods, without forge, still to no avail. Launching directly from the MC launcher with forge did work however. Forge is not the cause.

**Comment by Zetabite** [comment]
https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png

**Comment by VoxelTek** [comment]
Hi there,
Could you:
1. Provide the Minecraft version number you are attempting to use to connect to realms.
2. Attempt to access realms under similar or identical conditions, but using the official MC launcher.
3. Create a completely new and clean install, and attempt to reproduce the issue.

**Comment by DownLoude** [comment]
Minecraft Info:
-----------------------------
Version: 1.16.4

Log:
-------------
https://paste.ee/p/2yWVx

Additional Info:
-----------------------------
I launched Minecraft under identical conditions, with forge + mods, only forge, and vanilla in both official launcher and MultiMC, consistently being unable to connect to realms in the MultiMC instances. With a new install of the instance the MultiMC still seems to fail.

**Comment by jotoho** [comment]
Are you able to connect to other (non-realm, non-offline-mode) minecraft servers? Knowing this may be useful to figure out if this is realms-specific.

**Comment by Zetabite** [comment]
You have MMC in OneDrive folder. This breaks MMC cause OneDrive does stuff. Move it out of the OneDrive folder structure and see what happens.

**Comment by DownLoude** [comment]
Ok, it seems that completely removing and reinstalling MultiMC has solved the issue. I'm very sorry for the unnecessary trouble I've caused, but thank you very much.

**Comment by Zetabite** [comment]
If you havent yet, move it outside the OneDrive folder structure

**Comment by DownLoude** [comment]
I have MultiMC inside of onedrive so that I can easily transfer worlds and data between computers, that's why I use MultiMC.

**Comment by Zetabite** [comment]
MMC doesnt work properly inside OneDrive, please move it out of there

**Comment by VoxelTek** [comment]
This issue should be closed lol

**Comment by youngchief-btw** [comment]
Just make copies (automated or not) to OneDrive if you really want to have it for backups.

**Comment by spannerman79** [comment]
> Just make copies (automated or not) to OneDrive if you really want to have it for backups.



I doubt that the user would do that @youngchief-btw simply for the fact that the sole intention of the OP was to " so that I can easily transfer worlds and data between computers".


OneDrive **does not** Shadowcopy.  OneDrive (non-business) sole intent was focused around making sure that documents were backed up.  Typically when any sort of application edits a document it doesn't write back to it intermittantly now and then (like what minecraft does to its storage system does of regions/player data etc) under the same file name.  It creates a temp file somewhere - sometimes in the same directory that the originally opened document is located with a different name *eg `~temp_orginal-document-name.ext` or in the system's temp file location.


**Only** when the user has stopped editing changes does it attempt to actually replace the file - not append the file contents.  This is how word processors operate generally (MS Word, libre/open office etc).

**Comment by youngchief-btw** [comment]
I was saying that because OneDrive has an API available. So if they really wanted to use OneDrive for that they could (with technical knowledge)
