### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by CouchMilk** [MultiMC/MultiMC5#3512]
https://paste.ee/p/oiEvS
i dont understand what i did wrong

**Comment by CouchMilk** [comment]
help

**Comment by jotoho** [comment]
Does not seem like a MultiMC issue.

The crash occurs because the game cannot find a class in a subdirectory of `shadersmod`. Does this crash still occur without Optifine? Try removing it from fabric's mods folder.

Disclaimer: I have never really used Fabric before and this is just my best guess. The hard-to-read modlist in the log doesn't make it easier either.

**Comment by spannerman79** [comment]
> Minecraft folder is:
C:/Users/atle_/**OneDrive**/Skrivebord/MultiMC/instances/mc 1.16.4/.minecraft

Move MultiMC out of a onedrive monitored directory. 

OneDrive does **not** shadow copy and you **will** have issues.

Secondly - this issue would have been better addressed on and discord server.  This isn't a MultiMC issue.

**Comment by CouchMilk** [comment]
> > Minecraft folder is:
> > C:/Users/atle_/**OneDrive**/Skrivebord/MultiMC/instances/mc 1.16.4/.minecraft
> 
> Move MultiMC out of a onedrive monitored directory.
> 
> OneDrive does **not** shadow copy and you **will** have issues.
> 
> Secondly - this issue would have been better addressed on and discord server. This isn't a MultiMC issue.

okay thanks i dident know
