### ISSUE TITLE
crashed with exitcode -1073741819

### ISSUE THREAD

**Issue by Lboyboy** [MultiMC/MultiMC5#3527]
<!--
I was trying to make a cool modpack and when i tried to launch it, it Sayed this: process crashed with exitcode -1073741819 I dont know how to fix this and am new to this kind of stuff so if someone could tell me what's wrong that would be great.

**Comment by jotoho** [comment]
The issue template you deleted was there for a reason. And not only to hide rest of the description when you failed to delete it properly.

Since this is almost certainly not an issue with MultiMC but with your modded setup, you should go to the MultiMC Discord for help or at least follow the instructions in the template such as uploading the log.

**Comment by Lboyboy** [comment]
ok thanks for the help :D

**Comment by Zetabite** [comment]
please provide the full log: https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png
