### ISSUE TITLE
Code 255 MultiMC 1.6.4

### ISSUE THREAD

**Issue by ninjatwinkie1** [MultiMC/MultiMC5#3528]
I am on Manjaro Linux

console log: https://paste.ee/p/Yz6dj

edit: put in the right console log
edit: is there supposed to be a template?

**Comment by TreyRuffy** [comment]
This does not look like a problem with MultiMC. The problem looks to be that bspkrsCore cannot get the latest version for the files because the game is so old. The fix is to open the configuration file for the mod (right-click on the instance and click config folder) open the `bspkrsCore.cfg` file and change `B:allowUpdateCheck=true` to `B:allowUpdateCheck=false`.
