### ISSUE TITLE
Code 255

### ISSUE THREAD

**Issue by ninjatwinkie1** [MultiMC/MultiMC5#3559]
Operating System: 
Manjaro Linux

What should happen:
Launch Minecraft

Suspected cause:
No idea

Logs/Screenshots:
https://paste.ee/p/zH67a

Additional Info:
I had a problem with the same instance of MultiMC then instead of giving me code 6 now I am getting code 255

**Comment by jotoho** [comment]
Related to #3558

Non-zero exit codes just mean that the process ended with an error or the command in question was unsuccessful. The fact that the number changed may not mean anything.

The log did change though, so that's good. Seems to me like there are some mod dependencies that aren't met. I don't know if I'm reading the log correctly but may need to update forge.

**Comment by ninjatwinkie1** [comment]
I updated forge and I got exit code 6
https://paste.ee/p/8CB3b

**Comment by phit** [comment]
use the proper nvidia drivers if you wanna play video games, the nouveau drivers are neat, but not stable enough for video games

**Comment by spannerman79** [comment]
This is **not** a MultiMC issue.

MultiMC issues are for actual issues with MultiMC. Not with an incorrect version of Forge running with mods.  You would get the **exact** same issue if you did this with the vanilla launcher - hence not a MultiMC issue.

----

Take a moment to actually look at your log @ninjatwinkie1 .  Search for "Unable to parse dependency string required" (should be ~ 10 results) and compare to the version number it asks ( ie forge@[**14.23.5.2836**,) ) and look at the version of forge you have added (ie MinecraftForge v**14.23.0.2486** Initialized )
