### ISSUE TITLE
Smaller footprint of console window

### ISSUE THREAD

**Issue by Ozzymud** [MultiMC/MultiMC5#358]
Is there anyway we can get a smaller console window? With maybe icons only(collapsable) and a horizontal scroll bar in the log area? I don't know what's easily feasible, but the horizontal scroll in log would help greatly. Really love it besides the size, as well as the new instance properties window... gg :)

![mmc_console](https://cloud.githubusercontent.com/assets/6426344/3560623/4d71ffda-097c-11e4-8a18-ea537d0c2ecf.png)

**Comment by peterix** [comment]
Moved to workflowy (Ideas -> Instance window):
https://workflowy.com/s/2EyDMcp7CU

**Comment by Rencer** [comment]
MultiMC version: 0.6.5-custom (Build from AUR)
Operating System: 64 bit Manjaro Linux 

Can I ask, in which version, this 5 years old issue will be finally fixed?
About a years ago I opened the #2330 issue, and I really disappointed that this issue is still in the latest version.It just be much better if the affected windows can be resized...

**Comment by DeltaNedas** [comment]
Also have this issue, same platform and laptop screen size. Please let us resize the console window.

**Comment by peterix** [comment]
Try the new develop build. It should have the vertical size issue resolved to some extent.

**Comment by DeltaNedas** [comment]
yep ty its fixed and all buttons are unobscured

**Comment by peterix** [comment]
I'm going to call this done, because this is as far as I'm OK with going.
