### ISSUE TITLE
[Bug] Unable to start Minecraft with AdoptOpenJDK HotSpot JRE 15.0.1.9

### ISSUE THREAD

**Issue by Monniasza** [MultiMC/MultiMC5#3609]
System Information
-----------------------------
MultiMC version: 0.6.12-develop-1520

Operating System: Windows 10 64-bit

Summary of the issue or suggestion:
----------------------------------------------
Unable to start Minecraft with AdoptOpenJDK HotSpot JRE 15.x.x.x

What should happen:
------------------------------
Minecraft starts up normally

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install [AdoptOpenJDK HotSpot JRE 15](https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15.0.2%2B7/OpenJDK15U-jre_x64_windows_hotspot_15.0.2_7.msi)

2. Change MultiMC Java executable to AdoptOpenJDK HotSpot JRE 15

3. Run any Minecraft instance

Suspected cause:
---------------------------
bug in AdoptOpenJDK class loader

Logs/Screenshots:
----------------------------
[log](https://paste.ee/p/VomMz)

**Comment by kb-1000** [comment]
If this was a bug in OpenJDK's ClassLoader, you should've reported it there. It isn't, though. That's an issue with launchwrapper, an outdated piece of software written by cpw that's hacking into java internals. Use java 8.

**Comment by Monniasza** [comment]
The similar issue occurs even in newer Minecraft Forge and Fabric versions, using the same MultiMC and Java version

**Comment by phit** [comment]
yes modded Minecraft does not support Java 15 no matter what combination you will try, use Java 8

**Comment by kb-1000** [comment]
Fabric does support Java 15, and the newest Forge version do as well. This is not a bug with MultiMC either.

**Comment by AverageComet250** [comment]
Can this be closed?

There are hundreds off issues here on multimc complaining about there Minecraft not working when they Use java 15 instead of java 8. 

THIS IS NOT A MULTIMC ISSUE.

Maybe try looking in the wiki and see if anyone's had a similar issue before creating an issue here. There are LOADS of issues about this. Also the reason you didn't see this when you used the official launcher is cause mojang was smart enough to realise that their issue tracker wouldn't be spammed with dumb errors if they made the official launcher use java 8 unless the user messed with the settings of their instances. This is why the official launcher ships with its own java, based off oracle java 8 (or openjdk 8 it doesn't really matter)

**Comment by peterix** [comment]
Yes, Use java 8.
