### ISSUE TITLE
"internal server error" 

### ISSUE THREAD

**Issue by Nathanstraight** [MultiMC/MultiMC5#3624]
Everytime i want to join this minecraft server it keeps saying "internal server error" i've checked the mods in a singleplayer world but it works. Idk why is it showing me this error. Ive downloadded java, reinstalled multimc and the mods, pls help :p

**Comment by Chaoschaot232** [comment]
This looks more ike a problem with the server you are trying to connect to instead of MMC problem.
MMC does only allows you to have multiple instances with different or same versions of mc + forge/fabric/... and some different java settings per instance but it does nothing related to a server.

Also testing it in single player is not the way to found the solution for your main problem. You should ask other player from the server if they have the same or similar issue and if so, try to talk to the server admins to resolve this problem. Maybe restarting the multiplayer server solves it.

**Comment by wb1016** [comment]
unrelated issue.
should be closed.

**Comment by Forkk** [comment]
This does not sound like a problem with MultiMC. If you're still having issues, someone on our [discord](https://discord.gg/multimc) may be able to help .
