### ISSUE TITLE
I can't add an account !!!

### ISSUE THREAD

**Issue by Tigrao123** [MultiMC/MultiMC5#3631]
MultiMc 5
Windows 10

When I go to add an account, I put my data, but the error. He asks for mojang account, but I have minecraft recently and I signed up with a microsoft account I tried everything):

**Comment by second2050** [comment]
MultiMC currently does not support Microsoft accounts.
[MultiMC.org > About Microsoft accounts](https://multimc.org/posts/microsoft-accounts.html)

**Comment by Tigrao123** [comment]
But how do I create a mojang account, I don't know.

**Comment by second2050** [comment]
> But how do I create a mojang account, I don't know.

Short Answer: You can't.

Long Answer: Because Mojang is switching their account system to Microsoft they require new accounts to be Microsoft accounts and everyone who's currently using an **old** Mojang account will slowly need to migrate to a Microsoft account.

You are therefore currently unable to use MultiMC as Microsoft accounts are currently not implemented, so you need to wait until someone implements Microsoft accounts in MultiMC.

**Comment by Tigrao123** [comment]
Ok, thanks

**Comment by kb-1000** [comment]
> and everyone who's currently using an old Mojang account will slowly need to migrate to a Microsoft account.

As far as I know, the actual migration has not started yet. This only applies to new accounts.

**Comment by Tigrao123** [comment]
):I'm mad at microsoft

**Comment by AverageComet250** [comment]
We all are. I'm pretty sure Microsoft just expects people to migrate to their oauth2 system, however most people are waiting to see if mojang creates a new method or makes it official. Launchers (including MultiMC) may use this as a last resort if mojang starts migrating accounts before an official method is declared.

**Comment by wb1016** [comment]
this wont be solved until MS release login API. should be closed.
