### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by kakakakuts** [MultiMC/MultiMC5#3650]
System Information
-----------------------------  GeForce GTX 650, Intel pentium G2020, 8GB of ram 64 Bit system.
MultiMC version:
0.6.11-1430
Operating System:
Windows 10 20H2
Summary of the issue or suggestion:
----------------------------------------------
Game crashes about 4h of gaming. Error Code: -805306369

What should happen:
------------------------------
Game should run correctly without any crashes

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. None

2. None

3. None

Suspected cause:
---------------------------
I   don't know.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by phit** [comment]
please add your log as requested by the issue template

![grafik](https://user-images.githubusercontent.com/2097483/110469869-74754380-80da-11eb-9a8b-0684e0262727.png)

**Comment by Forkk** [comment]
This issue is being closed for non-response

I'm about 90% sure you have a memory leak here, but I have no way to know for sure without seeing your log. The log is not optional. Please do not leave it out next time.

If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
