### ISSUE TITLE
Memory Leak leading to PC crash

### ISSUE THREAD

**Issue by 1980s-housewife** [MultiMC/MultiMC5#3655]
System Information
-----------------------------
MultiMC version:
0.6.12

Operating System:
Manjaro Linux
Summary of the issue or suggestion:
----------------------------------------------
Not sure if this is a Java or MultiMC error, but I've seen this exact issue on here before (https://github.com/MultiMC/MultiMC5/issues/1740) and its happening to me, essentially I have loads of processes of minecraft running for some reason, and they start consuming loads and loads of memory and eventually will crash my PC because there is no RAM left to use.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
Not sure, just open minecraft and play for like 20 minutes?

Suspected cause:
---------------------------
Java or Something to do with multimc, no clue

Logs/Screenshots:
----------------------------
![image_2021-03-11_19-57-22](https://user-images.githubusercontent.com/17932849/111025531-a3423100-83dc-11eb-8f7c-a920cc828218.png)

Additional Info:
---------------------------
I've tried using a JVM argument to reduce the amount of threads, and that did absolutely nothing to help

**Comment by radiomike** [comment]
Doesn't look like anything is actually wrong here. Minecraft and java will use lots of threads. Minecraft and java will also use lots of memory, how much will depend on the modpack and your java arguments. 

Something useful in htop, if you go into the settings, then you can set 'show custom thread names' under display options. This will then show you the threads with the names associated with them, rather than the process name. I find this view helpful and quite informative. You can also disable the display of threads,in which case htop will only show the base process.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
