### ISSUE TITLE
Import instances and modpacks (for example from zip files)

### ISSUE THREAD

**Issue by P1-Kashwak** [MultiMC/MultiMC5#366]
It would be great to be able to import a modpack/instance. This would make it easier for modpack dev teams to work together and be able to share the same modpack.

**Comment by DusteDdk** [comment]
I'd like to add my 5 cents, as I was going to add a feature request, but searched if anyone already suggested something similar.
Instead of a zip, it'd be kind of neat if one could create modpack lists instead, something like a simple text or json file that listed urls (and associated hashes for the packages)  for the mods, and (optional) payloads, like config files.

The format might look like:
modUrl: http://thatsite.tld/path/to/mymod.zip 3b5fee5885515fa6fd5034242034ecdd
modUrl: http://thatsite.tld/path/to/mymod.zip 3b5fee5885515fa6fd5034242034ecdd
modUrl: http://thatsite.tld/path/to/mymod.zip 3b5fee5885515fa6fd5034242034ecdd
confUrl: http://thatsite.tld/path/to/mymod.conf 3b5fee5885515fa6fd5034242034ecdd
AND OR
confTxt: forge.cfg "Some
text
here"
AND OR 
confTxt: forge.cfg "some\nText\nhere"

One could then under under the edit instance tab, click "add modpack" where one could either browse for the txt file, or simply copy/paste it into a text window (for easier distribution of modpacks via forums without the need for external filehosts).

Additionally, one could add parameters like:
updateCheck: http://thatsite.tld/path/to/mymod.version
version: 0.1
and MMC could automatically check and ask if you want to update.

Another great thing about modlists is that they'd work well with git.

I believe I'd be qualified to implement such a feature, let me know what you think.

**Comment by Loetkolben** [comment]
@DusteDdk As jar as I've understood QuickMods, it does similar things and @02JanDal has already a specification for it (https://02jandal.github.io/QuickModDoc/qm_spec.html). However, I'm not sure what the current state of implementaion is? jan?

**Comment by DusteDdk** [comment]
@Loetkolben ah, I see! In that case, it will be interesting to see if anything comes up :)
