### ISSUE TITLE
Crashing when loading a resourcepack

### ISSUE THREAD

**Issue by BMAB2012** [MultiMC/MultiMC5#3834]
Minecraft crashes some time after loading a vanilla tweaks resource pack. The problem does not happen in the official launcher.
[hs_err_pid14120.log](https://github.com/MultiMC/MultiMC5/files/6594270/hs_err_pid14120.log)
[VT.zip](https://github.com/MultiMC/MultiMC5/files/6594272/VT.zip)

What could it be? Ty!

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your game, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by BMAB2012** [comment]
I believe it is a MultiMC issue becouse it only happens in this launcher. As I mentioned, it does not happen in the official minecraft launcher.

**Comment by BMAB2012** [comment]
I've tried disabling the "Dynamic FPS" mod and the issue stopped. It's just weird how the mod only works with the official launcher.

**Comment by AverageComet250** [comment]
The reason it works in the official launcher but not in MMC is because the official launcher has its own java that it uses. MMC is using your installed java, and it's a slightly different version from the one that came with the mojang launcher. Make MMC use the bundled official launcher java, and it should work

**Comment by BMAB2012** [comment]
Nice! It works now! Ty!
