### ISSUE TITLE
Each Instance with Forge Crashes with 255... But only if it has Forge

### ISSUE THREAD

**Issue by Terandox** [MultiMC/MultiMC5#3847]
### Description of bug

Each time i start any minecraft instance, it crashes with code 255... even conpletly new instances.

I have java 8 installed and its selected in the options: https://drive.google.com/file/d/1rxuCU7jBLjHcip4Gz3wEnv37vHwtus2b/view?usp=sharing

I tried every java instance that is listet in multimc but it crashes every time.

Vanilla works normaly

### Steps to reproduce

1. Pressing start
2. Screaming at the Crashreport

Crash Report: https://pastebin.com/W6T7S22Q

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

----------------------------------------------------------------------------------------------------------------------------------

Yesterday it worked normaly....
What i changed? I restarted my pc. thats it...

---------------------------------------------------------------------------------------------------------------------------------

I tried a few things and noticed, that the original minecraft launcher starts forge with no problems... (it took 1 second)
Multi MC doesn`t

**Comment by Xetaxheb** [comment]
Looks like the issue is `[15:53:45] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: Caused by: java.lang.UnsatisfiedLinkError: Failed to dynamically load library: /home/terandox/MultiMC/bin/instances/Ihh Rüdepisse/natives/libglfw.so(error = /home/terandox/MultiMC/bin/instances/Ihh Rüdepisse/natives/libglfw.so: Kann die Shared-Object-Datei nicht Ã¶ffnen: Datei oder Verzeichnis nicht gefunden)`

google translated means 

`[15:53:45] [main / INFO] [STDERR /]: [org.multimc.onesix.OneSixLauncher: launchWithMainClass: 200]: Caused by: java.lang.UnsatisfiedLinkError: Failed to dynamically load library: / home / terandox / MultiMC / bin / instances / Ihh Rüdepisse / natives / libglfw.so (error = / home / terandox / MultiMC / bin / instances / Ihh Rüdepisse / natives / libglfw.so: Cannot open the shared object file: File or directory not found) `

Looks like an issue with java and your specific os (linux distribution).. please edit to include instead of "no response"


Some links maybe useful for someone familiar with setting up java on linux:

https://stackoverflow.com/questions/38934607/lwjgl-failed-to-load-a-library

https://gist.github.com/moaxcp/2410aafb4b67733676d74e8bf6d0a96b

https://github.com/oakes/Paravim/issues/1

**Comment by spannerman79** [comment]
I've only seen this issue when a kernel mode driver or there has been a kernel update happen and the end user didn't simply restart their system.

Seeing as this issue is two days old now, an update @Terandox ?

Without knowning your distro trying to pin point any sort of issue is going to be very difficult - as right now trying to even attempt to reproduce or find any sort of solutions is going to be like trying to find a needle in the haystack.

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
