### ISSUE TITLE
MultiMC suddenly deleted all mods, versions and, worlds, and detects 64-bit java as 32-bit.

### ISSUE THREAD

**Issue by itschews** [MultiMC/MultiMC5#3954]
OS
macOS 11
m1 mac air

Bug
MultiMC detects 1000% confirmed 64-bit arm java 16  as 32 bit java

I used a method [here](https://github.com/r58Playz/m1-multimc-hack) to get it running natively on m1 and this just happened suddenly.

I tried to use x86 java and now the 64 32 bit error is gone but this shows up.

_Instance update failed because: Null jar is specified in the metadata, aborting._

PS: The main problem is the missing world. Is there a directory I can find to get it back? Ive checked the instance/.minecraft/saves but they are missing.

**Comment by kb-1000** [comment]
ARM is not supported. That being said, it deleting all worlds/saves should not happen. I'd guess it's a bug in that wrapper script you used.
Since there are several ARM and M1 support issues open already, and this doesn't seem to be a MultiMC issue (or is in any currently supported environment), closing.
