### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by StarfireSky** [MultiMC/MultiMC5#3966]
### Operating System

Windows

### Description of bug

I get no report I have try to load multimc dozen of times both with and without mods and vanilla version and it keeps crashing. I try to play 1.17.1 and it just wont load it crashes and I get no log. What is going on.

### Steps to reproduce

Just load the game and it will crash on the 1.17.1.

### Suspected cause

I don't know what is going on.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by StarfireSky** [comment]
no I even try the vanilla minecraft through the multimc and it still crashes.

**Comment by jotoho** [comment]
@StarfireSky This really does not sound like a MultiMC problem. It's more likely for there to be some difference between Vanilla in the official launcher and the vanilla instance you're running in MultiMC that you don't know about. Like differences between the Java versions used, for example.

Just do as you're told and ask on the Discord or go somewhere else. Throwing a temper tantrum on a developer issue tracker is far more likely to get you reported or banned than getting you what you want.

Remember: You want something (game support) from the MultiMC community. Not the other way around. So you have to play by the rules or you'll just drive away the nice people who would otherwise help you.
