### ISSUE TITLE
Implement a mod manager (based of/by implementing Modsman)

### ISSUE THREAD

**Issue by LeSnake04** [MultiMC/MultiMC5#3969]
There is a great tool named Modsman, which allows the users to install/upgrade mods. I think implementing this program or something similar / based on this could make this program a lot better

https://github.com/sargunv/modsman

**Comment by spannerman79** [comment]
It doesn't need to be added.

https://github.com/sargunv/modsman#initialize-modsman

> Initialize Modsman
> cd .minecraft/mods

To find the path to the instance loader mods there are two ways - either via GUI ( clicking on view folder button in https://github.com/MultiMC/MultiMC5/wiki/Loader-mods ).  From there it depends on your OS on how easily you can directly open a command line interface/console. I won't go into detail on this as its pretty easy to figure that part out on your own.

Or knowing what you called the instance and look under `/path/to/multimc/instances/instancename/.minecraft/mods` - this is known by those that use multimc direct via scripting to launch instances.

Also;

> A mod manager for Minecraft. It can download, manage, and update mods and resource packs from CurseForge, as **well as inflate MultiMC modpacks by downloading mods on first run**.

MultiMC already obtains the mods from curseforge and "inflate MultiMC modpacks by downloading mods on first run"

-------

If this is to be added it should be placed under External Tools ( https://github.com/MultiMC/MultiMC5/wiki/Tools ).


Also it is to be noted if this is to be seriously added it would be recommended that the dev/s join the MultiMC discord so that peterix doesn't have to chase after the dev/s if there is any issues that may arise from this.

**Comment by LeSnake04** [comment]
1. I know that I can just use the command on the mod folder of this instance and can, but it would be cool if multimc would automatically iniziallize and let the user update/install mods per button

2. It would be even better if the MultiMC devs found a way to make a own mod manager based of the already implemented modpack magager. Maybe they can use Modsman as an inspiration and make similar calls or a similar structure to make it easier

3. Sorry about the possible dublicate.
But the situation/knowledge changed since the other was closed, since we now know making a mod manager is defiantly possible!

**Comment by Janrupf** [comment]
I've looked at the source of modsman, I don't think its the solution we want to have in MultiMC. There have been (and will be) discussions on how properly implement mods discovery and update support, which involves a whole infrastructure and other things. 

While modsman is in concept partially whats wanted, it doesn't look feasible to integrate into MultiMC.

**Comment by peterix** [comment]
No.

**Comment by LeSnake04** [comment]
Maybe take a look in the the GD Launcher source code, they have a great mod manager and updater:

https://github.com/gorilla-devs/GDLauncher
