### ISSUE TITLE
MSA login: XBox user authentication failed

### ISSUE THREAD

**Issue by T41US** [MultiMC/MultiMC5#4014]
### Operating System

macOS

### Description of bug

When attempting to add a Microsoft account, error pops up - XBox user authentication failed, and unable to add a microsoft account
log: https://pastebin.com/QGxRmQkc

### Steps to reproduce

* Open multimc,  & goto Profiles -> Manage Accounts
* Click Add Microsoft
* Sign in from new browser windows
* once signed in, browser window will be blank, MultiMC shows error `XBox user authentication failed.`

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by CaptainMaximus5** [comment]
This happened to me too

**Comment by ExeRhythm** [comment]
Same thing

**Comment by insomnia-creator** [comment]
+1 same here

**Comment by ehylo** [comment]
@CaptainMaximus5 @ExeRhythm @T41US do you guys have the Apple M1 as your CPU?

**Comment by insomnia-creator** [comment]
M1 or not, this is not a huge deal. It's getting translated through Rosetta and that's a problem with code, and not M1. At least one of us mustn't have m1. I've got an M1 and multiMc launcher with my other accounts works fine.

**Comment by fmeunier** [comment]
Yes this is happening with M1 for me

**Comment by CaptainMaximus5** [comment]
It's on m1 and Intel Mac for me

**Comment by T41US** [comment]
@insomnia-creator @ehylo I am running multimc on Big Sur, on a Macbook Pro 15" 2017 + gpu.
Sorry for the late response, I didn't see any activity on the issue until now. Do some on Mac have this working, or does it affect all Mac?

**Comment by phit** [comment]
all MacOS, its related to Qt and will require dropping support for older MacOS versions to fix this

**Comment by CaptainMaximus5** [comment]
@phit when do you think peterix will patch

**Comment by lllldronellll** [comment]
I'm also experiencing this, as I'm running mac os 12 Monterey with an 8750h with the igpu.

**Comment by insomnia-creator** [comment]
No, this is a problem with their code.

**Comment by insomnia-creator** [comment]
> all MacOS, its related to Qt and will require dropping support for older MacOS versions to fix this

This should be done. Apple doesn't officially support older versions anymore. And there are utilities like Patched Sur and Mini Monterey to patch the gap for older macs.

**Comment by Revod** [comment]
I'm having the same problem but with a MacBook Pro 13" Intel CPU

**Comment by kode54** [comment]
It works with the latest Qt from Homebrew, if you build it yourself, and supply your own MSA client ID to the build setup, which means having an Azure account. Which is a totally unsupported scenario, because too much can go wrong with the setup process, and the developers don't want to be there to walk you through the complexity of it all, because it's pretty much a hands on process for anyone less than a supremely talented developer. Also whatever version of Homebrew you use, will produce binaries that don't work on any macOS version older than the major version you build it on.

Have patience that the developers will handle this in due time, but it will definitely mean dropping older versions of macOS than their build solution runs. Possibly 10.15+. And don't expect native M1 builds, either, because even if they do run, they won't support a native version of Minecraft without a native LWJGL. My profile contains a fork of a project that supplies its own alpha LWJGL for 1.13-1.17+, and has its own commit with a stable release of LWJGL3 from the official build servers, but that only seems to work with 1.17+. And further forks of the original project contain split versions of even older LWJGL for running 1.12.x and older. Definitely unsupported territory, because it goes without saying that you're trusting third party binaries beyond this project, and you're trusting technical setup mumbo jumbo that is a far leap from "click and go".

Wait for this project to decide what it needs to do to make this work. Dropping older OS users is apparently in the cards. Universal versions aren't likely to happen any time soon, until such time as Mojang finally makes a move toward supporting ARM. Hell, Microsoft, who have their own official builds of JRE and JDK for Windows, don't even support ARM there yet, either. Mojang may not be eager to make a move with this, since it entails extra development work. And M1 owners make up a fraction of all Mac users at this point, which already make up less than 10% of the total PC market. It will happen when it's ready to happen. Perhaps Apple can help boost it by launching some Serious Hardware based on Apple Silicon. The M1 is already pretty serious, but something with 16+ cores, and 32+ GPU cores, would totally stomp on that, and might be a viable alternative for some compared to waiting for the PC component market to settle.

Sorry for dumping here, hope some of this info is useful, and hope people can either wait to get this working, or know enough to not bother migrating their accounts yet.

**Comment by ExeRhythm** [comment]
@kode54 That's a lot of text... Thanks for clearing that out.

**Comment by insomnia-creator** [comment]
There already are native LWJGLs compiled

https://github.com/yusefnapora/m1-multimc-hack


Good point that you said, but, this is just about the MSA authentication. 

To be honest, if you make the early moves and get a native build running already, there won't be much issue.  

I'm just saying, arm is going to dominate the second apple releases their new macs in the long term. I see most developers just leave it for later, but they need to start compiling it; at least make plans for when you will do so, because ARM support is really required now that it's just not the Surface and some random Linux machines. It's the Macs man, these things dominate the laptop market in their segment.


But anyways, the MSA login affects all Mac users, a major part of the Minecraft community.

**Comment by jamierocks** [comment]
ARM support is off-topic here, as it is unrelated to the issue - so please cease that discussion.

**Comment by insomnia-creator** [comment]
No, we were on the topic when someone raised the question that '"tis the fault of your CPU'
But anyways, what's the roadmap of fixing this?

**Comment by jamierocks** [comment]
See phit's earlier comment.

**Comment by peterix** [comment]
The issue is easily reproducible and no further discussion is needed. Locking this.

**Comment by peterix** [comment]
Fixed.
