### ISSUE TITLE
Microsoft Account Sign-In doesn't work.

### ISSUE THREAD

**Issue by WyvernElement** [MultiMC/MultiMC5#4041]
### Operating System

Windows 11

### Description of bug

The Microsoft Account sign-in gets stuck on "Logging in on XBox and Mojang services".

### Steps to reproduce

Sign in with Microsoft account
Complete sign-in
Wait

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ZzmanzZ** [comment]
> XBox user authentication failed. (MacOS Big Sur, MultiMC 0.6.12-develop-2401)

+1 intel Mac running macOS Big Sur 11.5.2

**Comment by RustyVeteran** [comment]
XBox user authentication failed.

Same issue on a Mac running:
macOS X El Capitan 10.11.6, MultiMC 0.6.12-develop-2409

**Comment by jkcoxson** [comment]
Xbox user authentication failed

macOS Big Sur, M1 MacBook Air

**Comment by phit** [comment]
theres like 3 issues in here, all better covered by other issues

mac users: MSA doesn't work at all right now see https://github.com/MultiMC/MultiMC5/issues/4014 
missing 401 handling https://github.com/MultiMC/MultiMC5/issues/4041#issuecomment-906909484 : see https://github.com/MultiMC/MultiMC5/issues/4025
generic hang better described by https://github.com/MultiMC/MultiMC5/issues/4041 though I assume that that issue is also related to the missing 401 handling

**Comment by CmdrNorthpaw** [comment]
But this *is* #4041 so I don't understand how an issue can describe hanging better than itself.

**Comment by phit** [comment]
fixed the last link
