### ISSUE TITLE
Authentication operation failed due to a network error: Error transferring https://authserver.mojang.com/authenticate - server replied: Gone (207)

### ISSUE THREAD

**Issue by Jeff79** [MultiMC/MultiMC5#4056]
### Operating System

Windows

### Description of bug

Downloaded latest stable, 0.6.12-1530. Unzipped entire folder, started .exe. selected language. Created new instance, vanilla. Went to add account for the first time. Entered migrated Mojang account, now a Microsoft account. Error occurs:

"Authentication operation failed due to a network error: Error transferring https://authserver.mojang.com/authenticate - server replied: Gone (207)"

### Steps to reproduce

Anytime adding a Microsoft account.

Account works on Microsoft launcher, and on the Minecraft.net website.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by peterix** [comment]
You already migrated the account. So it is indeed 'gone'.

Use the dev version and log in with the Microsoft account instead.

Also, because you are even getting this error, it's clear you are using the same passwords for multiple accounts.

that's a really bad idea. I suggest using a password manager and generated, ungeussable passwords you don't need to remember.
