### ISSUE TITLE
custom secrets

### ISSUE THREAD

**Issue by ppoozl** [MultiMC/MultiMC5#4070]
### Role

I compile MultiMC myself.

### Suggestion

Add support to use own custom secrets  to enable Microsoft Account Login.

### Benefit

So I can compile MultiMC myself and have microsoft account login supported.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by kb-1000** [comment]
That's already doable, though we will not provide you support for making custom builds.

**Comment by Artox** [comment]
I know this is closed, but imo - this should be reopened as a feature request - so we can potentially discuss options for providing Microsoft azure credentials at runtime.

I know it is possible, I did a little private experiment for my own enjoyment, but surely there is space for a nice solution here. Rough ideas include, but are not limited to: checking for config files on the system; special environment variables; command-line arguments; **the settings menu** (my preference).

I like Multi-MC, and I like hacking on things. Today I retried running Minecraft natively on an arm64 Linux box, with an amd graphics card. Because I can, and because MultiMC made it easy for me to inject appropriate binaries of lwjgl. This is what I love about open-source, and I would like to see more of it, not less.

**Comment by jamierocks** [comment]
It can already be done, modify `notsecrets/whatever.cpp`. If you want to have a command-line option - I have an alternative implementation you could use (https://git.sr.ht/~jmansfield/MMCSecrets (clone to secrets under multimc directory, see cmake for option)).
