### ISSUE TITLE
Domain ends up on wrong server.

### ISSUE THREAD

**Issue by BluetoDark** [MultiMC/MultiMC5#4122]
### Description of bug

When i use minecraft 1.17.1 I can join through the domain and when I am on 1.8.9 i can also join but it ends up in some unknown server.

The server is running with bungeecord joining through the IP everything works but when joining through domain it does not work for minecraft 1.8.9 other versions it does work.

I tried using other minecraft accounts reinstalling the multimc using different java version but none fixes the issue.

The server ip is 5.135.84.208:19319 the domain is mc.horsehax.com (I know sounds stupid but is not a hack its a troll).

### Steps to reproduce

using the minecraft 1.8.9 instance join through domain that is hooked too a bungeecord server.

### Suspected cause

No idea but it only happens with multimc normal minecraft works fine

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jotoho** [comment]
This is game support, not an issue with MultiMC. Other places like forums or the MultiMC Discord are better suited for this type problem. 

That said, I would investigate if this may be due to missing support for SRV DNS records in older MC versions. The SRV record can be used to make MC use a different hostname or port for connecting to a server.

*For example, I could make an SRV record on my domain (`jotoho.de`) point to a different domain and port (`randomserverhoster.example:19365`) and minecraft would try to connect to the server hoster computer on the designated port rather than my webserver on default port 25565 when typing in `jotoho.de` into MC.*

The SRV record for `mc.horsehax.com` is definitely configured and points to a MC server on `mc.horsehax.com` port 19319.

```console
$ dig SRV _minecraft._tcp.mc.horsehax.com

; <<>> DiG 9.16.21 <<>> SRV _minecraft._tcp.mc.horsehax.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 11704
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;_minecraft._tcp.mc.horsehax.com. IN    SRV

;; ANSWER SECTION:
_minecraft._tcp.mc.horsehax.com. 300 IN SRV     0 0 19319 mc.horsehax.com.

;; Query time: 40 msec
;; SERVER: 192.168.178.3#53(192.168.178.3)
;; WHEN: Fri Sep 24 16:39:09 CEST 2021
;; MSG SIZE  rcvd: 95

```

**Comment by phit** [comment]
SRV records have existed since https://minecraft.fandom.com/wiki/Java_Edition_1.3.1

**Comment by jotoho** [comment]
@phit Oh, cool. I tried to google it but couldn't get a fast answer. So that's probably not it.
