### ISSUE TITLE
Support for Technic Platform and Solder

### ISSUE THREAD

**Issue by nalexander50** [MultiMC/MultiMC5#469]
Feature Request: Ability to track Technic Launcher instances just like FTB instances.

**Comment by DrZed** [comment]
When will the solder stuff be included in dev branch for testing :D because I'd love to use it with my modpack :D

**Comment by kreezxil** [comment]
Ooh,  didn't know that was in dev. Can't wait.

-----Original Message-----

**Comment by spannerman79** [comment]
> When will the solder stuff be included in dev branch for testing :D because I'd love to use it with my modpack :D

I too would also love to know - and try out.

Personally I find MultiMC better then the Technic Launcher.  Not sure why. Perhaps the Technic Launcher tries too hard to look like Windows 8

**Comment by kreezxil** [comment]
Not sure how you think Technic looks like windows. The power of Technic I'd not revealed until interface out with a solder server. When you do that your players will receive updates incrementally instead requiring the entire pack everytime. MultiMC shines as client because it allows you to rapidly try out different mod combinations, bit sadly required an entire pack download for each update. However if the Technic stuff were to go live, MultiMC would be exceptionally useful if connected toa

-----Original Message-----

**Comment by spannerman79** [comment]
> Not sure how you think Technic looks like windows. The power of Technic I'd not revealed until interface out with a solder server. When you do that your players will receive updates incrementally instead requiring the entire pack everytime

I know already, as I have a solder setup for my actual modpack myself.

Its the general look of the client (all their official packs plus other cr@p ) which i don't like personally.

If MultiMC was able to use the Solder API directly in the same way then;

* Incremental Updates would occur - just like the current Technic Launcher
* Solder is changing in `0.7.3` to use actual jar files instead of the current zip format and curse links to comply with some of the current mod dev requirements (Looking at you JourneyMap)

Not to mention some of the issues that some of my friends have had with the actual Technic Launcher running on their system.  If they create an instance in MultiMC, copy over the mods and config folder from the modpack directory from Technic into the MultiMC instance they have no issues launching and connecting.

Not to mention whats built directly into MultiMC if a user has issues (one click client log upload to paste.ee) not to mention one click screenshot uploading without needing any added mods.

I can go on but I think I've made my preference clear :smile:

**Comment by kreezxil** [comment]
I was just making sure you and I were on the same page

-----Original Message-----

**Comment by peterix** [comment]
Moved to workflowy (Ideas -> Packs):
https://workflowy.com/s/2EyDMcp7CU

**Comment by kreezxil** [comment]
is it complete? is this really now a feature of mmc?

**Comment by peterix** [comment]
No, this just got updated because of some organizational changes.

I relabeled all the github issues and did some spring cleaning around here. This included reopening all the Idea issues. There are so many ideas and feature requests that it's really hard to make sense of it all, even in Wokflowy. So I'm giving the tools github added since the move a chance again.

**Comment by GenPage** [comment]
I've started poking around the codebase and figuring out how to setup a dev environment. I wouldn't mind trying to contribute to this to help it along.

**Comment by peterix** [comment]
Any help will be welcome. 

If you come to the discord server, I can hopefully walk you through setting up the dev environment.
The easiest would be running something like linux with KDE, because you basically already have all the things there. Just add the compilers and some code editor.  Maybe devel packages if the distro does those.
Windows will likely be a pain.
MacOS ... I don't know, I leave that to the ci - but there's pretty much just XCode, CMake and Qt from an installer there, along with the 10.7 SDK.

I've done some work on this in the past, but it's really running into a problem with the level of abstraction in the data. MultiMC works with a higher level of abstraction when it comes to the mod loaders -- it's now entries (id:version) in a list of dependencies. On the technic side, it's modpack.jar with some contents that need interpretation. You probably have way more experience with the technic side though :)

So, I see a bit of a disconnect between the two, because going from less abstraction to more abstraction in data means some sort of pattern recognition. I'm wondering how far could translating the technic format(s) and some simple heuristics take this.

Like:
* look in modpack.jar
  * if it has some metadata file that's characteristic for forge jars, read the file and use the version numbers from it
  * if not, tell the user that some assembly might be required

Previous implementations of FTB tracking and experimental technic support involved custom instance types that behaved differently from the normal ones. I think that would result in user confusion (because it just wouldn't be consistent) and more maintenance work. I'd like to translate to the MultiMC format and keep things in the MultiMC format, so there don't have to be weird exceptions in place everywhere in the code.

The other part is that currently, MultiMC does not keep track of where an instance came from and what it was made from on import. I think this information is necessary to determine the deltas for more reliable pack updates. The main issue is that MultiMC encourages customization, and some non-trivial deltas between the original pack, current instance and the pack update are bound to crop up.

**Comment by GenPage** [comment]
I have joined the Discord server. I already use a Debian Stretch VM for DO work so spinning up a another dev VM with KDE shouldn't be too hard at all.

The Technic launcher isn't too complicated at all, the modpack.jar is usually just the modloader (Forge). You can see how the classpath is built [here](https://github.com/TechnicPack/MinecraftCore/blob/master/src/main/java/net/technicpack/minecraftcore/launch/MinecraftLauncher.java#L194). as part of the commands that are appended prior to launching the Minecraft process.

I don't think the data abstraction disconnect will be too problematic (famous last words) as we are going from less abstraction to more abstraction. Since Technic doesn't mess with the modpack files itself, that is something on the end users end, I agree that some soft of pattern recognition would be best as you briefly detailed and suggested.

`experimental technic support involved custom instance types that behaved differently from the normal ones. I think that would result in user confusion (because it just wouldn't be consistent) and more maintenance work. I'd like to translate to the MultiMC format and keep things in the MultiMC format, so there don't have to be weird exceptions in place everywhere in the code.`

This is probably the best path. I am not opposed to it and most likely would depend on me learning the MultiMC format and what changes might be needed.

I'll work on getting a dev environment setup first and poke you on Discord if I run into any troubles.

**Comment by kaeptmblaubaer1000** [comment]
This support would be very useful for me, since the Technic launcher does not include support for HTTP proxies, while MultiMC does.

**Comment by peterix** [comment]
Issue of olde, ARISE FROM THY GRAVE!

**Comment by kreezxil** [comment]
wait, aren't you the Necromancer that created MMC to begin with?

**Comment by peterix** [comment]
Well, sort of. I took over maintenance after Forkk.

**Comment by peterix** [comment]
Anyway, this is now implemented to some extent in the dev builds. Tear it apart and show me the pieces :)

**Comment by kreezxil** [comment]
I'm involved with another launcher now,
https://github.com/KoalaDevs/KoalaLauncher https://koalalauncher.com
anyways, yeah great job on implementing that. It's also on reddit so the
reckoning will begin
https://www.reddit.com/r/feedthebeast/comments/jambps/multimc_supports_installing_technic_packs/?utm_source=share&utm_medium=web2x&context=3

Which was probably a good time to implement it as the state of the launcher
community is in what I see as Flux.
