### ISSUE TITLE
ugocraft mod uses java agent instrumentation. implement support for it in the launcher part.

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#764]
The relevant thread:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/mods-discussion/2300452-ugocraft-mod-for-minecraft-1-7-10

The black magic:
http://docs.oracle.com/javase/7/docs/api/java/lang/instrument/package-summary.html

the loader should get an 'agent jars' list that will be probed for agent arguments (MANIFEST file). call every agent in order specified, THEN call the main class.

**Comment by evernife** [comment]
Hello, i need help, i tried to put the jar mod "Ugocraft'', the same that you linked here, but, i cant do it. There is a error everytime that i try, how can i put this, or there is no way to put any jar mods?

**Comment by peterix** [comment]
it's not a jar mod. It's something entirely different.

**Comment by evernife** [comment]
Sorry for, so... there is a way to install it?
On MultiMC

**Comment by peterix** [comment]
The only answer I can give you is 'not yet'. That is why this issue exists.

**Comment by evernife** [comment]
Ok, ty dude ^^

**Comment by TheDoctorsLife** [comment]
WOW, that's cool

**Comment by robotbrain** [comment]
todo: look into instrumenting a custom classloader

**Comment by FyberOptic** [comment]
I just wanted to point out that Ugocraft works fine, but it appears that you need to make sure to name your instance without any special characters.  I used "Ugocraft [1.7.10]" initially and that causes the mod to get an error (it's trying to load its own JAR in the code and fails to find it), but simply calling it "Ugocraft" works fine.

Unrelated to Ugocraft, my own personal problem is that I need to use ASM from an Instrumentation class, but MultiMC doesn't appear to load any of the libraries yet.  I tried putting it in the classpath on the command line via the Java Arguments but that seemed to be ignored.

**Comment by peterix** [comment]
You'll have to describe that in more detail, because I'm missing a lot of context there.

**Comment by peterix** [comment]
Anything unrelated should go into a separate issue.

**Comment by FyberOptic** [comment]
Well to run an Instrumentation class, all you need is "-javaagent:SOME.JAR" passed on the command line.  That aspect works with MultiMC just fine, it attempts to execute the premain method in the class specified in the manifest, just as you would expect.

The problem is that it seems that none of the libraries specified by the instance's JSON files are added to the classpath initially, nor can I seem to force them to be on the classpath.  So when my Instrumentation class is loaded, it immediately crashes because the ASM library is missing (as well as LaunchWrapper, which my class also uses).  

I'm not entirely familiar with the startup procedure that MultiMC uses, I just know that things get passed through NewLaunch.jar initially.  I'm going to assume that the classpath isn't set up at that point.

In comparison, when you specify a javaagent on the command line in the vanilla launcher, everything behaves properly, it finds the libraries it needs, and the game starts as normal.

**Comment by peterix** [comment]
Yeah. everything goes through the launcher part, which creates its own class loader (currently in develop) or forces the system classloader to load the jar files (currently in stable).

What would need to change is the launcher part implementing javaagent.

It's the stuff here:
https://github.com/MultiMC/MultiMC5/tree/develop/depends/launcher

**Comment by peterix** [comment]
Specifically, these:
https://github.com/MultiMC/MultiMC5/tree/develop/depends/launcher/org/multimc/onesix

**Comment by FyberOptic** [comment]
Keep in mind that the instrumentation class is probably being executed before NewLaunch.jar even gets loaded, so the classpath would already need to be set up beforehand.

**Comment by peterix** [comment]
Well, I would run the instrumentation bits and pieces myself, using reflection, in the right context (MMCClassLoader), not try to do it the normal java way.

From [java.lang.instrument documentation](https://docs.oracle.com/javase/7/docs/api/java/lang/instrument/package-summary.html):
> The manifest of the agent JAR file must contain the attribute Premain-Class. The value of this attribute is the name of the agent class. The agent class must implement a public static premain method similar in principle to the main application entry point. After the Java Virtual Machine (JVM) has initialized, each premain method will be called in the order the agents were specified, then the real application main method will be called. Each premain method must return in order for the startup sequence to proceed.

So, it should be just calling the premain methods in order, before calling the main Minecraft entry point (main, or launchwrapper main).

**Comment by peterix** [comment]
In case of ugocraft, it's in `META-INF/MANIFEST.MF`:
```
Manifest-Version: 1.0
Created-By: Mao
Premain-Class: net.maocat.Loader.Boot.Boot
```

We can read that and just run the class.

**Comment by peterix** [comment]
```
public static void premain(String paramString, Instrumentation paramInstrumentation)
```
The `MMCClassLoader` and the loading mechanism in general would have to create and interact with Instrumentation.

**Comment by FyberOptic** [comment]
Since Instrumentation itself already works fine based on my test of Ugocraft, I think you could get by much easier by simply setting the classpath when running NewLaunch.jar.  I looked through the MultiMC source and found that the libraries from the JSONs appear to be written out into a "launchScript" variable, which appears to be lines of text passed to NewLaunch.jar which it reads from standard input in org.multimc.EntryPoint.listen().  It then uses reflection to add those libraries into the classloader's classpath, and then eventually executes the Minecraft entry point.  You don't appear to use those libaries as the classpath of NewLaunch.jar itself, which would be why my class is crashing, because the Instrumentation class has been executed before anything in NewLaunch.jar is.  

The expected behavior (also in the vanilla launcher) would be that you set those libraries on the classpath when NewLaunch.jar itself is executed, that way all of those libraries are available immediately when the 'premain' method is executed in the Instrumentation class, since it will run before anything in NewLaunch.jar itself ever will. 

You would know more about MultiMC internally than I do so I don't know if you specifically aren't setting the classpath that early for a reason.  But if there's no specific reason, then I would say that's your best bet, and it prevents you from having to do anything at all to make Instrumentation work as expected.

**Comment by peterix** [comment]
Yeah. That would be nice... except that is a workaround for java not handling unicode command line arguments on Windows properly. If you look at the Java command line interface on windows, it can only handle the local codepage:
http://hg.openjdk.java.net/jdk8u/jdk8u40/jdk/file/c7bbaa04eaa8/src/share/bin/main.c#l86

MMC internally is unicode-safe, the text file fed to java is UTF-8 and the java code fills the required variables directly without involving the command line at all.

**Comment by FyberOptic** [comment]
Ah okay, so it was intentional after all.  No worries then, I can understand the position you're in of trying to bridge two languages.  Instead of expecting you to mess up your system, I've gone back and fortunately been able to circumvent the issue entirely in my own code.  I'll describe what I'm doing here in case anyone else finds this thread and has a similar problem.

What my mod does is hook the method where transformers are applied by LaunchWrapper's class loader, because I'm tracking which Forge coremods are modifying which classes as a debug tool.  I initially did it as a standard Forge mod, but that was a total hack of injecting multiple copies of a transformer into the transformers list, which wasn't 100% accurate because some mods modify the list after the fact.  I needed to modify LaunchWrapper itself to have direct access to when transformers are called, but you can't really use ASM on LaunchWrapper via a tweak class or anything because it's already loaded.  That's why I opted for using Instrumentation, because that lets me get in front of LaunchWrapper entirely to modify it before it's loaded.  It's just that in the case of MultiMC, it also gets me in front of NewLaunch.jar, which is where the problem is because no libraries are loaded at that point, and we need ASM.

My solution to this issue was to simply avoid loading a class that uses anything not on the classpath until a point when I know the environment is in a predictable state.  I moved anything that did any ASM or accessed anything from LaunchWrapper out of my main Instrumentation class into a separate one.  My main Instrumentation class also implements my ClassFileTransformer, so when it attempts to transform net.minecraft.launchwrapper.LaunchClassLoader, I execute a static method in a different class (which isn't loaded yet) to modify it via ASM.  By the time anything from LaunchWrapper is being loaded, you'll know that MultiMC's NewLaunch.jar has already set up the classpath, so the class where you're doing the actual ASM activity doesn't cause a crash when loaded by that point.

Even if you're not modifying LaunchWrapper like I am, you can still implement a similar system of waiting until a class from LaunchWrapper is being loaded before initializing anything from an external library, and you should avoid any classpath issues.  It's a trivial workaround and allows MultiMC to retain its unicode-safe system of setting up the classpath.

**Comment by Kilobyte22** [comment]
The best approach might be to actually emulate premain in the wrapper of MultiMC

**Comment by FyberOptic** [comment]
A problem would be how do you get access to the Instrumentation object to pass along unless you make MultiMC's launcher into a javaagent JAR as well.  There are also a few flags in the manifest that can be specified to control the ability to transform classes, although I suppose it's not critical if they're followed as long as you allow full control.

Also, where would the user be expected to place these Instrumentation-based mods so that MultiMC knew to search for them?  You wouldn't necessarily want them in the standard mods folder.

Other than figuring that stuff out, it's not a bad idea to support it, although Ugocraft is the only other mod I know of that uses it.  But I've considered using it to implement coremods into Minecraft 1.2.5 and other older versions as well, so I wouldn't mind seeing more direct support.

**Comment by peterix** [comment]
The Instrumentation object is created from native code, inside some jvmti based agent, inside the JVM. So creating it is a no-go. Grabbing the Instrumentation created by JVM and reusing it later is the only thing I can do without reimplementing the whole thing from scratch or abusing the JVM too much.

So, I'll go with that and see if it works :)

**Comment by malice936** [comment]
base installation instructions work with v0.4.7 IE install the ugocraft jar into the instance minecraft folder, however does not load with forge.

**Comment by peterix** [comment]
Moved to workflowy (Ideas -> Launching):
https://workflowy.com/s/2EyDMcp7CU

**Comment by gamax92** [comment]
Apologies for the bump but I noticed in the instance settings one can set `MCLaunchMethod=DirectJava` and `OverrideMCLaunchMethod=true`, which then launches minecraft with all of the libraries specified on the classpass ahead of time.

Is this a good/bad way to get around the classpath issue with java agents that require it?
