### ISSUE TITLE
Cannot Launch FTB Infinity

### ISSUE THREAD

**Issue by Pieguys** [MultiMC/MultiMC5#787]
So when I try and launch FTB Infinity in the FTB Launcher it downright doesnt do anything, just freezes the launcher. In MultiMC it opens for a few seconds and then closes. This: http://pastebin.com/645Zm7eS is all I could find in the logs. I have reinstalled the modpack and it is still in the directory with my other working modpacks. Is there something I can do?

**Comment by 02JanDal** [comment]
Just tried it, and it doesn't crash for me.

Some things to try: Settings -> MultiMC -> Console, and ensure that only the first of the two boxes is checked ("Show console while game is running?"), and the other is not checked. Then try to launch again. This should give you some scrolling text, see if you can find an error there. If you don't know what to look for, use the "Upload" button and post the paste.ee link you get here.

Also: put MultiMC-0.log on pastebin or similar and post the link here.

**Comment by Pieguys** [comment]
Thanks. I have experience with MultiMC so I know about the uploading. I had the close console button checked so I am going to retry and post results in a bit.

**Comment by Pieguys** [comment]
Ok, here are the results: http://paste.ee/p/hm3Ou

**Comment by Loetkolben** [comment]
For me, it works too (Win7 x64).
The problem seems to be Minecraft beeing unable to find Forge's tweak class (_java.lang.ClassNotFoundException: cpw.mods.fml.common.launcher.FMLTweaker_).
Please provide the MultiMC log file, too. (You only provided the Minecraft log) The MultiMC log file is called **MultiMC-[_Number from 0 to 4_].log** and located in the MultiMC root directory (where MultiMC5.exe or the linux start script is located). The logs are roteted (correct term?), aka the log's numbers are increased every time MMC starts, so the newest log avilable is MultiMC-0.log and the oldest one is MultiMC-4.log.
So, it's easiest to just reproduce the crash, exit from MultiMC and than upload **MultiMC-0.log** to GH gist, pastbin or similar.

**Comment by jikuja** [comment]
It looks like MultiMC is using FTB's libraries/ and version/*/*.jar to start FTB instances located in FTB installation folder. (e.g. C:/Users/Sam/Downloads/libraries/net/minecraftforge/forge/1.7.10-10.13.2.1291/forge-1.7.10-10.13.2.1291-universal.jar)

In this case user selected to install FTB packs into his Downloads folder. Antivirus or similar tampered forge-1.7.10-10.13.2.1291-universal.jar and it can't be opened by JVM.

Fixes: copy FTB instance to real multimc instance to use mmc's libraries or run FTB's force update untill libraries are fixed. Also using better installation location might help.

**Comment by peterix** [comment]
I'm going to assume you managed to fix it on your end.

There are some upcoming changes in the unstable branch that should fix these similar problems with tracked FTB instances. YMMV.
