### ISSUE TITLE
Add option to change instance's ./minecraft/ folder

### ISSUE THREAD

**Issue by tesfabpel** [MultiMC/MultiMC5#788]
Please add an option to change the instance's minecraft folder, so that the default ~/.minecraft can be used.

Thanks :)

**Comment by Kilobyte22** [comment]
You should be able to symlink it to there. Although, I think MultiMC uses a different directory layout. Not exactly sure.
Am 16.02.2015 11:48 schrieb tesfabpel <notifications@github.com>:Please add an option to change the instance's minecraft folder, so that the default ~/.minecraft can be used.

Thanks :)

**Comment by 02JanDal** [comment]
What is it you actually want to achieve? What is your end goal?

**Comment by peterix** [comment]
Right now, I would say anything in the mojang .minecraft is unformatted binary data.

If we allow using the mojang .minecraft folder in any way, it will be through importing.

**Comment by peterix** [comment]
And that is final.
