### ISSUE TITLE
Stupid crashes

### ISSUE THREAD

**Issue by thecarotking** [MultiMC/MultiMC5#791]
Just a whie ago i began using MultiMC. It was great and I put a lot of mods in. But when I added GalactiCraft and Hardcore Ender Expansion I coudn't load my game anymore, it was crashing before it even could load the title screen and in my crash reporter I started geting messages like ''Why did you do that'' or ''I think you shoudn't wory about this''. Plese help me.

Here is my crash: http://paste.ee/p/0bomz

**Comment by Loetkolben** [comment]
The problem seems to be a mod trying to register something for an ID (_170_), but there's already something registered (_java.lang.IllegalArgumentException: ID is already registered: 170_).
You're using Minecraft 1.7.10, right? So there are no more numeric IDs for items.
But reading the stacktrace further makes me think it's a problem with Entity IDs:
    _at net.minecraft.entity.EntityList.func_75618_a_

This probably means you have two mods trying to register an entity for Entity ID 170, what causes the crash.To resolve this, look trough your configs for _Entity ID_ and _170_ and change the dublicate one to a different, unused ID.

Also, it's very likely that this is not a MMC issuse.

**Comment by Heufneutje** [comment]
I'm not sure if Entity IDs have been changed from numeric yet. I know block IDs definitely aren't referenced by a numeric ID anymore, but I'm not sure about entities. 

Judging by the log,
> at micdoodle8.mods.galacticraft.core.util.GCCoreUtil.registerGalacticraftCreature(GCCoreUtil.java:64)

 I'd say GalactiCraft is the issue. The GalactiCraft config might be a good place to start looking for ID 170 as @Loetkolben suggested.
