### ISSUE TITLE
Crashing every time

### ISSUE THREAD

**Issue by KishinPlays** [MultiMC/MultiMC5#807]
When ever I use 1.6.4 Forge 965 it crashes and goes back to the regular screen, im not sure why, it comes up with the log for only a few seconds but as I said it goes back to the home screen, So I cant get any of the logs....

**Comment by KishinPlays** [comment]
Also it doesn't work for any other version of forge.

**Comment by peterix** [comment]
You probably need this mod: http://files.minecraftforge.net/LegacyJavaFixer/legacyjavafixer-1.0.jar

The console closes because Minecraft, for whatever reason, decided not to crash, but exited properly. 

As for keeping the console open, change the multimc settings:
![console](https://cloud.githubusercontent.com/assets/203326/6565553/230cde3e-c6b1-11e4-90e1-2ac22a809d9d.png)

**Comment by KishinPlays** [comment]
Thanks :D @peterix it helped a lot, if I need anything else i'll post it here :+1:
