### ISSUE TITLE
Include MCPatcher

### ISSUE THREAD

**Issue by silvabin90** [MultiMC/MultiMC5#817]
Is it possible to get MCPatcher on MultiMC?

**Comment by Devil-May-Kare** [comment]
I think it's already installed. If you right-click the instance, click "edit instance," and click "change version" in the top-right, the version can be changed, which is, I think, what MCPatcher does.

**Comment by 02JanDal** [comment]
Not really.

The way MCPatcher is installed is quite different from most other things, so it is unlikely that it'll be supported anytime soon.

**Comment by peterix** [comment]
I know how I would do it and it would require a custom build of mcpatcher or changing mcpatcher to not require the vanilla infrastructure to be present.

**Comment by peterix** [comment]
[Moved to workflowy (Ideas -> Integrate MCPatcher)](https://workflowy.com/s/2EyDMcp7CU)

**Comment by Coldwire** [comment]
I can see this has been in the backlog for a while. I just wanted to add in my voice - finding some solution to this (like a custom MCPatcher build) would be a huge help. I'm presently forced to use the old vanilla minecraft launcher if I want MCPatcher features alongside some legacy mods (namely Better Than Wolves). It would be nice to integrate those instances into my MultiMC profile.

**Comment by QuImUfu** [comment]
@Coldwire Same problem here, i copied the MCpatched BTW minecraft.jar and use it as minecraft jar in develop MultiMC. If you want the settings to be keeped, you need to copy an xml file mcpatcher creates, but on my PC, most settings apart from the default are bugged anyway.
I even had to use some old backup of my Minecraft folder and an old version of MCPatcher and java to get MCPatcher to install properly. 
It would be really great if someone with the required java skills would write a last Version for MultiMC that can patch every version of Minecraft MCPatcher ever supported, and make it a jar mod instead of patching the Minecraft.jar directly. If someone wrote such a program, i think there is a good chance peterix would add support for launching it from MultiMC.

**Comment by Coldwire** [comment]
After patching the legacy minecraft launcher with HDTextureFix 5.0.2, it looks like the configuration data is stored in mcpatcher.json in the /.minecraft directory. I used the patched .jar as a jarmod in MultiMC. As usual, I did get the default MCPatcher functionality, but the extra configured features (like Better Grass) were disabled. Putting mcpatcher.json in /.minecraft in the MultiMC instance (predictably) doesn't work. Is there any way to have the .json read in MultiMC?

**Comment by Coldwire** [comment]
I found a workaround that works perfectly. Download gson-x.x.x.jar from [here](https://repo1.maven.org/maven2/com/google/code/gson/gson/2.6.2/), add it as a jarmod along with the patched jar from vanilla.

Move mcpatcher.json from the vanilla launcher ./minecraft to the MultiMC instance ./minecraft.

Bam. Better Grass for days.
