### ISSUE TITLE
FTB Tracking Launcher Location doesn't work with NTFS junctions

### ISSUE THREAD

**Issue by TylerJaacks** [MultiMC/MultiMC5#836]
I have a small SSD which is predominately used as a boot drive but FTB likes to install the launcher in to appdata so I created a junction from my ftb appdata to my documents now it no detect.

**Comment by Heufneutje** [comment]
You can change where MultiMC searches for FTB in the MultiMC settings.

**Comment by peterix** [comment]
NTFS junction points and similar aren't something we are able to deal with. And you can't really change the 'launcher root' from the UI.

I haven't tested this, but it should be possible to change it in the config file. Look for 'multimc.cfg' and inside:
```
FTBLauncherRoot=C:/Users/$USERNAME/AppData/Roaming/ftblauncher
FTBRoot=
```

close MultiMc, change the paths, reopen. Hopefully, that works. Otherwise, it's buggy :)

**Comment by peterix** [comment]
OK. Just going to close this...

I'd rather not spend any time on fixing corner cases in FTB tracking.
