### ISSUE TITLE
Import Instance from URL seemingly not working

### ISSUE THREAD

**Issue by Greenphlem** [MultiMC/MultiMC5#841]
So I exported one of my instances and uploaded them onto my webserver, I then created an instance using that [URL](http://www.magnificentbastards.net/modpack.zip) (if you'd like to test for yourself) It then hangs at the "Task Status" screen with the close button not working

Here's an upload of the MultiMC-0.log: http://paste.ubuntu.com/10686182/ the key lines being around 263-267

**Comment by Kilobyte22** [comment]
Looks like it tries to create a directory containing a colon when downloading the file. While this is completely valid on unix like systems (linux, osx) this breaks on windows. I cannot explain how that causes the freeze though, probably because that code path was never tested on windows - if it was tested at all.
