### ISSUE TITLE
MultiMc Won´t start any ftb instance 

### ISSUE THREAD

**Issue by ibsharam** [MultiMC/MultiMC5#857]
log:http://paste.ee/p/QCk3m

**Comment by TheDoctorsLife** [comment]
[code]Can't load library: /Users/alegomez/Desktop/Ftb Instantces/Initial/direwolf20_17/natives/liblwjgl.jnilib[/code] There's you issue, it's not multimc, it's your FTB instance.

**Comment by peterix** [comment]
I would say... no?

Try updating to java 8

**Comment by Heufneutje** [comment]
Most likely because that's what OSX defaults (or used to default) to.

**Comment by jikuja** [comment]
Java 6 support was broken with https://github.com/LWJGL/lwjgl/commit/a6bb6e31d888c07026ac0381c2900c895765ffbb and fixed in https://github.com/LWJGL/lwjgl/commit/8cdaf59905819bd753257865fc5078aed8af121e

You need to update java or or wait until lwjgl libraries are updated or copy FTB instance as a native multimc instance and hope mmc json use newer lwjgl.

**Comment by Heufneutje** [comment]
Updating Java most likely being the best solution, as Java 6 is pretty old now.

**Comment by peterix** [comment]
We use LWJGL 2.9.1 and the problem shouldn't exist if you use a supported version of java (8).
