### ISSUE TITLE
Feature to automatically update to newest snapshot

### ISSUE THREAD

**Issue by SullyTheUnusual** [MultiMC/MultiMC5#87]
Would it be possible to add a checkbox for instance options to "use latest development version"?

**Comment by peterix** [comment]
Moving this to workflowy: https://workflowy.com/s/2EyDMcp7CU - see Wonko package management -> Add support for meta-versions

**Comment by BlightedBlue** [comment]
Bumping this. It's a really good feature in the launcher and I think it would be a huge improvement to MultiMC.

**Comment by Nixinova** [comment]
Bump also. This is a much-needed feature as manually changing the version all the time is really annoying.

**Comment by Zetabite** [comment]
this is inteded. automatic updates are nasty and against mmc ethos

**Comment by Nixinova** [comment]
Why?

**Comment by Zetabite** [comment]
https://github.com/MultiMC/MultiMC5/issues/2167

**Comment by Nixinova** [comment]
What about #2167?

**Comment by MsWolphie** [comment]
So, ehm, do we know why this suggestion is closed? It has a handful of duplicates years after, so people are willing to use this feature. Peterix themselves were apparently willing to add it at some point?
Also I saw the mention about "auto updates are nasty", but don't see the point of it. We're talking about an option to ask an instance to always use the latest snapshot or stable version, not making every instance auto updating itself?

**Comment by phit** [comment]
@MsWolphie at some point all suggestions and feature requests were closed, for the most part they are just noise. There's probably hundreds of ideas that would be nice to be added, but there's only so much dev power behind this project. Since I've been dealing with issues on here I started to leave suggestions open again, as people will just create the same tickets over and over without searching. So consider #4293 as the current main ticket that's tracking this suggestion. As for the topic of this issue, no idea what the current stance is, but it doesn't really matter like basically [any issue with that label](https://github.com/MultiMC/Launcher/issues?q=is%3Aopen+is%3Aissue+label%3Asuggestion), there is currently no active planning for that topic. There is just a lot of more [pressing issues](https://github.com/MultiMC/Launcher/issues?q=is%3Aopen+is%3Aissue+label%3Afeature) (feature label).
