### ISSUE TITLE
Needs Newer Forges

### ISSUE THREAD

**Issue by NickGamer1** [MultiMC/MultiMC5#959]
I tried downloading the Regrowth mod pack and it says I need to have minecraft forge 1.1.1.321

**Comment by NickGamer1** [comment]
The exact word Forge Mod Loader has found a problem with your minecraft installation the mods and versions listed below could not be found ForgeMultipart : minimum version required is 1.1.1.321 the file 'logs/fml-client-lates.log' contains more ino plz HELP!

**Comment by dmodoomsirius** [comment]
That is not forge its forge Multipart something different.

**Comment by peterix** [comment]
The latest version of the modpack is here:
http://ftb.cursecdn.com/FTB2/modpacks/Regrowth/0_7_4/Regrowth.zip

... It takes forever to download because curse is overloaded ...

And inside, is FMP version 1.1.1.323:
![contents](https://cloud.githubusercontent.com/assets/203326/7677636/15f035ec-fd4e-11e4-929c-54eebcd48c70.png)

So your pack is corrupted in some way.

**Comment by peterix** [comment]
I suggest using the direct download instead of FTB tracking.

**Comment by NickGamer1** [comment]
ok

**Comment by NickGamer1** [comment]
iv tryed using a a direct download and reinstalling multiMc and still the same thing :(

**Comment by NickGamer1** [comment]
so im clueless now ugh i just wanted to play the stupid pack

**Comment by NickGamer1** [comment]
![2015-05-18_09 06 56](https://cloud.githubusercontent.com/assets/12489846/7684742/5f3edfa2-fd3d-11e4-9c73-5341fd3e01c0.png)
