### ISSUE TITLE
Exitcode 255 can someone help me figure out the issue

### ISSUE THREAD

**Issue by carter5051** [MultiMC/MultiMC5#995]
http://paste.ee/p/IRAtB

**Comment by peterix** [comment]
Update and/or change your java in MultiMC to 1.8

**Comment by carter5051** [comment]
thanks

**Comment by carter5051** [comment]
that doesn't work @peterix

**Comment by peterix** [comment]
`/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Commands/java`

Old Apple java.

`Caused by: java.lang.UnsupportedClassVersionError: ExAstris/ExAstris : Unsupported major.minor version 51.0`

Java can't load code because it's built for a newer version of java.

You need a newer version of java.

![java](https://cloud.githubusercontent.com/assets/203326/7779200/c80fcda0-00d2-11e5-876b-772bca082522.png)

If clicking the auto-detect button doesn't find a usable version (1.7.x or 1.8.x), you need to install it.

**Comment by Orcinuss** [comment]
If you are on a mac, I would recommend installing and using java 7 to play minecraft. Macs don't play well with java 8 for MC

**Comment by carter5051** [comment]
@Orcinuss i think i am on java 7

**Comment by carter5051** [comment]
@peterix it gives me like a thing that says
1.8.0_40 
1.6.0_65

**Comment by peterix** [comment]
Then use 1.8.0_40

**Comment by carter5051** [comment]
i have java 8 and i can't find the thing to uninstall it

**Comment by Orcinuss** [comment]
You don't need to uninstall it, you want to use it to launch minecraft.

**Comment by carter5051** [comment]
it says i need to uninstall ti to download Java 7 update 79

**Comment by carter5051** [comment]
nvm it says You are trying to install Java 7 Update 79, however Java 8 Update 40 is already installed.
Visit java.com/newerversionexists for more information.

**Comment by peterix** [comment]
Please just use java 8 and forget 7 ever existed.

**Comment by carter5051** [comment]
then what do i do know @peterix all of the maps have fence gates on them

**Comment by peterix** [comment]
That would be a completely different problem...

**Comment by carter5051** [comment]
@peterix what do i do then
and plus it doesn't say any of the mods

**Comment by peterix** [comment]
I have no idea what that means.
Those sound like separate problems that likely have nothing to do with java.
